### ISSUE TITLE
Maven dependecy injector injects wrong data

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#1043]
on the github action nightly build against tycho 3.0.0
we see this error tonight
```
Error:  Failed to execute goal org.eclipse.tycho:target-platform-configuration:3.0.0-SNAPSHOT:target-platform (default-target-platform) on project org.eclipse.xtext.example.domainmodel.ide: Execution default-target-platform of goal org.eclipse.tycho:target-platform-configuration:3.0.0-SNAPSHOT:target-platform failed: The Maven artifact to be added to the target platform is not stored at the required location on disk: required "/home/runner/.m2/repository/org/osgi/org.osgi.util.promise/1.2.0/org.osgi.util.promise-1.2.0.jar" but was "/home/runner/.m2/repository/p2/osgi/bundle/org.osgi.util.promise/1.2.0.202109301733/org.osgi.util.promise-1.2.0.202109301733.jar" -> [Help 1]
```
https://github.com/itemis/xtext-reference-projects/runs/6855276729?check_suite_focus=true

what does tycho want to tell us.
when i run the build locally, tycho is perfectly fine
same when i run on jenkins

```
export JAVA_HOME=/...../somejava11
git clone https://github.com/itemis/xtext-reference-projects.git
cd xtext-reference-projects/domainmodel/2.28.0/org.eclipse.xtext.example.domainmodel.releng
mvn clean install -Dtycho-version=3.0.0-SNAPSHOT -Ptycho_snapshots --settings ../../../settings.xml -Dmaven.repo.local=.m2
```

on interesting point is this in the log
```
[INFO] ### Using TychoRepositoryTransport for remote P2 access (You can disable this with -Dtycho.p2.transport=ecf) ###
[INFO]     Cache location:         /home/runner/.m2/repository/.cache/tycho
```
is this a new feature? does it work properly with multiple tycho versions?

the cache thing seems to be unrelated.why does tycho resolve/consider local artifacts at all and does not resolve the stuff from the target platform, but downloads stuff from the target platform and then complains about it.

ok. the ide project has
`<pomDependencies>consider</pomDependencies>`
but why is this preferred about p2 deps and why does it work locally and on jenkins

using a separate maven repo seems to help neither
```
Error:  Failed to execute goal org.eclipse.tycho:target-platform-configuration:3.0.0-SNAPSHOT:target-platform (default-target-platform) on project org.eclipse.xtext.example.domainmodel.ide: Execution default-target-platform of goal org.eclipse.tycho:target-platform-configuration:3.0.0-SNAPSHOT:target-platform failed: The Maven artifact to be added to the target platform is not stored at the required location on disk: required "/home/runner/work/xtext-reference-projects/xtext-reference-projects/domainmodel/2.28.0/org.eclipse.xtext.example.domainmodel.releng/.mxxxx2/org/osgi/org.osgi.util.promise/1.2.0/org.osgi.util.promise-1.2.0.jar" but was "/home/runner/work/xtext-reference-projects/xtext-reference-projects/domainmodel/2.28.0/org.eclipse.xtext.example.domainmodel.releng/.mxxxx2/p2/osgi/bundle/org.osgi.util.promise/1.2.0.202109301733/org.osgi.util.promise-1.2.0.202109301733.jar" -> [Help 1]
```

i have no clue where to start investigating. do you @laeubi 

here i a log with debug enabled
https://pipelines.actions.githubusercontent.com/serviceHosts/7f567f03-0c97-4d1b-94b0-cb817cff75a8/_apis/pipelines/1/runs/2128/signedlogcontent/22?urlExpires=2022-06-13T19%3A47%3A48.2827552Z&urlSigningMethod=HMACV1&urlSignature=csbbLWbT6U5AuFjkE5M6GHGKPDLeoki9KSl93nShnlE%3D

on another local machine i can see following entry in generated org.eclipse.xtext.example.domainmodel.ide/.tycho-consumer-pom.xml
```
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>org.osgi.util.promise</artifactId>
      <version>1.2.0</version>
      <type>eclipse-plugin</type>
      <scope>compile</scope>
      <optional>false</optional>
    </dependency>
```
this is also the maven dependency that is nowhere in my pom and not the p2 dependency

2022-06-13T20:29:23.7782565Z [DEBUG] P2resolver.addMavenArtifact org.osgi:org.osgi.util.promise:eclipse-plugin:1.2.0:compile

_Originally posted by @cdietrich in https://github.com/eclipse/tycho/discussions/1015_

**Comment by laeubi** [comment]
FYI @cdietrich

**Comment by cdietrich** [comment]
As mentioned in the discussion the problem is there with maven 3.8.5 and 3.8.6 only 

a reproducer can be found at https://github.com/cdietrich/tycho_discussions1015

**Comment by laeubi** [comment]
@cdietrich the 3.0 SNAPSHOT should include this fix shortly, many thanks for reporting and providing an inital test-case!

**Comment by cdietrich** [comment]
thx @laeubi my reproducer and the original project are green again
