### ISSUE TITLE
Tycho-p2-plugin is not honouring the ignore list

### ISSUE THREAD

**Issue by SarikaSinha** [eclipse/tycho#1053]
https://ci.eclipse.org/jdt/job/eclipse.jdt.debug-github/job/PR-71/2/console

Comparator does not ignore changes in the files listed in filter.

https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/71

**Comment by mickaelistria** [comment]
Are the missing signatures file ("in baseline only") expected/desired?

**Comment by SarikaSinha** [comment]
> @SarikaSinha can you provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue? Beside this I'm not sure what exact "ignore list" is refereed here...

Ignored list mentioned in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/b86734cef0382a2f6fb04c56a1b692f92564298e/eclipse-platform-parent/pom.xml#L532

**Comment by SarikaSinha** [comment]
> Are the missing signatures file ("in baseline only") expected/desired?

15:43:50  [ERROR]    META-INF/ECLIPSE_.RSA: present in baseline only
15:43:50  [ERROR]    META-INF/ECLIPSE_.SF: present in baseline only

These files should not be compared.
No changes in Beta branch for these.

**Comment by iloveeclipse** [comment]
Can we just switch back to some version that doesn't have this issue?
Any chance that anyone can say which tycho version is supposed to work?

**Comment by iloveeclipse** [comment]
> I'd like to repeat my earlier question: "Are the missing signatures file ("in baseline only") expected/desired?"

Yes, in gerrit builds we don't sign anything, in the baseline we do.

**Comment by laeubi** [comment]
By the way I can't find any evidence that `ignoredPatterns` is any valid configuration parameter for the `tycho-p2-plugin`...

**Comment by laeubi** [comment]
> Yes, in gerrit builds we don't sign anything, in the baseline we do.

Should baseline check not be disabled in gerrit builds?

**Comment by mickaelistria** [comment]
I think that the parent pom for BETA_JAVA19 branch is not properly configured:
Build says
```
11:55:33  [INFO] --- tycho-packaging-plugin:3.0.0-SNAPSHOT:build-qualifier (default-build-qualifier) @ org.eclipse.jdt.launching.macosx ---
11:55:33  [INFO] The project's OSGi version is 3.4.800.v20210915-0906
```
so it's building a bundles that wasn't changed for a long time.
But then 
```
11:55:37  [INFO] --- tycho-p2-plugin:3.0.0-SNAPSHOT:p2-metadata-default (default-p2-metadata-default) @ org.eclipse.jdt.launching.macosx ---
11:55:37  [INFO] No baseline version MavenProject: org.eclipse.jdt:org.eclipse.jdt.launching.macosx:3.4.800-SNAPSHOT @ /home/jenkins/agent/workspace/eclipse.jdt.debug-github_PR-71/org.eclipse.jdt.launching.macosx/pom.xml
```
It cannot find a version in baseline (used for replacement). The expectation here would be that existing bundle is found and used.
So
```
11:55:37  [INFO] --- tycho-p2-extras-plugin:3.0.0-SNAPSHOT:compare-version-with-baselines (compare-attached-artifacts-with-release) @ org.eclipse.jdt.launching.macosx ---
11:55:37  [ERROR] Baseline and reactor have same fully qualified version, but with different content
11:55:37  different
11:55:37     META-INF/ECLIPSE_.RSA: present in baseline only
11:55:37     META-INF/ECLIPSE_.SF: present in baseline only
```
It tells that the new bundle doesn't match the expected one.

The error is desired and highlight a build configuration issue. The baseline used by tycho-p2-plugin:3.0.0-SNAPSHOT:p2-metadata-default  should contain the 3.4.800.v20210915-0906 version and this one should replace the local one, and then not fail later one.
