### ISSUE TITLE
Typo "does not exits"

### ISSUE THREAD

**Issue by kriegaex** [eclipse/tycho#111]
https://github.com/eclipse/tycho/search?q=exits&type=code

In two places there is this typo which I just happened to notice during a local build. Please change "exits" to "exist".

**Comment by laeubi** [comment]
@kriegaex thanks for the hint. If you like you can simply click on the "edit" button on top of any file to propose a change. Just make sure you have signed the ECA and we can merge this right away!

**Comment by kriegaex** [comment]
Fine, as long as you do not require a Bugzilla ticket or the ancient but useless "Signed-off-by" header, I can do that. I have experienced Eclipse to be quite bureaucratic and, as a consequence, slow with tedious processes which do not add any value.
