### ISSUE TITLE
Maven Target Location adds undesired artifact

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/tycho#1133]
This change https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/392 had a strange effect that it forces addition of org.apiguardian.api 1.1.0 and fails because this artifact has no OSGi-friendly MANIFEST.MF. However the .target already contains a reference to newer org.apiguardian artifact and the org.apiguardian requirement for commons-io seem to be transitive from the `test` scope, so it probably shouldn't be involved.

**Comment by laeubi** [comment]
> had a strange effect that it forces addition of org.apiguardian.api 1.1.0 and fails because this artifact has no OSGi-friendly MANIFEST.MF

The location seem to be configured to error on a missing manifest so I'm not sure what is the expectation?

> However the .target already contains a reference to newer org.apiguardian artifact

Each location is resolved independently.

> the org.apiguardian requirement for commons-io seem to be transitive from the `test` scope, so it probably shouldn't be involved.

Can you maybe create an example target that shows the wrong behavior?

**Comment by mickaelistria** [comment]
> The location seem to be configured to error on a missing manifest so I'm not sure what is the expectation?

The expectation would be that apiguardian, which is a transtive dependency of a test dependency wouldn't even be considered here.

> Each location is resolved independently.

I locally tried to add apiguardian 1.1.2 (OSGi-compliant) to this location and got the same result.

> Can you maybe create an example target that shows the wrong behavior?

I'll try later. I believe just having commons-io:2.11.0 in the target is enough to get apiguardian erroneously attempted to be resolved.

**Comment by laeubi** [comment]
There might be a bug in Tycho not filtering correctly, maybe we can add a test to `org.eclipse.tycho.test.target.TargetPlatformLocationsTest`

**Comment by mickaelistria** [comment]
https://github.com/eclipse/tycho/pull/1171 is an ITest that reproduces this issue.
More info about this example case
```
$ mvn  dependency:tree -f ~/.m2/repository/commons-io/commons-io/2.11.0/commons-io-2.11.0.pom
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------< commons-io:commons-io >------------------------
[INFO] Building Apache Commons IO 2.11.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:tree (default-cli) @ commons-io ---
[INFO] commons-io:commons-io:jar:2.11.0
[INFO] +- org.junit.jupiter:junit-jupiter:jar:5.7.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter-api:jar:5.7.2:test
[INFO] |  |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
[INFO] |  |  \- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  +- org.junit.jupiter:junit-jupiter-params:jar:5.7.2:test
[INFO] |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.7.2:test
[INFO] |     \- org.junit.platform:junit-platform-engine:jar:1.7.2:test
[INFO] +- org.junit-pioneer:junit-pioneer:jar:1.4.2:test
[INFO] |  +- org.junit.platform:junit-platform-commons:jar:1.7.2:test
[INFO] |  \- org.junit.platform:junit-platform-launcher:jar:1.7.2:test
[INFO] +- org.mockito:mockito-inline:jar:3.11.2:test
[INFO] |  \- org.mockito:mockito-core:jar:3.11.2:test
[INFO] |     +- net.bytebuddy:byte-buddy:jar:1.11.3:test
[INFO] |     +- net.bytebuddy:byte-buddy-agent:jar:1.11.3:test
[INFO] |     \- org.objenesis:objenesis:jar:3.2:test
[INFO] +- com.google.jimfs:jimfs:jar:1.2:test
[INFO] |  \- com.google.guava:guava:jar:30.1-android:test
[INFO] |     +- com.google.guava:failureaccess:jar:1.0.1:test
[INFO] |     +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:test
[INFO] |     +- com.google.code.findbugs:jsr305:jar:3.0.2:test
[INFO] |     +- org.checkerframework:checker-compat-qual:jar:2.5.5:test
[INFO] |     +- com.google.errorprone:error_prone_annotations:jar:2.3.4:test
[INFO] |     \- com.google.j2objc:j2objc-annotations:jar:1.3:test
[INFO] +- org.apache.commons:commons-lang3:jar:3.12.0:test
[INFO] +- org.openjdk.jmh:jmh-core:jar:1.32:test
[INFO] |  +- net.sf.jopt-simple:jopt-simple:jar:4.6:test
[INFO] |  \- org.apache.commons:commons-math3:jar:3.2:test
[INFO] \- org.openjdk.jmh:jmh-generator-annprocess:jar:1.32:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```
and
```
$ mvn  dependency:tree -f ~/.m2/repository/commons-io/commons-io/2.11.0/commons-io-2.11.0.pom -Dscope=compile
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------< commons-io:commons-io >------------------------
[INFO] Building Apache Commons IO 2.11.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:tree (default-cli) @ commons-io ---
[INFO] commons-io:commons-io:jar:2.11.0
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.949 s
[INFO] Finished at: 2022-07-20T11:22:32+02:00
[INFO] ------------------------------------------------------------------------
```
