### ISSUE TITLE
Change the default value for requireJREPackageImports

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#1136]
I just noticed here:

https://www.eclipse.org/tycho/sitedocs/tycho-compiler-plugin/compile-mojo.html#requireJREPackageImports

that the default for `requireJREPackageImports` is `false`. With modular VMs any "default jre packages" become meaningless and I think we should change this to `true` to give better guidance to the user (even if PDE still do not have good support for this).

**Comment by mickaelistria** [comment]
> even if PDE still do not have good support for this

What does it mean exactly? If forcing usage of JRE packages at build-time make the dev-time less usable (more issues to tackle in PDE), then Tycho shouldn't do it as it overall wouldn't serve users.

**Comment by laeubi** [comment]
> What does it mean exactly?

I can't find the PDE bug, but PDE currently assumes that `javax.*` (and probably some other packages) are "auto imported" by an Equinox specific feature called [osgi.compatibility.bootdelegation](https://wiki.eclipse.org/Equinox_Boot_Delegation#The_solution). This leads to hard to track and cryptic errors when using JVM >= 9 because you don't get the usual error/warnings about missing imports, the bad thing is that the [eclipse-launcher defaults it to true](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Fruntime-options.html) while the equinox default is `false`, so depending on where you run your bundle (e.g. on java 8 with bootdelegation on because using the executable launcher) it works, or fails (e.g using java 9 or plain equinox/felix framework).

> then Tycho shouldn't do it as it overall wouldn't serve users

If users absolutely require this compatibility **(!)** feature they can still configure it explicitly but I'm not even sure this option has any useful effect for anything >=11 were lots of stuff was already removed and afaik Java 17 will even remove more. And as we have said in #522 we do no longer want to support non-modular vms in 3.x I think its a good opportunity to change the default and even deprecate the option at all.

**Comment by mickaelistria** [comment]
> If users absolutely require this compatibility (!) feature they can still configure it explicitly but I'm not even sure this option has any useful effect for anything >=11 were lots of stuff was already removed and afaik Java 17 will even remove more.

We do want to provide that kind of compatibility to users because we don't want to make their work harder.
Before switching it, we should try it on a few projects of choice (including Platform) to get a sense of what it would imply to users. If it brings tons of unexpected and not so useful new errors that are hard to troubleshoot, then it's probably not worth it. If it requires a couple of adjustments to provide some better value, it can be worth it.

**Comment by laeubi** [comment]
@akurtakov as you are dedicated to enforcing modern java support, WDYT?

**Comment by akurtakov** [comment]
I think we can change the default value and clearly document how to flip it back for projects that can't handle these changes right now.
Platform would most probably do that as I don't see how the ~500 bundles will be handled in timely manner.
Even when it's not required we should spit warnings in bundles that disable it but use such imports so things can be cleaned up in chunks.

**Comment by akurtakov** [comment]
Thinking more about it - before flipping the default, the warnings should be implementd and visible for some period.

**Comment by laeubi** [comment]
> Platform would most probably do that as I don't see how the ~500 bundles will be handled in timely manner.

As explained it might be that nothing has to be changed as already this do not work anymore, I'll try to run some build and see if it actually harm anything.

> Even when it's not required we should spit warnings in bundles that disable it but use such imports so things can be cleaned up in chunks.

I'm not sure if that's possible to determine easily, maybe the compiler will complain, I think we could do it in the following steps:

1. change the default and see if any integration test fails, we can probably better decide then
2. build some platform projects and see how it behaves
3. merge and document in the migration guide (I think its quite easy to enable for people having issues) and simply add a warning if this option is explicitly set.

**Comment by akurtakov** [comment]
If building platform.releng.aggregator works without many extra changes I think nothing else will demand bigger changes.
