### ISSUE TITLE
tycho-p2-director-plugin - materialize-products fails - No algorithm found for 1.2.840.113549.1.1.11 (SHA256withRSA)

### ISSUE THREAD

**Issue by minduch** [eclipse/tycho#116]
Using Tycho 2.3.0, we get the attached error. Without signing it works fine. We use a GlobalSign EV Code Signing certificate with PKCS11 USB Dongle. The problem seems to be in the code below:
```
java.security.NoSuchAlgorithmException: An error occurred while processing the signatures for the file: C:\Jenkins\workspace\iizi\com.iizigo.product\target\products\com.iizigo.product\win32\win32\x86_64\iiziGo\plugins\com.iizigo_1.6.0.15472.jar
	at org.eclipse.osgi.internal.signedcontent.SignedBundleHook.getSignedContent(SignedBundleHook.java:231)
	at org.eclipse.equinox.internal.p2.engine.phases.CertificateChecker.checkCertificates(CertificateChecker.java:77)
	at org.eclipse.equinox.internal.p2.engine.phases.CertificateChecker.start(CertificateChecker.java:58)
	at org.eclipse.equinox.internal.p2.engine.phases.CheckTrust.completePhase(CheckTrust.java:55)
	at org.eclipse.equinox.internal.p2.engine.Phase.postPerform(Phase.java:254)
	at org.eclipse.equinox.internal.p2.engine.Phase.perform(Phase.java:105)
```

[tycho-err.txt](https://github.com/eclipse/tycho/files/6417605/tycho-err.txt)

**Comment by minduch** [comment]
After the error occurs, I am trying to verify the signature using jarsigner, and it reports that the file does not exist. I have seen other comments and bugs related to this.

**Comment by minduch** [comment]
Same problem with Tycho 2.4.0-SNAPSHOT (3rd May 2021), here with all debug log file attached.
[tycho-err-2.4.0-SNAPSHOT-full.txt.zip](https://github.com/eclipse/tycho/files/6417896/tycho-err-2.4.0-SNAPSHOT-full.txt.zip)

**Comment by mickaelistria** [comment]
This is upstream issue https://bugs.eclipse.org/bugs/show_bug.cgi?id=572034 in p2. This will.be fixed when Tycho moves to newer version of Eclipse Platform.

**Comment by minduch** [comment]
Seems like this will be fixed in Eclipse 4.20 (target milestone M3) for Eclipse OSGI, so I guess that this will be fixed for Tycho as well.

The problem in our case is the timestamp authority http://rfc3161timestamp.globalsign.com/advanced that signs with a SHA256withSHA256withRSA signature that is not yet supported.

FYI: A workaround fix right now is to use the Comodo timestamp authority URL http://timestamp.comodoca.com/rfc3161.

**Comment by minduch** [comment]
FYI: DigiCert just released the following information...

Starting from May 27, 2021, 14:00 MDT (20:00 UTC), DigiCert® will require 3072-bit RSA keys or larger for code signing certificates. This change is to comply with industry standards. These new RSA key size requirements apply to the complete certificate chain: end-entity, intermediate CA, and root. Note that ECC key requirements remain unchanged. 
•	Code signing certificates issued before May 27 require no change and will work until they expire. 
•	After May 27, new, renewed, and reissued code signing certificates from DigiCert will automatically issue with new intermediate CAs and roots. 
•	After May 27, all code signing certificates will require CSRs with 3072-bit or larger RSA keys. EV code signing certificates will need a new token or an HSM that supports at least 3072-bit keys.

**Comment by laeubi** [comment]
I'll reopen this as we needd to take some actions on this.

**Comment by laeubi** [comment]
@minduch can you please check with latest tycho 2.4.0 release if the problem persists?
