### ISSUE TITLE
Tycho not able to build more than one product configuration file

### ISSUE THREAD

**Issue by vogella** [eclipse/tycho#118]
If I create another product configuration file in the same project (with different ID's) the build fails. Tycho ask to configure the attachId, which is something that AFAIK it not available in the product configuration file.

I'm using a pomless build for this example.

[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-director-plugin:2.3.0:archive-products (archive-products) on project rcp.product: Artifact file names for the archived products are not unique. Configure the attachId or select a subset of products. Current configuration: [Product [id=rcp.product, attachId=null], Product [id=rcp.product.debug, attachId=null]] -> [Help 1]

**Comment by laeubi** [comment]
Can you share an example? I use a pomless builds with different products in the same folder without a problem (using tycho pomless 2.3.0).

**Comment by laeubi** [comment]
@vogella ca you provide an example (or better a PR with itest) that shows the problem?

**Comment by vogella** [comment]
@laeubi https://github.com/vogellacompany/tycho-example has been updated to contain two products and it works fine. So the issue must be with the configuration of the RCP client. As I now have a working setup, I can fix his.

Sorry for the noise.

**Comment by laeubi** [comment]
As mentioned this feature was added recently to tycho-pomless so make sure the version of tycho-pomless is updated in .mvn/extensions.xml as well.
