### ISSUE TITLE
Unable to deploy artifacts in parallel

### ISSUE THREAD

**Issue by pzi-dsa** [eclipse/tycho#1212]
When trying to deploy our artifacts in parallel, I get the following error:

> Execution default-update-local-index of goal org.eclipse.tycho:tycho-p2-plugin:3.0.0-SNAPSHOT:update-local-index failed: already locked file E:\jenkins\workspace\atm~e4_20_COR---04f4a81e\CORE\..\.m2\.meta\p2-artifacts.properties

A sequential deployment works just fine.

What I find weird is that I have set `maven.install.skip` to `true`, so there should be nothing to update the index with.

The update-local-index Mojo should support parallel builds, so there shouldn't be more than one thread modifying the index at a time.

We build on Windows 10 and with the maven-deploy-plugin v3.0.0.

**Comment by laeubi** [comment]
If it is reprocuable, can you post a stacktrace with `-e` switch?

**Comment by laeubi** [comment]
Strange enough this code path IS already synchronized, so knowing where the exception exactly occurs would be useful!

**Comment by laeubi** [comment]
@pzi-dsa I think there are some inconsistencies in Tycho regarding the index, I prepared a patch for this particular case now, if this is reproducible for you it would be great when you can try out the patch.

**Comment by pzi-dsa** [comment]
With the latest snapshot, parallel deployment works without issues. Thanks again for looking into this!
