### ISSUE TITLE
BaselineValidateAndReplaceTest fails on windows

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#1240]
On windows the test fails with:
```
[INFO] Reactor Summary for baseline-parent 1.0.0-SNAPSHOT:
[INFO] 
[INFO] baseline-parent .................................... SUCCESS [  0.075 s]
[INFO] baseline.feature02 ................................. FAILURE [  0.930 s]
[INFO] baseline.repository ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.021 s
[INFO] Finished at: 2022-08-03T09:33:44Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-plugin:3.0.0-SNAPSHOT:p2-metadata-default (default-p2-metadata-default) on project baseline.feature02: baseline and build artifacts have same version but different contents
[ERROR]    classifier-root: not present in baseline
[ERROR]    no-classifier: different
[ERROR]       feature.xml: different
[ERROR] -> [Help 1]
```

@mickaelistria as you are more familiar with the baseline stuff, any chance to look into this? This might be a problem of line-ending normalization required before comparing files?

**Comment by mickaelistria** [comment]
Yes, it could be a problem of line ending. The comparison does compare files byte-to-byte, so any difference breaks the comparison. Retrieving the content of the generated feature.xml and diffing it with baseline would easily reveal the actual difference and hint about remediation.
However, I won't be able to dig deeper as I don't use Windows.

**Comment by laeubi** [comment]
> However, I won't be able to dig deeper as I don't use Windows.

We have a windows verification build, so if you like to add some debug or try to improve the comparator for known test-files (e.g. txt/xml/...) maybe @pzi-dsa can also help here as he is using windows...
