### ISSUE TITLE
BundleException: Bundle bundle cannot be resolved with tycho 2.3.0

### ISSUE THREAD

**Issue by jhonnen** [eclipse/tycho#135]
I'm getting the following BundleException with tycho 2.3.0, but tycho 2.2.0 works:

```
Caused by: org.osgi.framework.BundleException: Bundle bundle cannot be resolved:bundle [100]
  Unresolved requirement: Require-Bundle: com.collabnet.subversion.merge
    -> Bundle-SymbolicName: com.collabnet.subversion.merge; bundle-version="4.2.0.1"; singleton:="true"
       com.collabnet.subversion.merge [1]
         Unresolved requirement: Require-Bundle: org.eclipse.jdt.core

    at org.eclipse.tycho.core.osgitools.EquinoxResolver.assertResolved (EquinoxResolver.java:423)
    at org.eclipse.tycho.core.osgitools.EquinoxResolver.newResolvedState (EquinoxResolver.java:127)
    at org.eclipse.tycho.core.osgitools.OsgiBundleProject.getResolverState (OsgiBundleProject.java:281)
    at org.eclipse.tycho.core.osgitools.OsgiBundleProject.resolveClassPath (OsgiBundleProject.java:177)
    at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject (DefaultTychoResolver.java:142)
```

I've published a reproducer here: https://github.com/jhonnen/tychorepro

**Comment by jhonnen** [comment]
When I add an `Require-Bundle: org.eclipse.jdt.core` in bundle, the build works. Without the direct dependency, jdt.core is not present in the DependencyArtifacts.

**Comment by mickaelistria** [comment]
I'm not going to investigate it in more details anytime soon, but my impression is that since the resolver become more correct (and "pedantic" in 2.3), this can highlight that the p2 metadata of the dependency are not really matching the actual requirements; so the 1st round of dependency gathering (against p2) misses content that are actually required later.

**Comment by jhonnen** [comment]
You're right, jdt.core is missing in the p2 metadata from https://subclipse.github.io/updates/subclipse/4.3.3/content.jar

    <unit id='com.collabnet.subversion.merge' version='4.2.0.1'>
      <update id='com.collabnet.subversion.merge' range='[0.0.0,4.2.0.1)' severity='0'/>
      ...
      <requires size='14'>
        <required namespace='osgi.bundle' name='org.eclipse.ui' range='3.3.0'/>
        <required namespace='osgi.bundle' name='org.eclipse.core.runtime' range='3.3.0'/>
        <required namespace='osgi.bundle' name='org.tigris.subversion.subclipse.ui' range='1.10.0'/>
        <required namespace='osgi.bundle' name='org.tigris.subversion.subclipse.core' range='1.10.0'/>
        <required namespace='osgi.bundle' name='org.eclipse.core.resources' range='3.3.0'/>
        <required namespace='osgi.bundle' name='org.eclipse.team.core' range='3.3.0'/>
        <required namespace='osgi.bundle' name='org.eclipse.team.ui' range='3.3.0'/>
        <required namespace='osgi.bundle' name='org.eclipse.ui.ide' range='3.3.0'/>
        <required namespace='osgi.bundle' name='org.eclipse.ui.views' range='3.2.0'/>
        <required namespace='osgi.bundle' name='org.eclipse.compare' range='3.3.0'/>
        <required namespace='osgi.bundle' name='org.eclipse.ui.editors' range='3.3.0'/>
        <required namespace='osgi.bundle' name='org.eclipse.jface.text' range='3.3.0'/>
        <required namespace='osgi.bundle' name='org.eclipse.ui.forms' range='3.3.0'/>
        <required namespace='osgi.bundle' name='org.eclipse.core.filesystem' range='1.1.0'/>
      </requires>

**Comment by laeubi** [comment]
@jhonnen can you provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue? Is this still a problem on more recent tycho versions?

**Comment by jhonnen** [comment]
I've tried the reproducer with tycho 2.7.3 and the error is gone.

**Comment by laeubi** [comment]
Thanks for verification!
