### ISSUE TITLE
Update Eclipse Installer for Tycho to use github repository

### ISSUE THREAD

**Issue by and-k** [eclipse/tycho#142]
I followed the instructions in https://github.com/eclipse/tycho/blob/master/CONTRIBUTING.md to setup a development environment. The setup fails because the repository https://git.eclipse.org/r/tycho/org.eclipse.tycho doesn't exist:

Cloning Git repo https://git.eclipse.org/r/tycho/org.eclipse.tycho to C:\Eclipse\tycho-master\git\org.eclipse.tycho
java.lang.Exception: org.eclipse.jgit.api.errors.TransportException: https://git.eclipse.org/r/tycho/org.eclipse.tycho: tycho/org.eclipse.tycho unavailable
...

**Comment by mickaelistria** [comment]
If using the installer doesn't work, please try the manual steps in the meantime; those should be more up-to-date.

**Comment by LorenzoBettini** [comment]
For the time being, it's enough to replace the git URI in the installer dialog with the new URI: https://github.com/eclipse/tycho.git

then everything should work (I've just tried that). Unfortunately the URI will be setup as gerrit, but that should not be a problem.

@mickaelistria I'm going to provide a PR for this, is that OK?

**Comment by mickaelistria** [comment]
I have no interest in that part, so feel free to submit the PR and if no-one reacts I'll merge it.
Maybe @laeubi will be more helpful than me here.

**Comment by laeubi** [comment]
@LorenzoBettini Fell free to improve here, contributions are welcome as we currently have no one that work in this area.

**Comment by LorenzoBettini** [comment]
@laeubi I created https://github.com/eclipse/tycho/pull/144

please note that once it is merged, the official Oomph catalog should be updated as well, https://git.eclipse.org/c/oomph/org.eclipse.oomph.git/tree/setups/org.eclipse.projects.setup, since that points to the old Git repository. I think it is enough to open a bug here https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Oomph&component=Setup&bug_severity=enhancement&short_desc=Please%20include%20setup%20for%20project%20Xyz

**Comment by laeubi** [comment]
@LorenzoBettini I think you can open a bug right now against the Oomph catalog, the old entry is of no value anyways...

**Comment by LorenzoBettini** [comment]
@laeubi before doing that the new setup file must be in place, otherwise the catalog will point to something that does not exist... that's why I'm waiting for #144 to be merged

**Comment by laeubi** [comment]
But [setup/Tycho.setup](https://github.com/eclipse/tycho/blob/master/setup/Tycho.setup) does already exits here or do you refer to a different file?

**Comment by LorenzoBettini** [comment]
Sorry, you're right: Yes, that file already exists, so this entry in the Oomph catalog would be valid:

```xml
<project href="https://raw.githubusercontent.com/eclipse/tycho/master/setup/Tycho.setup#/"/>
```

Just like the old one:

```xml
<project href="https://git.eclipse.org/c/tycho/org.eclipse.tycho.git/plain/setup/Tycho.setup#/"/>
```

Currently, they are the same file, so they both refer to the wrong Git URI... if you want I can open a bug in the meantime...

**Comment by laeubi** [comment]
Just open the bug, as we don't make anything more 'worse' and I think we can merge the change soon so work could be done 'in parallel'

**Comment by LorenzoBettini** [comment]
OK, done: https://bugs.eclipse.org/bugs/show_bug.cgi?id=481088 I simply reopened the original bug

**Comment by LorenzoBettini** [comment]
@laeubi the bug above has been resolved, could we also merge the PR?

**Comment by laeubi** [comment]
Thanks for the fix @LorenzoBettini

**Comment by LorenzoBettini** [comment]
My pleasure, happy contributions! :)
