### ISSUE TITLE
move tycho-pomless from 'extras' to 'core' and drop 'tycho-pomgenerator:generate-poms' mojo

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#148]
tycho-pomless has become a fully fledged solution to build pde projects and thus I think its time to remove it's 'extra' nature.

This won't harm much, as the only thing required when upgrading from a previous version is to adjust the version **and** group id once. 
On the other side it would be good to remove the `tycho-pomgenerator:generate-poms` mojo as it is not actively developed/maintained see the [recent news-group discussion](https://www.eclipse.org/lists/tycho-user/msg09099.html). Instead we should suggest to use a pomless-build with `-Dpolyglot.dump.pom=pom.xml` if one needs to generate `pom.xml` files. That way we only need to maintain tycho-pomless what gives much more benefits on its own beside generating pom.xml files.

**Comment by laeubi** [comment]
It might be better to integrate pomless in a generic build extension as described in 
- #556

**Comment by akurtakov** [comment]
With tycho-build extension added in 2.7  and tycho-pomgenerator:generate-poms removed I consider this one done.
