### ISSUE TITLE
Tycho publishes too much

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#155]
I run a pure J11 build (j11 jdk and all bundles require JavaSE11) Tycho still instals profiles for 14,15,16 ...

```
[INFO] --- tycho-p2-publisher-plugin:2.2.0:publish-osgi-ee (default-publish-osgi-ee) @ de.laeubisoft.products.labratry.sgs ---
[INFO] Published profile IUs: [a.jre.javase 11.0.0, config.a.jre.javase 11.0.0]
[INFO] Published profile IUs: [config.a.jre.javase 14.0.0, a.jre.javase 14.0.0]
[INFO] Published profile IUs: [config.a.jre.javase 15.0.0, a.jre.javase 15.0.0]
[INFO] Published profile IUs: [config.a.jre.javase 16.0.0, a.jre.javase 16.0.0]
```

**Comment by mickaelistria** [comment]
That's tricky because of https://bugs.eclipse.org/bugs/show_bug.cgi?id=568150 . More EE units can be necessary for example if you run your product with Java 16 and try to install an extra bundle that does require JavaSE-16; then the JavaSE-11 unit won't satisfy the requirement. And https://bugs.eclipse.org/bugs/show_bug.cgi?id=568150 is the solution to the whole family of problems so we should probably not try to workaround it in Tycho but instead focus on the root of evil.
In the meantime you can control which EE are published with https://www.eclipse.org/tycho/sitedocs/tycho-p2/tycho-p2-publisher-plugin/publish-osgi-ee-mojo.html

**Comment by laeubi** [comment]
> In the meantime you can control which EE are published with

I just though of to automate it a bit so by default publish-osgi-ee uses the set of ee it finds in the build instead of a fixed list (that seems to be outdated in the description of the mojo anyways as t is missing JavaSE-14)

**Comment by mickaelistria** [comment]
I recommend you look at https://bugs.eclipse.org/bugs/show_bug.cgi?id=568150  instead ; once this one is fixed, there won't be need to publish EE units any more and many more problems will be solved. Basically making everything everything simpler, more powerful and more correct. ROI is much more interesting...

**Comment by laeubi** [comment]
And ROF (return of frustration) is maybe even higher, it usually ends up in endless cycles of discussion and complains because "something" works different than before and there's always someone unhappy with this... just in case I'm able to fix this for P2 there will be instant complains because PDE target does not support it in a similar way and so on, the next complain would be if the new update-site does not work with older eclipse, builds, whatever and why we do not support those for the next 50+ years...

**Comment by mickaelistria** [comment]
> there's always someone unhappy with this...

If you look at the bug, you'll see that all active maintainers of p2 do support this change and that it's perceived as important. Some people will be unhappy, but I think that the ones that take the decision would be happy enough.

> will be instant complains because PDE target does not support it in a similar way

That will be a bug in PDE then, but a lot of other bugs will be fixed. I don't think it would be a blocker, but some more discussion can happen on https://bugs.eclipse.org/bugs/show_bug.cgi?id=568150 to evaluate that.

> and so on, the next complain would be if the new update-site does not work with older eclipse,

That's not true. This would be a runtime change. The content of the p2 repo are controlled at build time and we can totally keep generating EE units in the Platform repo for compatibility with older versions.
