### ISSUE TITLE
Skip Tycho dependency resolution for clean-only builds by default

### ISSUE THREAD

**Issue by HannesWell** [eclipse/tycho#166]
When you want to clean Eclipse projects build with Maven/Tycho the dependency resolution is performed initially by default, even tough it is not necessary (please correct me if I'm wrong). For large projects the dependency resolution takes the vast majority of runtime in a `clean`-only build.

In order to speed-up `clean` builds, one can specify the property `-Dtycho.mode=maven` to skip the dependency resolution.

For convenience (on the command-line and in the IDE) and to speed up cleans for users that do not know about the mentioned property I suggest to skip the dependency resolution by default for clean only builds.
This could be accomplished in `TychoMavenLifecycleParticipant.disableLifecycleParticipation(Seesion)` by checking if the session only has the goal `"clean"`.

If nothing else speaks against it, I can provide a patch to change that default behavior for clean-only builds.

**Comment by mickaelistria** [comment]
Tycho somehow modifies the Maven model by adding dependencies, but AFAIK,it does affect the typical "dirty" directories that clean is supposed to process. So ok, let's try it!

**Comment by HannesWell** [comment]
> Tycho somehow modifies the Maven model by adding dependencies, but AFAIK,it does affect the typical "dirty" directories that clean is supposed to process. So ok, let's try it!

You meant `does not affect`, don't you?

Because yes, the modifications of the Maven-model performed by Tycho in `TychoMavenLifecycleParticipant.afterProjectsRead` do affect the model, but I think they are not necessary for running a clean build.
At least I got that impression when looking at `TychoMavenLifecycleParticipant.afterProjectsRead(MavenSession)` and what happens after the initial if statement that calls disableLifecycleParticipation(MavenSession).
The additional validation and configuration performed here seems unnecessary for cleaning and skipping the dependency resolution is the intention of this change.

I'm about to open a PR to address this.
