### ISSUE TITLE
AllKnownEEsResolutionHints is missing equals/hascode causing target resoloution for every project

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#170]
If `AllKnownEEsResolutionHints` is used (e.g. `<resolveWithExecutionEnvironmentConstraints>false</resolveWithExecutionEnvironmentConstraints>` configured in the build) the target is resolved over and over again because AllKnownEEsResolutionHints do not use any caching or meaningful equals/hashcode implementation

**Comment by mickaelistria** [comment]
Good catch! Shouldn't we make AllKnownEEResolutionHints a singleton as well?

**Comment by laeubi** [comment]
I have first though about that but it is created on a per project basis and fills the EEs from the project somewhat... So i have not investigated how this might be cached somewhere...

**Comment by mickaelistria** [comment]
OK
