### ISSUE TITLE
Info.plist not configured correctly on MacOS

### ISSUE THREAD

**Issue by UdoW** [eclipse/tycho#193]
I build an Eclipse product with Tycho. I do it for the three platforms Windows, Linux and MacOs. For all 3 platforms it works but for MacOS the file Info.plist is not populated correctly.

I use the JustJ feature to include a Java 11 JRE into my product. For Windows and Linux the option `-vm path-to-Java` is added correctly to the productname.ini file. This is also done for MacOS but MacOS needs this option in the `<array>` section of the file `Info.plist`.
In this file it should look like this:

`<string>-vm</string><string>../Eclipse/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.macosx.x86_64_11.0.2.v20200815-0835/jre/lib/jli/libjli.dylib</string>`

I tried to add the -vm option to the `<programArgsMac>` section of my product definition file but it is not copied to the file Info.plist. Other additional program options are copied correctly.

I tried with Tycho 2.3.0 and Eclipse target platform 2021-06.

**Comment by mickaelistria** [comment]
The Info.plist is not generated by Tycho, but by p2 director. So I think it should be reported to p2, with steps to reproduce that do not involve Tycho. This can typically be an example p2 repository which contain the product definition and the p2 director command to provision the macos product.
Please add a link from here to the p2 issue when it's reported.

**Comment by UdoW** [comment]
The same problem occurs also in the Tycho example project `itp04-rcp` .

**Comment by UdoW** [comment]
Eclipse bug entry: [https://bugs.eclipse.org/bugs/show_bug.cgi?id=574924](https://bugs.eclipse.org/bugs/show_bug.cgi?id=574924)

**Comment by UdoW** [comment]
Yo can close the issue as it is not a bug. My problems result from the fact that my app is not signed.

I only need to call the command `xattr -r -d com.apple.quarantine <name of unpacked Eclipse based app>` and then my unsigned app starts. No need to change the file Info.plist.
