### ISSUE TITLE
Tycho hangs on fetching and eventually crashes

### ISSUE THREAD

**Issue by wimjongman** [eclipse/tycho#197]
I have a situation where Tycho hangs for a couple of hours (I left it overnight) and then crashes. Please see the attached logs and jvm dumps.

I also have the dmp and trc files if needed but they are huge.

[log.txt](https://github.com/eclipse/tycho/files/6854325/log.txt)
[javacore.20210721.101717.22980.0004.txt](https://github.com/eclipse/tycho/files/6854364/javacore.20210721.101717.22980.0004.txt)
[javacore.20210721.101717.22980.0005.txt](https://github.com/eclipse/tycho/files/6854366/javacore.20210721.101717.22980.0005.txt)

**Comment by wimjongman** [comment]
Here is another log snippet where it more explicitly hangs on resolving a bundle.

[log.txt](https://github.com/eclipse/tycho/files/6854887/log.txt)

**Comment by wimjongman** [comment]
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: C:\Users\jongw\programs\apache-maven-3.8.1\bin\..
Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: C:\users\jongw\programs\AdoptOpenJDK\jdk-11.0.11.9-openj9
Default locale: en_NL, platform encoding: UTF8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by mickaelistria** [comment]
Do you have an example project that can reproduce the issue?
Does the isuse happen with other/newer JVMs?

**Comment by cdietrich** [comment]
do you also have a thread dump (jstack)

**Comment by wimjongman** [comment]
jstacks 1/2/3 a few seconds apart

jstacks 4/5/6 a couple of minutes later also a few seconds apart


[stack1.txt](https://github.com/eclipse/tycho/files/6854992/stack1.txt)
[stack2.txt](https://github.com/eclipse/tycho/files/6854993/stack2.txt)
[stack3.txt](https://github.com/eclipse/tycho/files/6854994/stack3.txt)
[stack4.txt](https://github.com/eclipse/tycho/files/6854995/stack4.txt)
[stack5.txt](https://github.com/eclipse/tycho/files/6854996/stack5.txt)
[stack6.txt](https://github.com/eclipse/tycho/files/6854997/stack6.txt)

**Comment by laeubi** [comment]
Seems you have a (hardly resolvable) state that produces an endless loop and the Felix resolver increases the Heap until an OutOfMemmory occurs, or the GarbageCollector overhead is reached. You should try to get a heapdump and see what object occupy the space here.

**Comment by wimjongman** [comment]
The failing project is here: 

https://github.com/eclipse/birt/tree/How_to_import_BIRT_code_into_eclipse_%23628

https://github.com/eclipse/birt/commit/f5a0fcf3a09a4813530d654019a5b409cd8ab528

**Comment by wimjongman** [comment]
The issue is caused by the following snippet in the pom of the project. If I remove that part of the pom, the build continues.


```
<build>
	<plugins>
		<plugin>
			<groupId>org.eclipse.tycho</groupId>
			<artifactId>target-platform-configuration</artifactId>
			<version>${tycho.version}</version>
			<configuration>
				<dependency-resolution>
					<extraRequirements>
						<requirement>
							<type>eclipse-feature</type>
							<id>org.eclipse.birt.osgi.runtime</id>
							<versionRange>0.0.0</versionRange>
						</requirement>
					</extraRequirements>
				</dependency-resolution>
			</configuration>
		</plugin>
	</plugins>
</build>
```

**Comment by laeubi** [comment]
@wimjongman any chance to dereive a simple reproducer or even an [itest](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) from what you have discovered?

**Comment by wimjongman** [comment]
Sure. However, I am swamped getting BIRT to build at the moment. So not immediately.

**Comment by laeubi** [comment]
As I'm not a ware of anyone with the same problem I don't see a need to rush :-)

**Comment by laeubi** [comment]
I created https://github.com/eclipse/tycho/issues/213 as a follow up as the root cause of this problem.

**Comment by mickaelistria** [comment]
@wimjongman have you verified whether this is a regression compared to 2.2 or if issue is also present with 2.2? Would you have the opportunity to isolate the error/case a bit more; it's a too big codebase to be effective at trying to debug anything.

**Comment by wimjongman** [comment]
Thanks for looking at it. I am using a new target platform (including maven repos). Since there are many changed variables, I am not sure if it would also fail pre-2.2.

I don't have time to try and isolate the problem. I'm not sure why it fails and it would take me a long time.

However, if you want I can rebuild https://github.com/eclipse/birt/commit/f5a0fcf3a09a4813530d654019a5b409cd8ab528 and see if it is resolved with the latest Tycho when it is released. Let me know.
