### ISSUE TITLE
Support JUnit @DisplayName

### ISSUE THREAD

**Issue by DariaMarkaryan** [eclipse/tycho#198]
Hi. I'm using JUnit for run tests and it turns out that the @DisplayName does not work with tycho-surefire. I don't really care if I can use this particular annotation, it is important for me to change the names of the suites and test cases. Is there any way to do this?

**Comment by mickaelistria** [comment]
I think it's a bug, @DisplayName is supposed to work.
Please provide a minimal example licensed under EPLv2, which we could try to include into Tycho test suite.

**Comment by FedorovaDarya** [comment]
I'm using tycho-surefire 2.3.0 and JUnit 5.7.2
Test class just for an example:
```
package <...>;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;

@DisplayName("Custom name")
public class MyTests {

    @Test
    @DisplayName("My test name")
    public void uglyTestName(){
        System.out.println("Do something");
    }
}

```
It generates report like that:
```
<?xml version="1.0" encoding="UTF-8"?>

-<testsuite failures="0" skipped="0" errors="0" tests="1" time="5.18" name="org.tests.MyTests" xsi:noNamespaceSchemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<properties/>
<testcase time="5.153" name="uglyTestName" classname="org.test.tests.MyTests"/>
</testsuite>
```

**Comment by FedorovaDarya** [comment]
And one additional question: is this possible to include logs into passed test cases?

**Comment by ernstblechaJKU** [comment]
The behaviour of the maven-surefire-plugin changed some time ago; as far as i remeber there is a difference between JUnit4 and JUnit5 when it comes to handling display-name;

The new version of the surefire-plugin requiers additional configuration (see https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html#Surefire_Extensions_and_Reports_Configuration_for_.40DisplayName ). So far i wasn't able to figure out how to set these options when using tycho-surefire?

**Comment by joeshannon** [comment]
I wonder if this would be possible using the providerProperties on the Tycho mojo?

However I've just seen that support for this was added to maven-surefire in version 3.0.0-M4 but Tycho currently uses 2.22.2 so that would probably have to be upgraded first I think.

**Comment by joeshannon** [comment]
Tycho 3.0.0-SNAPSHOT does now have a version of Surefire that supports this however passing the required configuration looks like it might be non-trivial.

The configuration for tycho-surefire (`TestPluginMojo`/`AbstractTestMojo`) is written into a `PropertiesWrapper` and stored in a file which is then passed into the new Surefire OSGi booter process via an argument. The properties are a `Map<String, String>` at this point.

In Maven Surefire the required `SurefireStatelessReporter`, `SurefireConsoleOutputReporter` and `SurefireStatelessTestsetInfoReporter` objects are typed parameters on the Mojo. In Tycho these objects are created in the  booter process - `OsgiSurefireBooter`, currently hardcoded to default implementations. 

We would need a way to recreate these objects in the booter but the `Map<String, String>` of properties does not seem sufficient to allow this unless the raw xml was passed in and then deserialized in the booter process.

One option could be to add a tycho-surefire parameter such as `enableJUnit5Reporting` that, if enabled, `OsgiSurefireBooter` can configure itself using the default settings for JUnit5 [as documented by Surefire](https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html#surefire-extensions-and-reports-configuration-for-displayname) but this doesn't feel like an ideal solution as it does not allow full flexibility.

Does this make sense?
Any thoughts on how we might achieve this?

**Comment by laeubi** [comment]
> Does this make sense?
> Any thoughts on how we might achieve this?

Your best option would be to fetch the code and try out some of your suggestions, if your happy with them open a PR so we can discuss it.

**Comment by joeshannon** [comment]
Have created a draft PR based on my previous comment.
