### ISSUE TITLE
Tycho and m2e connector

### ISSUE THREAD

**Issue by cdietrich** [eclipse/tycho#200]
with the recent changes in tycho 2.4 we see new issues with the lifecycle mappings
https://github.com/eclipse/xtext-core/commit/fcb6da383afa98aff5fb5a817cfb9404e9b31e7a

unfortunately the alternative approach with the tycho m2e connector does not seem to work.
the version on https://repo1.maven.org/maven2/.m2e/connectors/m2eclipse-tycho/0.9.0/N/LATEST/
seem to be too old for the new connector.

what is the state of the connector? is it no longer maintained?
is there an alternative solution?

**Comment by mickaelistria** [comment]
AFAIK, the m2eclipse-tycho connector is not maintained any more; and there is about no real hope it becomes maintained again. The same is true for about all m2e connectors that said.
So the recommended approach is to make Maven plugins compatible with incremental builds as described in https://www.eclipse.org/m2e/documentation/m2e-making-maven-plugins-compat.html ; for Tycho #146 is where this (not yet started) effort can be tracked.
