### ISSUE TITLE
Artifact not found -  Access forbidden

### ISSUE THREAD

**Issue by lavaude** [eclipse/tycho#209]
Hi there,

Since this morning all of our builds are failing when trying to fetch from eclipse server.

[ERROR] Failed to resolve target definition 
Failed to load p2 metadata repository from location https://download.eclipse.org/releases/2021-03/: Unable to read repository at https://download.eclipse.org/releases/2021-03. Artifact not found: https://download.eclipse.org/technology/epp/packages/2021-03/compositeContent.xml. -> [Help 1]

When trying to browse that page I get an "Access forbidden". 

Is that normal?

Best,

Edouard

**Comment by laeubi** [comment]
There are [heavy outages](https://www.eclipsestatus.io/) on eclipse infra that influences a lot of services. Please retry once the status is back to green if the problem persists.

**Comment by mickaelistria** [comment]
Eclipse infra issue should be resolved now; and in any case, Tycho cannot really act on that topic, so let's close.
