### ISSUE TITLE
Maven build hangs when resolving class path

### ISSUE THREAD

**Issue by katebambuk** [eclipse/tycho#212]
Hello
I have a problem with maven build hangs when resolving class path.

If I try to build attached [hanging_project.zip](https://github.com/eclipse/tycho/files/6922395/hanging_project.zip)  with Tycho 2.2.0, mvn clean verify takes 51.219 s
After upgrade Tycho to 2.3.0 or 2.4.0, mvn clean verify takes 06:10 min. 
It spends a lot of time on
[INFO] Resolving class path of MavenProject: com.sample.hanging.bundles:com.sample.hanging.bundle:1.0.0-SNAPSHOT @ D:\projects\hanging\bundles\com.sample.hanging.bundle\pom.xml
[DEBUG] Using TargetEnvironment (& (osgi.os=win32) (osgi.ws=win32) (osgi.arch=x86_64) ) to create resolver properties

Environment:
Apache Maven 3.8.1
Maven home: D:\ext_soft\apache-maven-3.8.1\bin\..
Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

This hang started after adding the com.sun.xml.bind.jaxb-impl dependency. I have another project with com.sun.xml.bind.jaxb-impl dependency and it works fine, so probably the reason of hanging is the combination of dependencies. But since it works fine with tycho 2.2.0, I'm reporting a bug. 
Please check this case.

Thanks!
Ekaterina

**Comment by laeubi** [comment]
Maybe related to 

- https://github.com/eclipse/tycho/issues/197

**Comment by laeubi** [comment]
@katebambuk thanks for your sample project.

> Please check this case.

Just to be sure: Is tycho really hanging (e.g. never terminates) or is it just very slow (e.g. terminates after one hour, day, ...)?

**Comment by laeubi** [comment]
Okay, I have missed your comment about build times... I have build the project locally and for me actually the fetching from the update sites was *very* slow, but I think this is then more related to the new resolver used in tycho 2.3 so I think

- https://github.com/eclipse/tycho/pull/173

is related instead.

**Comment by laeubi** [comment]
I created https://github.com/eclipse/tycho/issues/213 as a follow-up describing the root-cause of this problem.
