### ISSUE TITLE
Allow Tycho surefire debug settings to be customised

### ISSUE THREAD

**Issue by joeshannon** [eclipse/tycho#216]
The surefire test allows a [debugPort](https://www.eclipse.org/tycho/sitedocs/tycho-surefire-plugin/test-mojo.html#debugPort) to be set only. This results in the following to be added to the Java arguements: `cli.addVMArguments("-Xdebug", "-Xrunjdwp:transport=dt_socket,address=" + debugPort + ",server=y,suspend=y");`

The maven surefire plugin allows this to be customised with the [maven.surefire.debug](https://maven.apache.org/surefire/maven-surefire-plugin/examples/debugging.html) property. It would be useful if Tycho supported something like this too.

For context, my use case is that I want to allow a different host to connect to the process. This used to work but as of Java 11 only localhost connections are permitted by default (see e.g. [this issue](https://github.com/OpenLiberty/open-liberty/issues/7833)).

**Comment by laeubi** [comment]
@joeshannon this sounds reasonable can you provide a PR for this?

**Comment by joeshannon** [comment]
Yes I am happy to take a look. I think the parameter names might require some thought/agreement. 

What do you think would be a good parameter name? `tycho.surefire.debug` to correspond with Maven surefire or something different e.g. `debugArgs`?

For the exiting `debugPort`, we would need to decide whether to keep this as an alternative or perhaps deprecate it as would be configurable via the new debug args.

There is also the existing `debugOptions` but this relates to Equinox/OSGi debug options.

**Comment by laeubi** [comment]
I think `tycho.surefire.debug` is fine. I would recommend to have some kind of fallback approach: if `tycho.surefire.debug` is not specified, use the `debugPort` as before.

**Comment by laeubi** [comment]
Adding a hint to debugPort seems to suffice then! AFAIK you simply need to adjust the javadoc and it will appear in the site-doc of the next release.

**Comment by mickaelistria** [comment]
Is patch #219 enough to cover this story?

**Comment by joeshannon** [comment]
Yes I think so, thanks for reviewing/merging!
