### ISSUE TITLE
additional.bundles dependencies are not properly resolved

### ISSUE THREAD

**Issue by cdietrich** [eclipse/tycho#23]
additional.bundles dependencies are not properly resolved

this issue is initially reported here: https://www.eclipse.org/lists/tycho-user/msg09020.html
besides the xtext-eclipse and xtext-xtend tests builds with tycho 2.4.0-SNAPSHOT
i can also see the problem with
https://github.com/cdietrich/tych24ddBundlesBug

```
[ERROR] Internal error: java.lang.RuntimeException: org.osgi.framework.BundleException: Bundle org.xtext.example.mydsl.ide cannot be resolved:org.xtext.example.mydsl.ide [109]
[ERROR]   Unresolved requirement: Require-Bundle: org.xtext.example.mydsl
[ERROR]     -> Bundle-SymbolicName: org.xtext.example.mydsl; bundle-version="1.0.0.qualifier"; singleton:="true"
[ERROR]        org.xtext.example.mydsl [108]
[ERROR]          Unresolved requirement: Require-Bundle: org.eclipse.xtext.xtext.generator
[ERROR] -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: org.osgi.framework.BundleException: Bundle org.xtext.example.mydsl.ide cannot be resolved:org.xtext.example.mydsl.ide [109]
  Unresolved requirement: Require-Bundle: org.xtext.example.mydsl
    -> Bundle-SymbolicName: org.xtext.example.mydsl; bundle-version="1.0.0.qualifier"; singleton:="true"
       org.xtext.example.mydsl [108]
         Unresolved requirement: Require-Bundle: org.eclipse.xtext.xtext.generator
```

org.eclipse.xtext.xtext.generator is part of xtext.sdk here in the tp https://github.com/cdietrich/tych24ddBundlesBug/blob/7e0dbd51eed5802857b45b4db499041457c4eb5c/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target#L18

interestingly i can also find this in the log
```
[INFO] Fetching org.eclipse.xtext.xbase_2.25.0.v20210301-0909.jar from https://ftp.snt.utwente.nl/pub/software/eclipse/releases/2021-03/202103171000/plugins/ (2,46MB)
[INFO] Fetching org.eclipse.xtext.xtext.generator_2.25.0.v20210301-0843.jar from https://ftp.snt.utwente.nl/pub/software/eclipse/releases/2021-03/202103171000/plugins/ (969,17kB)
[INFO] Fetching org.eclipse.equinox.launcher.win32.win32.x86_64_1.2.100.v20210209-1541.jar.pack.gz from https://mirror.dkm.cz/eclipse/releases/2021-03/202103171000/plugins/ (81,75kB)
```

also the problem is on the ide project, whilst die add. bundles are on the mydsl project

```
[INFO] Computing target platform for MavenProject: org.xtext.example.mydsl:org.xtext.example.mydsl:1.0.0-SNAPSHOT @ /Users/cdietrich/eclipse-workspaces/es2103/org.xtext.example.mydsl.parent/org.xtext.example.mydsl/pom.xml
[INFO] Resolving dependencies of MavenProject: org.xtext.example.mydsl:org.xtext.example.mydsl:1.0.0-SNAPSHOT @ /Users/cdietrich/eclipse-workspaces/es2103/org.xtext.example.mydsl.parent/org.xtext.example.mydsl/pom.xml
[INFO] Resolving class path of MavenProject: org.xtext.example.mydsl:org.xtext.example.mydsl:1.0.0-SNAPSHOT @ /Users/cdietrich/eclipse-workspaces/es2103/org.xtext.example.mydsl.parent/org.xtext.example.mydsl/pom.xml
[INFO] Fetching 202103171000&countryCode=de&timeZone=1&format=xml from http://www.eclipse.org/downloads/download.php?format=xml&file=/releases/2021-03/

.... tons of more fetches
[INFO] Computing target platform for MavenProject: org.xtext.example.mydsl:org.xtext.example.mydsl.ide:1.0.0-SNAPSHOT @ /Users/cdietrich/eclipse-workspaces/es2103/org.xtext.example.mydsl.parent/org.xtext.example.mydsl.ide/pom.xml
[INFO] Resolving dependencies of MavenProject: org.xtext.example.mydsl:org.xtext.example.mydsl.ide:1.0.0-SNAPSHOT @ /Users/cdietrich/eclipse-workspaces/es2103/org.xtext.example.mydsl.parent/org.xtext.example.mydsl.ide/pom.xml
[INFO] Resolving class path of MavenProject: org.xtext.example.mydsl:org.xtext.example.mydsl.ide:1.0.0-SNAPSHOT @ /Users/cdietrich/eclipse-workspaces/es2103/org.xtext.example.mydsl.parent/org.xtext.example.mydsl.ide/pom.xml
```

**Comment by laeubi** [comment]
Thanks for the example, I'll try to take a look at this. Can you verify that removing the additional bundle from the build.properties makes the build succeed?

**Comment by cdietrich** [comment]
> Can you verify that removing the additional bundle from the build.properties makes the build succeed?

yes this works

so it looks like tycho now seeks from upstream add. bundles to be present in downstream plugins, whilst in p2 they are not, they are available in the plugin specifiying the add.  bundles only.

**Comment by laeubi** [comment]
> so it looks like tycho now seeks for upstream add. bundles to be present in downstream plugins, whilst in p2 they are not, they are available in the plugin specifiying the add. bundles only.

Can you elaborate a bit more here? I must confess I'm not completely sure what you suspect to be the problem here.

**Comment by cdietrich** [comment]
pde:
mydsl has add. bundles  org.eclipse.xtext.xtext.generator so i can use stuff from it like XtextGenerator class.
in myldsl.ide which has a dependency to mydsl i cannot use stuff from org.eclipse.xtext.xtext.generator
but why does tycho need it then

**Comment by laeubi** [comment]
Tycho resolves the complete chain of transitive dependencies.

**Comment by cdietrich** [comment]
then the question would be: why can mydsl find org.eclipse.xtext.xtext.generator if it is resolved itself,
but cannot find it if it is resovled as dependency of mydsl.ide

**Comment by laeubi** [comment]
I don't know yet :-)

Possible reasons include:

- Target platform is different for both projects
- A bug in Tycho
- A bug in P2
- Something is restricting the scope (e.g. platform filters)
- ...

**Comment by laeubi** [comment]
I have checked out your example. The build complains about

"org.xtext.example.mydsl" is missing it is not part of the target nor part of the reactor build.

**Comment by cdietrich** [comment]
but why 

https://github.com/cdietrich/tych24ddBundlesBug/blob/7e0dbd51eed5802857b45b4db499041457c4eb5c/pom.xml#L25

and why could it be resolved 50 lines before

```
[INFO] Computing target platform for MavenProject: org.xtext.example.mydsl:org.xtext.example.mydsl:1.0.0-SNAPSHOT @ /Users/cdietrich/eclipse-workspaces/es2103/org.xtext.example.mydsl.parent/org.xtext.example.mydsl/pom.xml
[INFO] Resolving dependencies of MavenProject: org.xtext.example.mydsl:org.xtext.example.mydsl:1.0.0-SNAPSHOT @ /Users/cdietrich/eclipse-workspaces/es2103/org.xtext.example.mydsl.parent/org.xtext.example.mydsl/pom.xml
[INFO] Resolving class path of MavenProject: org.xtext.example.mydsl:org.xtext.example.mydsl:1.0.0-SNAPSHOT @ /Users/cdietrich/eclipse-workspaces/es2103/org.xtext.example.mydsl.parent/org.xtext.example.mydsl/pom.xml
[INFO] Fetching 202103171000&countryCode=de&timeZone=1&format=xml from http://www.eclipse.org/downloads/download.php?format=xml&file=/releases/2021-03/
...
```

**Comment by laeubi** [comment]
Good question :-)

While implementing this feature I had the problem that the requirement was there but the claspathresolver has thrown it away, but here it seems missing in the first place. I need to further debug this.

**Comment by laeubi** [comment]
I think I found the issue, if the bundles uses requirebundle AND additional bundles then only the req. ones are used.

**Comment by laeubi** [comment]
@cdietrich can you try with a local build version of https://github.com/laeubi/tycho/tree/issue_23 if that fixes your issue?

**Comment by cdietrich** [comment]
@laeubi nice, my demo project seems to work, so do xtext-eclipse and xtext-xtend

**Comment by laeubi** [comment]
Thanks for verification!

**Comment by LorenzoBettini** [comment]
@laeubi I think this is worthwhile to be mentioned in the release notes

**Comment by cdietrich** [comment]
https://github.com/eclipse/tycho/pull/157#issuecomment-864504359

**Comment by laeubi** [comment]
@cdietrich :+1: @LorenzoBettini I did not think that this feature is of much interest to be noted in the release notes :-)

**Comment by LorenzoBettini** [comment]
@laeubi IMHO it definitely is :)
I mean it's something that it was meant to work but it didn't
