### ISSUE TITLE
Use HTTPS links

### ISSUE THREAD

**Issue by Marcono1234** [eclipse/tycho#247]
Hello,
this project uses multiple HTTP instead of HTTPS links in markdown files, Java documentation (and exception messages) and POM files.
It would be good to replace those with HTTPS since most target sites, to which the links refer, support it.

I am not going to sign the CLA or submit a pull request for this, so if you don't consider this a problem then feel free to close this issue.
However, in case you do consider this an issue, here is a regex pattern for finding such links (excluding some false positives):
```
http://(?!maven\.apache\.org/POM|www\.w3\.org/2001/XMLSchema-instance|maven\.apache\.org/maven-.+\.xsd|www\.eclipse\.org/legal/epl-v10\.html|www\.eclipse\.org/org/documents/edl-v10\.php|www\.w3\.org/TR/xhtml1/DTD/.+|www\.w3\.org/1999/xhtml|maven\.apache\.org/SETTINGS/.+|maven\.apache\.org/xsd/.+|(www\.)?example\.com/.*)
```

Additionally there are tools such as Spring's [nohttp](https://github.com/spring-io/nohttp) which can automate finding such links in the future (though I have not used it myself yet).

**Comment by mickaelistria** [comment]
Can you please submit a PR that fixes it?

**Comment by Marcono1234** [comment]
Will that require me to sign the CLA? If that is the case I won't submit a pull request.
Feel free to close this issue then.

**Comment by mickaelistria** [comment]
I'll leave the issue open as it's still valid.
But what's your reason to not sign the contributor agreement? Did you read it first?

**Comment by Marcono1234** [comment]
> But what's your reason to not sign the contributor agreement? Did you read it first?

I have caused some trouble for the Eclipse LSP4J maintainers due to the ECA already in the past (see https://github.com/eclipse/lsp4j/pull/419). So it is what it is. Please don't try to change the ECA process or the standards for contributing to this repository just for this. HTTPS links would be nice to have, but it is not worth the trouble.

**Comment by mickaelistria** [comment]
I reas you want to keep your activities separated, note that it is possible if you use different mail addresses. With gmail, you can use eg marconi+eclipse@gmail.com, sign ECA with this address, author patches to Eclipse projects, and get ECA approved with some isolation compared to your other addresses.
If you really want full anonymity, then it's not going to work for Eclipse projects at all: unlike some other contributor agreements, you keep your IP and are still responsible in case you copied code illegally or if you intentionally contribute malicious code. Responsibily and anonymity don't play well together.

**Comment by mschreiber** [comment]
@mickaelistria I created different pull requests for that to make the review easier ... I created another pull request (#867) right now, which contains also many https instead of http changes that are relevant... 
I guess with that pr all relevant changes are done, the remaining http things are just test stuff
