### ISSUE TITLE
Using an absolute path for the target platform file is not working 

### ISSUE THREAD

**Issue by jmini** [eclipse/tycho#263]
In recent version of tycho, it is possible to specify the path of the target platform file, directly in the configurations:

https://github.com/eclipse/tycho/blob/4a8d1c1c81e78049e70b9ef691b1408f967a3bf4/tycho-its/projects/target.usefile/pom.xml#L40-L49

The value expected in the `<file>` section seems to be a relative path.

If you change the linked example to be:
```xml
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>target-platform-configuration</artifactId>
				<version>${tycho-version}</version>
				<configuration>
					<target>
						<file>${project.basedir}/jetty.target</file>
					</target>
				</configuration>
			</plugin>
```

Which should point to the same file, you get following error:
```
$ mvn verify
[INFO] Scanning for projects...
[ERROR] Setting target failed: target definition file '/<path to>/org.eclipse.tycho/tycho-its/projects/target.usefile/jetty.target' not found in project 'Jetty p2 Update Site for Platform build neeeds'. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
```

In this simple example it doesn't matter that much, but in more complicated multi-module builds, it could be interesting to have the support of absolute path (and path using constructs like `../` in the value)

**Comment by laeubi** [comment]
Tycho uses `File target = new File(project.getBasedir(), file);` to construct the path (at least 2.4+) so these conversion rules apply here: https://docs.oracle.com/javase/7/docs/api/java/io/File.html#File(java.io.File,%20java.lang.String)

**Comment by jmini** [comment]
I tried it with `2.4.0` and it works as you have described:

`new File(project.getBasedir(), file);`

```
[ERROR] Setting target failed: target definition file '/<path to>/org.eclipse.tycho/tycho-its/projects/target.usefile/<path to>/org.eclipse.tycho/tycho-its/projects/target.usefile/jetty.target' not found for project 'Jetty p2 Update Site for Platform build neeeds'. -> [Help 1]
```

Which is also wrong in my personal opinion, because you will never be able to pass an absolute path in the `<file>` tag.

---

For me the correct implementation should be using the nio API:

```
// import java.nio.file.Paths;

Paths.get(project.getBasedir()).resolve(file)
```

I did not add the `.toPath()` and `.toFile()` calls (to switch between `java.io` and `java.nio` constructs) to improve readability.

---

If `<file>` is something relative `jetty.target` then you will get `/path/to/projectBaseDir/jetty.target` (as now)
If `<file>` is something absolute `/my/target/location/file.target` then you will get `/my/target/location/file.target`

---

As I wrote in the issue there is no chance to provide an absolute path with the current implementation.

**Comment by laeubi** [comment]
This feature is relative new and not widely used, so there is a great chance that there is room for improvements. If you like you can provide a PR with your idea regarding the usage of path + an integration test that shows the usage of this.

I just wanted to point out (and that's why it works how it works today) that there is no such thing like 'build-root' / 'pom-file location' or similar absolute path in maven as far as I know, so using `${project.basedir}` in your example will not work as you might expect it to work (it will always point to the path of the current module not the path of the pom where it is declared).

**Comment by jmini** [comment]
Yes. 
My example is from a single-module project that I found in the examples (to not have to bring my own reproducer).

A real usage of this feature "Support absolute path in for the target file location" is useful if you provide a real absolute path (that can be parameterized or not -- Examples:`${targetDefs}/version1.target` where `targetDefs` do not depends from the current project or`/my/target/location/file.target` directly).

**Comment by laeubi** [comment]
Thanks for the fix!
