### ISSUE TITLE
org.eclipse.tycho.plugins.tar.TarGzArchiverTest currently fails on jenkins ci

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#292]
@akurtakov @mickaelistria any idea? Is this an OS issue we need to report to ci-infra?

**Comment by laeubi** [comment]
Example build: https://ci.eclipse.org/tycho/job/tycho-github/job/master/86/#showFailuresLink the GH action build is fine https://github.com/eclipse/tycho/actions/runs/1253280194

**Comment by mickaelistria** [comment]
This userId comes from the pod/agent IIRC, so maybe more something to check with infra folks.

**Comment by laeubi** [comment]
Reported here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=575285#c17

**Comment by cdietrich** [comment]
maybe you need to replace 
`tarStream.setLongFileMode(TarArchiveOutputStream.LONGFILE_GNU);`
with something else. (`LONGFILE_POSIX`)

**Comment by laeubi** [comment]
While this is certainly possible I'm not sure if it hinders compatibility with older(?) linux/unix/... as this could affect the eclipse-downloads and all its users I don't really like to change behavior without a good reason...

**Comment by merks** [comment]
@jonahgraham 

FYI, I think this change might be related to the warnings when extracting *.tar.gz files...

**Comment by laeubi** [comment]
> @jonahgraham
> 
> FYI, I think this change might be related to the warnings when extracting *.tar.gz files...

What warning? This issue is > 1 year old targeting a no longer supported Tycho stream, so if you see any issues / improvements it might be better to open a dedicated issue...

**Comment by merks** [comment]
I thought maybe it's related to this:

https://github.com/eclipse-platform/eclipse.platform.releng/issues/147

But I don't know that for a fact.  I just thought about it because I used org.apache.commons.compress.archivers.tar.TarArchiveOutputStream in a customer project and ran into the issue of the result not being GNU compatible.  If it's not related, then sorry for the noise!
