### ISSUE TITLE
Release tycho-2.5.x

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#293]
# Releasing Tycho

This describes the steps to perform a release of Tycho:

- [x] Make sure all fixed issues and merged PRs have the correct milestone for this release
- [x] Prepare the [release notes](https://github.com/eclipse/tycho/blob/master/RELEASE_NOTES.md) which should provide a quick overview of new features and bug fixes 
- [x] Create release record on https://projects.eclipse.org/projects/technology.tycho projects.eclipse.org , link the N&N to https://github.com/eclipse/tycho/blob/master/RELEASE_NOTES.md release notes]
- [x] Create branch `tycho-N.M.x` (eg `tycho-2.4.x`) for upcoming release and push it to remote; this branch should remain frozen until the release, only major fixes for regressions could be merged in before release. Work can still happen regularly on the `master` branch.
- [x] Update versions on `master `to future release with `mvn org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=<NEXT_VERSION>-SNAPSHOT` and push to remote 
- [x] Announce the intent to release and request feedback about snapshots on tycho-user@eclipse.org:
```
Subject: Please test snapshots for upcoming <VERSION> release

We plan to release Tycho <VERSION> next week. For details of new features and bugfixes, see release notes [1].
Please help by testing the SNAPSHOTS build. To use it, change your tycho version to <VERSION>-SNAPSHOT and add snippet [2] to your pom.

We plan to promote this release in one week unless major regressions are found.

Regards,
Tycho team

[1] https://github.com/eclipse/wildwebdeveloper/blob/master/RELEASE_NOTES.md
[2]
<pluginRepositories>
    <pluginRepository>
      <id>tycho-snapshots</id>
      <url>https://repo.eclipse.org/content/repositories/tycho-snapshots/</url>
    </pluginRepository>
</pluginRepositories>
```

... Wait until review date (usually a week later)...

- [x] Make sure you have everything setup (GPG installed!) for deploying to the Nexus OSS repository, see https://central.sonatype.org/pages/ossrh-guide.html guide
- [x] Add your credentials for server `sonatype-nexus-staging` in `~/.m2/settings.xml`
```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
   <!-- ... -->
   <servers>
    <server>
      <id>sonatype-nexus-staging</id>
      <username>mickael.istria</username>
      <password>securePassword</password> <!-- use `mvn --encrypt-password` to not store plain text -->
    </server>
    <!-- ... -->
   </servers>
</settings>
</source>
```

- [x] Checkout branch `tycho-N.M.x`
- [x] Update version to remove `-SNAPSHOT` with `mvn org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=<VERSION>`
- [x] Update versions in tycho-demo folder
- [x] Sync to release commit and deploy to nexus staging repository: `mvn clean deploy -Prelease -DforgeReleaseId=sonatype-nexus-staging -DforgeReleaseUrl=https://oss.sonatype.org/service/local/staging/deploy/maven2/`
- [x] On https://oss.sonatype.org/#stagingRepositories , Close the staging repository, get the staging repo URL from Nexus
- [x] Wait for artifacts to be available on Maven central.
- `git tag <TYCHO_VERSION>`
- push tag to remote
- Documentation
  - [x] Generate site docs using `mvn install site site:stage -DskipTests` and check the result from `target/staging` seems viable.
  - [x] Prepare documentation on the webite, using git repo https://git.eclipse.org/c/www.eclipse.org/tycho.git/ : copy the local site docs folders `target/staging/sitedocs` to the existing `sitedocs` folder and then submit as Gerrit review (don't merge yet)
- Announce the release
   - [x] Find out who contributed to the release:
```
git log --pretty=format:%an tycho-<previousVersion>..tycho-<newVersion> | sort | uniq
git log --grep="Also-[bB]y:" tycho-<previousVersion>..tycho-<newVersion> | grep -i also-by | sed -e 's/.*Also-[bB]y:\s*\(.*\)/\1/' | sort | uniq
```
  - [ ] Announce the release on [GitHub discussions](https://github.com/eclipse/tycho/discussions) and tycho-dev@eclipse.org, thanking the contributors:
```
Subject: Tycho <VERSION> is released

Tycho <VERSION> has been released and is available from Maven Central repository.

🆕 https://github.com/eclipse/tycho/blob/master/RELEASE_NOTES.md#xyz
🏷️ https://github.com/eclipse/tycho/tree/tycho-x.y.z
👔 https://projects.eclipse.org/projects/technology.tycho/releases/x.y.z
🙏 contributors who contributed patches for this release:
<contributors>
and thanks and to everyone who helped us with testing the staged version.

Regards,

```
   - [ ] Optionally, announce on other medias (Twitter)
- [ ] Create, push and merge patch changing the bootstrap Tycho version for Tycho build (eg https://git.eclipse.org/r/c/tycho/org.eclipse.tycho/+/174964 )

**Comment by laeubi** [comment]
@mickaelistria I think we maybe should exchange the `Create release record` step with the `Create branch` step so it is possible to link to https://github.com/eclipse/tycho/blob/...branch name.../RELEASE_NOTES.md what do you think?

**Comment by laeubi** [comment]
@mickaelistria in step `Announce the intent to release` should we probably also add an item to the github discussions as well?

**Comment by mickaelistria** [comment]
Yes to both

-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/eclipseide> developer, for Red Hat
Developers <https://developers.redhat.com/>

**Comment by laeubi** [comment]
@akurtakov it seems your are[ the only one allowed creating an announcement](https://github.blog/changelog/2021-05-18-github-discussions-labels-and-announcements-category-format/) currently can you please add one at the discussions page in the [announcement category](https://github.com/eclipse/tycho/discussions/categories/announcements):

We plan to release Tycho 2.5.0 next week. For details of new features and bugfixes, see [release notes](https://github.com/eclipse/tycho/blob/tycho-2.5.x/RELEASE_NOTES.md).
Please help by testing the SNAPSHOTS build. To use it, change your tycho version to 2.5.0-SNAPSHOT and add the following snippet to your pom.

```
<pluginRepositories>
    <pluginRepository>
      <id>tycho-snapshots</id>
      <url>https://repo.eclipse.org/content/repositories/tycho-snapshots/</url>
    </pluginRepository>
</pluginRepositories>
```

We plan to promote this release in one week unless major regressions are found.

Regards,
Tycho team

**Comment by laeubi** [comment]
@mickaelistria is the mailinglist already shut down?
```

 tycho-user@eclipse.org
    host mail.eclipse.org [198.41.30.200]
    SMTP error from remote mail server after RCPT TO:<tycho-user@eclipse.org>:
    550 5.1.1 <tycho-user@eclipse.org>: Recipient address rejected:
    User unknown in local recipient table
```

**Comment by laeubi** [comment]
Currently the release is blocked I raised https://bugs.eclipse.org/bugs/show_bug.cgi?id=576132 
@mickaelistria if I remember right from the last discussions, CI is not considered "first class infra" if not requested from a "strategic member company" do you see any chance to give some more priority on this? If I understand the issue correct it is simply the userid that is configured wrong and a way too large given common os configurations and I can't even consider a case where one really needs 1'003'220'000 users on a system so I don't get the rationale behind choosing such a large user-id ...

**Comment by akurtakov** [comment]
Done https://github.com/eclipse/tycho/discussions/295

**Comment by laeubi** [comment]
> Done #295

Thanks, strange enough I can edit / pin / unpin your discussion but not create one :1st_place_medal:

**Comment by akurtakov** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=576132 doesn't exist

**Comment by laeubi** [comment]
> https://bugs.eclipse.org/bugs/show_bug.cgi?id=576132 doesn't exist

Can you check that you are logged in (I rember there where some issues in the past) because the link works for me as expected (I have added you CC).

**Comment by laeubi** [comment]
Given there won't be any more server problem could we release next week on Wednesday? Jetty likes to release on Oct 1 and it would be good to have an official release until then available. @mickaelistria can you take over the missing release steps then? I will only be partly available next week...
