### ISSUE TITLE
Java 17 Support

### ISSUE THREAD

**Issue by Dmor01** [eclipse/tycho#302]
Hello, I see tycho `2.5.0` will be released soon and saw it supports up till Java 16
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project ____: Fatal error compiling: target level should be in '1.1'...'1.8','9'...'16' (or '5.0'..'16.0') or cldc1.1: 17 -> [Help 1]
```
In which release is Java 17 expected to be supported?

Thanks

**Comment by laeubi** [comment]
Most likely it will be supported with the release of 2021-12 release.

**Comment by cdietrich** [comment]
see also https://www.eclipse.org/lists/jdt-dev/msg01924.html

**Comment by akurtakov** [comment]
Btw, your error is coming from maven-compiler-plugin not tycho-compiler-plugin so you might need to find when it will support Java 17 too.

**Comment by LorenzoBettini** [comment]
@akurtakov couldn't we keep this issue open till Java 17 is actually supported?

**Comment by vogella** [comment]
Trying to compile Tycho master with a Java 17 runtime results in the  following unit test error:

INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   EquinoxResolverTest.testBREEJavaSE11:71 expected:<JavaSE-1[1]> but was:<JavaSE-1[7]>
[INFO] 
[ERROR] Tests run: 161, Failures: 1, Errors: 0, Skipped: 0
[INFO] 

[INFO] Tycho Core ......................................... FAILURE [ 13.672 s]

**Comment by mickaelistria** [comment]
Support for Java 18 was added, so I guess Java 17 becomes both unnecessary and supported as part of Java 18. Let's close.

**Comment by LorenzoBettini** [comment]
@mickaelistria it was added in the next 2.6.0 release, wasn't it? If that's the case, I think the RELEASE notes should be updated accordingly.

**Comment by Dmor01** [comment]
I tested my project with `tycho-compiler-jdt` v`2.6.0-SNAPSHOT` and still see the same error message indicating only up to Java 16 is supported. Similar to https://github.com/eclipse/tycho/issues/136

**Comment by akurtakov** [comment]
There is no ECJ release that supports Java 17. Until this happens and Tycho updates to use that version tycho-compiler-jdt won't be able to compile Java 17 code.

**Comment by Dmor01** [comment]
Thanks for the clarification @akurtakov, based on https://github.com/eclipse/tycho/issues/302#issuecomment-925516839 I expect that to be released in December.

**Comment by Bananeweizen** [comment]
@akurtakov I thought the 2.5.0 snapshot already supported Java 17 since https://github.com/eclipse/tycho/commit/2a17ad75239258534578033169e968434d348c48. Is that wrong?

**Comment by akurtakov** [comment]
Wrong. This ecj version can't generate Java 17 bytecode.

**Comment by ppogorzelski** [comment]
Are 2.6 snapshots available for Maven usage?

**Comment by akurtakov** [comment]
Sure, describe at https://github.com/eclipse/tycho/blob/master/CONTRIBUTING.md#try-snapshots-and-report-issues . But this one still doesn't contain ecj supporting Java 17. That should happen in couple of weeks.

**Comment by RoiArthurB** [comment]
Hi all, 

Eclipse 2021-12 has been released this December 8th (according to [their project plan](https://www.eclipse.org/projects/project-plan.php?planurl=https://www.eclipse.org/eclipse/development/plans/eclipse_project_plan_4_22.xml#release_milestones)) which have support for JDK 17. In general, it's coming with a new Tycho version, but I can't find any official 2.6.0 nor date, information, nor anything. 

Anyone knows for when Tycho 2.6.0 (with JDK 17 support) will officially be released?

**Comment by laeubi** [comment]
> In general, it's coming with a new Tycho version

I don't think this is 'generally true', tycho often releases a new version some weeks after the Eclipse Release as the new items have to be in cooperated and tested first. 
If you like you can [check the latest snapshot of tycho](https://github.com/eclipse/tycho/wiki#getting-tycho-snapshots) if it already contains the necessary updates and help finding potential problems and regressions..

**Comment by RoiArthurB** [comment]
> If you like you can check the latest snapshot of tycho if it already contains the necessary updates and help finding potential problems and regressions.

Already working with the snapshot, but I'm waiting for the official release to update the development pipeline (without adding repos and stuff). But I can't find any date nor stuff even after almost a week, so I'm asking here :)

**Comment by laeubi** [comment]
> But I can't find any date nor stuff even after almost a week,

Mostly because there is no such plan :-)

If there is enough demand and the tycho team is fine with it we can start the release process at any time, I have no concerns so far only some version bumps are open and we already have some valuable enhancements in the release notes so maybe @mickaelistria  or @akurtakov could decide and start the release right now.

**Comment by akurtakov** [comment]
Tycho releases are usually done 2-3 weeks after Eclipse as visible on https://projects.eclipse.org/projects/technology.tycho/ . But even that is not a rule as we do other releases when we see fit. Right now both Mickael and me are busy with either other stuff or not working so expect new release in the new year but the date will be set next year.

**Comment by akurtakov** [comment]
If another committer is willing to drive 2.6.0 release earlier that would be more than welcome!

**Comment by Dmor01** [comment]
Closing since 2.6.0 with Java 17 support was released today per https://github.com/eclipse/tycho/discussions/497#discussioncomment-2013370.
