### ISSUE TITLE
Tycho fails to resolve dependency on NL fragments from babel

### ISSUE THREAD

**Issue by opcoach** [eclipse/tycho#320]
This bug is the continuation of the eclipse bug : [https://bugs.eclipse.org/bugs/show_bug.cgi?id=399966](https://bugs.eclipse.org/bugs/show_bug.cgi?id=399966)

I am using Tycho 2.5.0, and add the NL babel fragment (photon release for the moment)  in my target platform : 

location "https://archive.eclipse.org/technology/babel/update-site/R0.17.0/photon/" {
	org.eclipse.babel.nls_eclipse_de.feature.group
	org.eclipse.babel.nls_eclipse_es.feature.group
	org.eclipse.babel.nls_eclipse_fr.feature.group
	org.eclipse.babel.nls_eclipse_it.feature.group
	org.eclipse.babel.nls_eclipse_nl.feature.group
	org.eclipse.babel.nls_eclipse_pt.feature.group
	org.eclipse.babel.nls_eclipse_tr.feature.group
	org.eclipse.babel.nls_eclipse_zh.feature.group
}

and ... **The build fails :**   (see trace below)

If I remove the NL fragments from my feature and my products, the build success...   It seems to fail for all the languages... 

[ERROR] All attempts to read artifact osgi.bundle,org.eclipse.core.commands.nl_de,4.8.0.v20190713101254 failed:
[ERROR]    An error occurred while transferring artifact canonical: osgi.bundle,org.eclipse.core.commands.nl_de,4.8.0.v20190713101254 from repository https://archive.eclipse.org/technology/babel/update-site/R0.17.0/photon:
[ERROR]       Retry another mirror:
[ERROR]          Error while reading from repository: /technology/babel/update-site/R0.17.0/photon/plugins/org.eclipse.core.commands.nl_de_4.8.0.v20190713101254.jar.
[ERROR]    An error occurred while transferring artifact canonical: osgi.bundle,org.eclipse.core.commands.nl_de,4.8.0.v20190713101254 from repository https://archive.eclipse.org/technology/babel/update-site/R0.17.0/photon:
[ERROR]       Retry another mirror:
[ERROR]          Error while reading from repository: /technology/babel/update-site/R0.17.0/photon/plugins/org.eclipse.core.commands.nl_de_4.8.0.v20190713101254.jar.
[ERROR]    An error occurred while transferring artifact canonical: osgi.bundle,org.eclipse.core.commands.nl_de,4.8.0.v20190713101254 from repository https://archive.eclipse.org/technology/babel/update-site/R0.17.0/photon:
[ERROR]       Retry another mirror:
[ERROR]          Error while reading from repository: /technology/babel/update-site/R0.17.0/photon/plugins/org.eclipse.core.commands.nl_de_4.8.0.v20190713101254.jar.
[ERROR]    An error occurred while transferring artifact canonical: osgi.bundle,org.eclipse.core.commands.nl_de,4.8.0.v20190713101254 from repository https://archive.eclipse.org/technology/babel/update-site/R0.17.0/photon:
[ERROR]       Retry another mirror:
[ERROR]          Error while reading from repository: /technology/babel/update-site/R0.17.0/photon/plugins/org.eclipse.core.commands.nl_de_4.8.0.v20190713101254.jar.
[ERROR]    An error occurred while transferring artifact canonical: osgi.bundle,org.eclipse.core.commands.nl_de,4.8.0.v20190713101254 from repository https://archive.eclipse.org/technology/babel/update-site/R0.17.0/photon:
[ERROR]       Retry another mirror:
[ERROR]          Error while reading from repository: /technology/babel/update-site/R0.17.0/photon/plugins/org.eclipse.core.commands.nl_de_4.8.0.v20190713101254.jar.
[ERROR]    An error occurred while transferring artifact canonical: osgi.bundle,org.eclipse.core.commands.nl_de,4.8.0.v20190713101254 from repository https://archive.eclipse.org/technology/babel/update-site/R0.17.0/photon:
[ERROR]       Retry another mirror:
[ERROR]          Error while reading from repository: /technology/babel/update-site/R0.17.0/photon/plugins/org.eclipse.core.commands.nl_de_4.8.0.v20190713101254.jar.
[ERROR]    An error occurred while transferring artifact canonical: osgi.bundle,org.eclipse.core.commands.nl_de,4.8.0.v20190713101254 from repository https://archive.eclipse.org/technology/babel/update-site/R0.17.0/photon:
[ERROR]       Retry another mirror:
[ERROR]          Error while reading from repository: /technology/babel/update-site/R0.17.0/photon/plugins/org.eclipse.core.commands.nl_de_4.8.0.v20190713101254.jar.
[ERROR]    An error occurred while transferring artifact canonical: osgi.bundle,org.eclipse.core.commands.nl_de,4.8.0.v20190713101254 from repository https://archive.eclipse.org/technology/babel/update-site/R0.17.0/photon:
[ERROR]       Retry another mirror:
[ERROR]          Error while reading from repository: /technology/babel/update-site/R0.17.0/photon/plugins/org.eclipse.core.commands.nl_de_4.8.0.v20190713101254.jar.
[ERROR]    An error occurred while transferring artifact canonical: osgi.bundle,org.eclipse.core.commands.nl_de,4.8.0.v20190713101254 from repository https://archive.eclipse.org/technology/babel/update-site/R0.17.0/photon:
[ERROR]       Retry another mirror:
[ERROR]          Error while reading from repository: /technology/babel/update-site/R0.17.0/photon/plugins/org.eclipse.core.commands.nl_de_4.8.0.v20190713101254.jar.
[ERROR]    An error occurred while transferring artifact canonical: osgi.bundle,org.eclipse.core.commands.nl_de,4.8.0.v20190713101254 from repository https://archive.eclipse.org/technology/babel/update-site/R0.17.0/photon:
[ERROR]       Retry another mirror:
[ERROR]          Error while reading from repository: /technology/babel/update-site/R0.17.0/photon/plugins/org.eclipse.core.commands.nl_de_4.8.0.v20190713101254.jar.
[ERROR]    An error occurred while transferring artifact canonical: osgi.bundle,org.eclipse.core.commands.nl_de,4.8.0.v20190713101254 from repository https://archive.eclipse.org/technology/babel/update-site/R0.17.0/photon:
[ERROR]       Retry another mirror:
[ERROR]          Error while reading from repository: /technology/babel/update-site/R0.17.0/photon/plugins/org.eclipse.core.commands.nl_de_4.8.0.v20190713101254.jar.
[ERROR]    An error occurred while transferring artifact canonical: osgi.bundle,org.eclipse.core.commands.nl_de,4.8.0.v20190713101254 from repository https://archive.eclipse.org/technology/babel/update-site/R0.17.0/photon:
[ERROR]       Retry another mirror:
[ERROR]          Error while reading from repository: /technology/babel/update-site/R0.17.0/photon/plugins/org.eclipse.core.commands.nl_de_4.8.0.v20190713101254.jar.
[ERROR]    An error occurred while transferring artifact canonical: osgi.bundle,org.eclipse.core.commands.nl_de,4.8.0.v20190713101254 from repository https://archive.eclipse.org/technology/babel/update-site/R0.17.0/photon:
[ERROR]       Retry another mirror:
[ERROR]          Error while reading from repository: /technology/babel/update-site/R0.17.0/photon/plugins/org.eclipse.core.commands.nl_de_4.8.0.v20190713101254.jar.
[ERROR]    An error occurred while transferring artifact canonical: osgi.bundle,org.eclipse.core.commands.nl_de,4.8.0.v20190713101254 from repository https://archive.eclipse.org/technology/babel/update-site/R0.17.0/photon:
[ERROR]       Retry another mirror:
[ERROR]          Error while reading from repository: /technology/babel/update-site/R0.17.0/photon/plugins/org.eclipse.core.commands.nl_de_4.8.0.v20190713101254.jar.
[ERROR]    An error occurred while transferring artifact canonical: osgi.bundle,org.eclipse.core.commands.nl_de,4.8.0.v20190713101254 from repository https://archive.eclipse.org/technology/babel/update-site/R0.17.0/photon:
[ERROR]       Retry another mirror:
[ERROR]          Error while reading from repository: /technology/babel/update-site/R0.17.0/photon/plugins/org.eclipse.core.commands.nl_de_4.8.0.v20190713101254.jar.
[ERROR]    An error occurred while transferring artifact canonical: osgi.bundle,org.eclipse.core.commands.nl_de,4.8.0.v20190713101254 from repository https://archive.eclipse.org/technology/babel/update-site/R0.17.0/photon:
[ERROR]       Retry another mirror:
[ERROR]          Error while reading from repository: /technology/babel/update-site/R0.17.0/photon/plugins/org.eclipse.core.commands.nl_de_4.8.0.v20190713101254.jar.

**Comment by laeubi** [comment]
If I remember right the archived sites do not work very well.

**Comment by laeubi** [comment]
@opcoach could you reproduce the issue with the latest 2.7.0 release? Can you even
provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue?

**Comment by laeubi** [comment]
No feedback so closing this, let us know if you can provide additional details so we can reopen this.
