### ISSUE TITLE
Tycho P2 resolution fails with 2.5.0 

### ISSUE THREAD

**Issue by sbouchet** [eclipse/tycho#341]
Hi,

while moving our builds to tycho 2.5.0, one of them suddenly fails with an Unresolved Requirement error :
Unresolved requirement: Import-Package: javax.servlet; version="[3.1.0,4.0.0)"

I tried multiple changes locally but still have this error ( like directly use the javax.servlet bundle ) 
It was working on tycho 2.4.0. I'm not sure what changed in the resolver since 2.4, and why it's only failing on this build only.

here is the falling PR: https://github.com/jbosstools/jbosstools-livereload/pull/147

and here is the working one: https://github.com/jbosstools/jbosstools-livereload/pull/148

**Comment by mickaelistria** [comment]
```
Non-resolvable parent POM for org.jboss.tools:livereload:1.5.200-SNAPSHOT: Could not transfer artifact org.jboss.tools:parent:pom:4.21.1.AM1-SNAPSHOT from/to jbosstools-base (${jbosstools-base-site}): Cannot access ${jbosstools-base-site} with type p2 using the available connector factories: BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 5, column 10
 ```
Can you please try to build a simpler example? Eg a single plugin module with just the necessary content in the MANIFEST.MF to make it fail + an appropriate .target file.

**Comment by sbouchet** [comment]
Hi again. 
I created a very small project with only MANIFEST.MF that reproduces the error.
https://github.com/sbouchet/tycho_341

gist here : https://gist.github.com/sbouchet/3a3d8ca06d99d6fae009ba6cadaa10d2

**Comment by sbouchet** [comment]
> The gist shows this project is failing to build with 2.4.0 already. How does it highlight a 2.5.0 specific issue?

? the first line is using Tycho 2.4.0 and ends as success, in the middle, there is the default mvn using Tycho 2.5.0 and fails.

**Comment by sbouchet** [comment]
OK, i can try to update to jetty 10 on my side, and if not possible/too complex, try out your workaround.

**Comment by akurtakov** [comment]
This one seems to have stalled. Thus I'm closing. Please reopen if there is still issue for you and you're ready to help with figuring it out.
