### ISSUE TITLE
Allow to use a remote target platform file via https://

### ISSUE THREAD

**Issue by vogella** [eclipse/tycho#354]
Currently a target platform file needs to be local. In multiple cases it would be useful if we could point to a remote file so that a target platform definition can be easily shared and accessed.

**Comment by mickaelistria** [comment]
That's already the pupose of publishing the .target files as Maven artifacts in a remote Maven repo.
Note that going to https://... uris entirely breaks the assumption that the build can be reproducible as the content pointed by random URIs can be mutable. On the opposite, with artifacts on a Maven repo, it's possible to release them so they become immutable and build is more reliable/reproducible.

That said, I wouldn't mind if this feature is added to Tycho, but I would encourage anyone willing to implement/use it to consider this potentially major pitfall compared to the current possibilities before investing more in this topic.

**Comment by vogella** [comment]
Thanks @laeubi for looking into this. I think you could use Github as source, for example https://raw.githubusercontent.com/vogellacompany/eclipse4book/master/target-platform/target-platform.target delivers a file.

**Comment by vogella** [comment]
Thanks @laeubi 

For reference: PDE bug for providing the same option: https://bugs.eclipse.org/bugs/show_bug.cgi?id=577005
