### ISSUE TITLE
Tycho pomless builds for Mac are missing the -XstartOnFirstThread

### ISSUE THREAD

**Issue by vogella** [eclipse/tycho#358]
If we try to use pomless builds for test on Mac, the runner complains:

***WARNING: Display must be created on main thread due to Cocoa restrictions. Use vmarg -XstartOnFirstThread
An error has occurred. See the log file

See also https://github.com/eclipse/tycho/discussions/234

**Comment by laeubi** [comment]
You should configure the neccesary settings for your vm/setup in the master-pom (example given in your reference).
Pomless do not add any (vendor specific) options by default.

**Comment by laeubi** [comment]
Also see https://stackoverflow.com/questions/28149634/what-does-the-xstartonfirstthread-vm-argument-do-mean

**Comment by laeubi** [comment]
Also related https://bugs.eclipse.org/bugs/show_bug.cgi?id=211625
