### ISSUE TITLE
Document which version of tycho is compiled with which version of JDK

### ISSUE THREAD

**Issue by zosrothko** [eclipse/tycho#379]
Hi

My company standard forces the usage of the Java JDK8 level with a compilation target of 1.8. Could you make clear in the documentation which level of JDK/JVM is compiled each version of Tycho.

Rigth now, one is working with tycho 1.2.0 and the tycho 2.5.0 does not work as it requires Java 11

**Comment by akurtakov** [comment]
It's already in the release notes - https://wiki.eclipse.org/Tycho/Release_Notes/2.0 . Also as written there "Note that this is a requirement for Tycho itself to run. Tycho can still build bundle that require older Java versions and have those bundles targeting older Java versions. "

**Comment by zosrothko** [comment]
Unless I am totally blind, there is no such list of supported JDK by tycho versions in this release notes: [https://wiki.eclipse.org/Tycho/Release_Notes/2.0](https://wiki.eclipse.org/Tycho/Release_Notes/2.0). (i.e. I am not asking if tycho 2.0 supports or not bundle with older JDKs)

By the way, what is the reason why tycho 2.0 requires Java 11itself?

**Comment by laeubi** [comment]
> Unless I am totally blind, there is no such list of supported JDK by tycho versions

There is no such "list", Tycho 1.x --> Java 8, Tycho 2.x -> Java 11

> what is the reason why tycho 2.0 requires Java 11itself

Java 8 is EOL and most open-source libs (especially those tycho uses in the background) are migrating to java 11.

So you'd better ask why your company standards forces you to use ancient Java versions ;-)

**Comment by zosrothko** [comment]
1/ There is no reason to move from Java 8 unless thcho code itself uses features from Java version greater that Java 8. 
2/ I am setting the company standard and will stick to Java 8  because none of our codebase is using features of Java 9 and successor.
3/ Java 8 is not EOL. You can use the free version without support and also get support from Oracle. By the way did you find any bug in the Java 8 JDK or JRE that was blocking??
4/ I have the same problem of mandatory Java11 with open source code (like IzPack for example) that are moving to Java 11 WITHOUT any good reason except to follow the line... 
5/ Using Java 111 add extra work for no benefit at all

So I am reasking: what is the reason why tycho 2.0 requires Java 11 itself? Is tycho using features from Java 9 and successors? and which ones?

**Comment by mickaelistria** [comment]
Tycho does use some APIs that are not in Java 8. It uses Eclipse bundles (JDT, p2) that require Java 11. Newer Java versions are usually better on both language, compilation, execution aspects than previous ones. Sticking to older version of Java reduces the productivity of developers who cannot leverage new and better constructs of the language, and results in application that don't perform as well as they could because they don't leverage new capabilities of compilation/runtime. This is not desired for Tycho,
Beware, Tycho is even likely to switch to Java 17 in less than 2 years. Good luck with Java 8!

**Comment by akurtakov** [comment]
The nightmare I had with supporting modular and non-modular Java at the same time is enough of a reason to *never* agree to support both anymore. E.g. https://bugs.eclipse.org/bugs/show_bug.cgi?id=532302 is just one example. 
But there is smth more important - *humans* - until the project is so well in terms of contributions that there are people willing to actually do the work to support old versions, work on complications coming from that and etc. - only latest Java LTS version will be supported! Even if we say Java 11 is supported - I don't have the time to look into issues that don't happen on Java 17 unless it breaks some of my projects.

**Comment by zosrothko** [comment]
@mickaelistria "Sticking to older version of Java reduces the productivity of developers"...That's not a general valid statement... most Java programmer's do not even understand the Lambda expressions bring by Java8... Thus speaking of nice productive features bring by Java9 en successor is just a myth... standard Java programmers stick to java 1.6/1.17...

**Comment by laeubi** [comment]
> standard Java programmers stick to java 1.6/1.17...

... can stick with Tycho 1.x

**Comment by zosrothko** [comment]
I have no problem for Tycho 2.X using Java 11 if its basecode IS using features from Java9++. I have a concern for projects that move to Java9++ only because it is the trend and their basecode is only using Java8-- features (as IzPack for exemple).

And about Tycho 1.x, one are using the 1.2.0 because there are problems with the 1.7.0... and if I open a issue on Tycho 1.7, the answer will be: Move to Tycho 2.X and this is problem. Tycho 1.7 should be also maintained.

**Comment by akurtakov** [comment]
Let's end this useless discussion with few critical remarks:
* This is volunteer project
* Technical decisions are taken by committers who actually spent their time keeping the project working
* Users are welcome express their opinion but they also **have to** respect the fact that people actually doing the work can have another one
* Whoever wants to has his/her voice stronger is more than welcome to start fixing issues in Tycho, best if fixing others' issues
* One can either suffer change or embrace change! After suffering enough decision has been to embrace change and no longer suffer for others.

**Comment by laeubi** [comment]
> I have a concern for projects that move to Java9++ only because

You can always fork the project and maintain a pure Java 8 codebase...

> Tycho 1.7 should be also maintained.

You can open Pull-Request against the [tycho-1.7.x](https://github.com/eclipse/tycho/tree/tycho-1.7.x) branch and then there is a good chance we can make a bug-fix release, or you can simply build your own version of tycho (see above) thats how open-source works.
