### ISSUE TITLE
Support nested targets

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#401]
PDE supports [nested targets](https://bugs.eclipse.org/bugs/show_bug.cgi?id=577184) now, tycho should support this as well.

**Comment by mickaelistria** [comment]
Please add a note about it to release notes; ideally referencing Eclipse PDE help about how this works for .target file in PDE and telling Tycho now mimics it.

**Comment by laeubi** [comment]
See https://github.com/eclipse/tycho/blob/master/RELEASE_NOTES.md#support-for-nested-targets

**Comment by mickaelistria** [comment]
> See https://github.com/eclipse/tycho/blob/master/RELEASE_NOTES.md#support-for-nested-targets

Thanks, I missed it.
Ideally, the nested platforms would be described in https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Fguide%2Ftools%2Ftarget_shared%2Fedit_target_wizard.htm and/or some other docs of PDE and Tycho would just reference it.
