### ISSUE TITLE
Lots of deprecation errors in tycho build 'Please fix your build!'

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#410]
I'm using maven 3.6.3 and get a lot of

```
[ERROR] 

Maven dependencies of Maven Plugins should be in provided scope.
Please make sure that all your dependencies declared in POM whose group ID is
org.apache.maven have set '<scope>provided</scope>' as well.
In the future this error will break the build.

The following dependencies are in wrong scope:
 * org.apache.maven:maven-plugin-api:jar:3.8.4:compile
 * org.apache.maven:maven-model:jar:3.8.4:compile
 * org.apache.maven:maven-artifact:jar:3.8.4:compile
 * org.apache.maven:maven-core:jar:3.8.4:compile
 * org.apache.maven:maven-settings:jar:3.8.4:compile
 * org.apache.maven:maven-settings-builder:jar:3.8.4:compile
 * org.apache.maven:maven-builder-support:jar:3.8.4:compile
 * org.apache.maven:maven-repository-metadata:jar:3.8.4:compile
 * org.apache.maven:maven-model-builder:jar:3.8.4:compile
 * org.apache.maven:maven-resolver-provider:jar:3.8.4:compile
 * org.apache.maven:maven-compat:jar:3.8.4:compile

Please fix your build!
```

**Comment by laeubi** [comment]
@akurtakov is this intentional or do we have a problem in tycho?

**Comment by akurtakov** [comment]
Seems that this is coming from https://issues.apache.org/jira/projects/MPLUGIN/issues/MPLUGIN-370?filter=allissues and maven-plugin-tools was updated with https://github.com/eclipse/tycho/commit/a4b5add36e88a74bc0bfd30e60bff05a37b7d885 . So this is really new error/warning coming from Maven developers. Seems like these dependencies will have to be with scope=provided

**Comment by Bananeweizen** [comment]
The problem is, at least for me locally just adding those scopes leads to compile errors for running "mvn clean install", e.g. in tycho-surefire-plugin. I have compared the effective POM and see no other difference than the one line adding the scope. I'm rather clueless why it doesn't compile.
