### ISSUE TITLE
Allow to give the Maven part in the pde editor a name

### ISSUE THREAD

**Issue by vogella** [eclipse/tycho#419]
Currently the M2e extension shows "Maven dependencies" with the number of libraries in the PDE editor.

Would be nice to allow to specify a label for these entries and show this label in the label of the editor, for example as 

 "Maven dependencies for Jetty" where "Jetty" in the label for this entry.

**Comment by mickaelistria** [comment]
Wrong project, here it's Tycho ;)

**Comment by vogella** [comment]
Sorry
