### ISSUE TITLE
tycho-p2-extras:mirror does not mirror property pgp.publicKeys

### ISSUE THREAD

**Issue by sratz** [eclipse/tycho#425]
When mirroring a p2 repo using `tycho-p2-extras:mirror`, the `pgp.signatures` property of individual artifacts is mirrored, but the top-level `pgp.publicKeys` property from `artifacts.xml` is not.

The mirrored repository is then corrupt and cannot be used to install software, since `org.eclipse.equinox.internal.p2.artifact.processors.pgp.PGPSignatureVerifier#initialize` is unable to verify the signatures.

E.g.:
```
[ERROR] An error occurred while transferring artifact canonical: osgi.bundle,net.bytebuddy.byte-buddy-agent,1.12.2 from repository <mirrored>:
[ERROR]    Result of processing steps.:
[ERROR]       Public key not found for 8074478291308066379.
```

**Comment by mickaelistria** [comment]
Indeed, tycho-p2-mirror does mirror *units* and doesn't copy repo properties. And the public key does need to be available for p2 to verify the artifact. If you plan to mirror units that are signed by a PGP key, you need your repo to include this pgp key property.
What do you think is the best approach for that? Should the mirror mojo add an extra flag to copy the PGP keys, or would it be better to be a separate mojo to copy some properties, or...?

**Comment by laeubi** [comment]
The problem here is with `<append>` flag as there is only one property for keys (as discussed earlier) this then would require that the MirrorMojo actually understand what properties means and merge these PGP public keys (looking for duplicates).

**Comment by sratz** [comment]
> Should the mirror mojo add an extra flag to copy the PGP keys, or would it be better to be a separate mojo to copy some properties, or...

I'd expect the default to copy over the keys. Without them, the resulting repo is of no use unless it is being refined afterwards.



> The problem here is with `<append>` flag as there is only one property for keys (as discussed earlier) this then would require that the MirrorMojo actually understand what properties means and merge these PGP public keys (looking for duplicates).

`org.eclipse.equinox.internal.p2.artifact.repository.MirrorRequest` already has special handling for `pgp.signatures`. Couldn't we add special handling to deal with `pgp.publicKeys` as well?

**Comment by mickaelistria** [comment]
as a workaround, you can manually add the property to artifact metadata; or -probably better- just copy the artifacts.xml.xz/jar/xml of the source repo into the target one manually, assuming content is identical.

**Comment by mickaelistria** [comment]
See also #481

**Comment by mickaelistria** [comment]
Public keys are now copied to artifacts directly (if you're using latest build of Eclipse Platform), so this shouldn't be an issue anymore in practice.
