### ISSUE TITLE
Enable parallel compile again?

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#459]
https://github.com/eclipse/tycho/blob/1fe29d7ddbb31213230bb3bc75a90a8268467d9e/tycho-compiler-plugin/src/main/java/org/eclipse/tycho/compiler/AbstractOsgiCompilerMojo.java#L338

@akurtakov  AbstractOsgiCompilerMojo references [Bug 574450](https://bugs.eclipse.org/bugs/show_bug.cgi?id=574450) that is marked as fixed, so can we enable parallel compiling again?

**Comment by Bananeweizen** [comment]
After reading all the linked bugzilla and github comments, it looks safe to me.
