### ISSUE TITLE
 Computing target platform for MavenProject:  ... is missleading

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#463]
Currently the Target platform computation is attributed to the first project in the following way in the log:

```
[INFO] Computing target platform for MavenProject:  ...
[INFO] Resolving dependencies of MavenProject: ...
```

what actually happens is: that the (individual)  target platform for the maven project is computed but this might trigger e.g resolving a target file. This could take a bit longer for the first project afterwards it is cached.
As most users won't understand the difference and might be confused why one project takes so long we should change this:

1. Output in the log if a target file is resolved with the name of the target
2. Find a better wording for the individual target of a project

Maybe we simply can use `Resolving dependencies of MavenProject: ...` as the only output and only write more fine grained steps with debug output.

**Comment by mickaelistria** [comment]
> Maybe we simply can use Resolving dependencies of MavenProject: ... as the only output and only write more fine grained steps with debug output.

+1
