### ISSUE TITLE
tycho-document-bundle-plugin tests depend on PATH

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse/tycho#471]
After lots of trial and error I've just found one reason for failing integration tests. The document-bundle-plugin tests run javadoc by just invoking the javadoc executable without using any path. Therefore whatever is first on the local PATH environment variable will be called. Since there are subtle differences between Java 8 (what I had on the path) and Java 11 Javadoc, the verification groovy script fails with some files not found, some files not matching content and finally even NoClassDefFoundError (for the Doclet).

What is a good way to avoid that? I can imagine these solutions:
* Somehow get the toolchain definition from maven (how?) and use that path to create a FQN
* verify the generated files to contain "Generated by javadoc (11" (which they have as HTML comment)

Any better ideas?

**Comment by laeubi** [comment]
Maybe we can check how the [maven-javadoc-plugin](https://maven.apache.org/plugins/maven-javadoc-plugin/) works?
