### ISSUE TITLE
Remove deprecated packaging types

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#474]
```
    @Deprecated
    public static final String TYPE_ECLIPSE_UPDATE_SITE = "eclipse-update-site";
    @Deprecated
    public static final String TYPE_ECLIPSE_APPLICATION = "eclipse-application";
```

When adding new features to tycho it becomes harder and harder to support these deprecated stuff, we should remove them on the next major release.

**Comment by mbooth101** [comment]
See also: https://bugs.eclipse.org/bugs/show_bug.cgi?id=342876

**Comment by akurtakov** [comment]
This one is done via https://github.com/eclipse/tycho/commit/fb40c068ffcf5b7507a8268d7b778f05c77f4769 and https://github.com/eclipse/tycho/commit/29631df290306503327d825ba9b418a633f154ba
