### ISSUE TITLE
drop "fixSWT"

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#476]
We should simply drop this as the depending bug has be resolved for more than 5 years:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=381167

**Comment by akurtakov** [comment]
I think we can deliver this one for 2.7 and not wait for 3.0.

**Comment by mickaelistria** [comment]
Removing 3.0 milestone, this can be included to master anytime as it's not going to break existing builds as far as I understand.
