### ISSUE TITLE
drop org.eclipse.tycho.plugins.p2.publisher.PublishProductMojo.flavor

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#477]
It is marked deprecated for a long time now and should be removed. removal will be backward compatible if this setting is not used.

**Comment by mickaelistria** [comment]
Removing milestone. If it's mark as deprecated for a long time it's acceptable to remove it in a minor release.

**Comment by akurtakov** [comment]
Done via https://github.com/eclipse/tycho/commit/0f60de36b5d5ce8c7ac22cebb3f0367c0288afbb

**Comment by chrislake** [comment]
Just wanted to leave a note here in case anyone else comes across this.

This change broke our builds as we have to change the default flavor from "tooling". The reason being that we have multiple Products (<packaging>eclipse-repository</packaging>) built in to the one repository and so each product gets its own flavor.

Without this, every product having the 'tooling' flavor destroys any unique "Start Levels" for bundles in a given product, for example Product 1 needs bundle "org.shared.bundle" to start at level 3 and Product 2 needs "org.shared.bundle" to start at level 6.

Without the unique flavor, we only get one instance of <unit id='toolingorg.shared.bundle'.../> in the "content.xml" file for the repository and so all Products can only use one start level for that bundle.

**Comment by laeubi** [comment]
@chrislake can you provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue?

**Comment by chrislake** [comment]
I am looking in to it.

**Comment by laeubi** [comment]
@chrislake the first would of course be a test that shows the problem if you can provide a fix with the test as well this would be great.
