### ISSUE TITLE
pgp-sign should by default place signer key on artifact properties

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/tycho#481]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=578023
The signer key should also be added directly to artifact to allow mirroring more easily. The overhead seems on file size seems acceptable.

**Comment by mickaelistria** [comment]
This should be fixed in next snapshots.

**Comment by laeubi** [comment]
@mickaelistria should I include this for the tycho 2.6 release?

**Comment by mickaelistria** [comment]
Don'tbother. Platform will use 2.7.0-SNAPSHOT to get this.

-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/eclipseide> developer, for Red Hat
Developers <https://developers.redhat.com/>
