### ISSUE TITLE
MavenTargetDefinitionContent should not copy artifacts but directly reference Maven locations

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/tycho#484]
The reason why we have duplicated Maven artifacts to the Tycho cache is that the TargetPlatformResolution assumes that all TargetDefinitionContent are p2 artifact repositories and consume them as such. So this artifact repository is then processed and content is copied as if it were remote.
Same could apply to other TargetDefinitionContent.
In general, TargetDefinitionContent should -instead of providing an ArtifactRepository- provide a method to get a ArtifactDescriptor (which includes either link to file, or a supplier for it). Whether to copy from a p2 ArtifactRepository or not should be internal to the content.

**Comment by mickaelistria** [comment]
This would solve #124 and #443

**Comment by laeubi** [comment]
I don't think this is a good idea saying ArtifactRepository is always remote does not hold true in many cases (e.g. one could load a repository from the local file system.

A "Target" is actually a ArtifactRepository+MetaDataRepository.

**Comment by laeubi** [comment]
For #443 we probably have to add additional properties to the IArtifactDescriptor instead?

**Comment by mickaelistria** [comment]
Yes, that's how I first thought of #443, but it also brought the question of duplication of artifacts and usage of unusual systemPath for Maven deps. Those 2 problems are deeply related and all boil down to the fact that we assume everything is an artifact repository and p2 can only copy from artifact repository.
Instead, Tycho should embrace that some of the locations do already contain the artifact, and that there is no need to "get" the artifact, nor to stream it into a sink. p2 has no API that allows it as far as I could see, so it's really Tycho that needs to let differnet location use different strategy when it comes to returning the artifact descriptor.

**Comment by laeubi** [comment]
That would really complicate a lot of things, if its really a P2 restriction I think we should solve it there.

**Comment by mickaelistria** [comment]
This is hard to change, but the result would be simpler. The current code is very complicated because it emulates things that are not artifact repositories as artifact repositories, and it heavily rely on p2 startegies that could relatively easily be made internal.

**Comment by laeubi** [comment]
> This is hard to change

Do you mean for P2 or for Tycho?

Unify everything to ArtifactRepository+MetaDataRepository has greatly reduced the amount of work that need to be done per location and actually simplifies a lot of handling (e.g. merging location contents into a larger view).

**Comment by mickaelistria** [comment]
I narrowed it down.
The issue is that the ListCompositeArtifactRepository will then be used for everything coming from TargetDefinition, but in TargetPlatformFactoryImpl#createExternalArtifactProvider , this repository will be proxied with MirroringArtifactProvider which will always populate cache.
I believe the MirroringArtifactProvider should not apply to all TargetDefinitionContent, but only to the URITargetDefinitionContent. All other sources don't need mirroring.

**Comment by mickaelistria** [comment]
I added a patch that make Maven Target locations bypass the Tycho bundle cache in resultion as part of #473

**Comment by laeubi** [comment]
> I narrowed it down. The issue is that the ListCompositeArtifactRepository will then be used for everything coming from TargetDefinition, but in TargetPlatformFactoryImpl#createExternalArtifactProvider , this repository will be proxied with MirroringArtifactProvider which will always populate cache. I believe the MirroringArtifactProvider should not apply to all TargetDefinitionContent, but only to the URITargetDefinitionContent. All other sources don't need mirroring.

I don't think this holds true, just think of a `file:`, or a `mvn:` based URI, both are local. Or a mavenized one where some artifacts are remote and some are (maven repository) local files. I think the Artifact itself should describe if it is local or not.

**Comment by laeubi** [comment]
> I added a patch that make Maven Target locations bypass the Tycho bundle cache in resultion as part of #473

Can you explain what makes the difference? Is it the sorting? Maybe you can extract this into a separate patch?

**Comment by mickaelistria** [comment]
I tried to explain it a bit in commit message of https://github.com/eclipse/tycho/pull/473/commits/d34241eeab432e7162290e0f61e142dd968b8b0c . Basically, the key is to *not* use ArtifactRepositoryProvider/MirroringArtifactProvider for local content, but to use FileRepositoryArtifactProvider instead, and give higher priority to the FileRepositoryArtifactProvider in the joint CompositeArtifactProvider .
Flattening and sorting the ListCompositeArtifactRepository allows to distinguish what's remote and needs copy, and what does not.

**Comment by laeubi** [comment]
Could you extract that part and submit is as a fix for https://github.com/eclipse/tycho/issues/124 independent from this task?

**Comment by mickaelistria** [comment]
Yes, I'll try that. I'm still working on it as it causes an issue with p2 director. When all tests pass and the result seems fine, I'll rework the PR into better-scoped commits.

**Comment by laeubi** [comment]
> I'm still working on it as it causes an issue with p2 director.

I remember there was such issues and probably I gave up at that point last time, so good luck with that :+1:  It still might be good to split that part already so its clear what causing issues (maybe by deprecated stuff, then please add a ticket so we don't forget to purge that for Tycho 3.x).

**Comment by mickaelistria** [comment]
@laeubi here is the magic trick to fix director issues (and I think it fixes a lot of them!), which was already indicated in a TODO: https://github.com/eclipse/tycho/pull/506/commits/c499f240db20d80d41b3f559f56f5cc185cf4e90
PR #506 is ready for review if you're interested.
