### ISSUE TITLE
Release Tycho 2.6.0

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#490]
# Releasing Tycho 2.6.0

This describes the steps to perform a release of Tycho:

- [x] Make sure all fixed issues and merged PRs have the correct milestone for this release, to finding PRs without milestone you can use the following filter `is:pr is:merged no:milestone` issues without milestone can be found with `is:issue no:milestone is:closed`
- [x] Prepare the [release notes](https://github.com/eclipse/tycho/blob/master/RELEASE_NOTES.md) which should provide a quick overview of new features and bug fixes
- [x] Create branch `tycho-N.M.x` (e.g. `tycho-2.4.x`) for upcoming release and push it to remote; this branch should remain frozen until the release, only major fixes for regressions could be merged in before release. Work can still happen regularly on the `master` branch.
- [x] Create release record on https://projects.eclipse.org/projects/technology.tycho projects.eclipse.org, link the N&N to https://github.com/eclipse/tycho/blob/[branch-name]/RELEASE_NOTES.md release notes]
- [x] Update the Jenkinsfile on the `tycho-N.M.x` and adjust the `stage('Deploy Snapshot')` to reference the new branch in the when conditional.
- [x] Update versions on `master `to future release with `mvn org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=<NEXT_VERSION>-SNAPSHOT` and push to remote
- [x] Announce the intent to release and request feedback about snapshots on tycho-user@eclipse.org and [GitHub discussions](https://github.com/eclipse/tycho/discussions):
```
Subject: Please test snapshots for upcoming <VERSION> release

We plan to release Tycho <VERSION> next week. For details of new features and bugfixes, see release notes [1].
Please help by testing the SNAPSHOTS build. To use it, change your Tycho version to <VERSION>-SNAPSHOT and add snippet [2] to your pom.

We plan to promote this release in one week unless major regressions are found.

Regards,
Tycho team

[1] https://github.com/eclipse/wildwebdeveloper/blob/master/RELEASE_NOTES.md
[2]
<pluginRepositories>
    <pluginRepository>
        <id>tycho-snapshots</id>
        <url>https://repo.eclipse.org/content/repositories/tycho-snapshots/</url>
    </pluginRepository>
</pluginRepositories>
```

... Wait until review date (usually a week later)...

- [x] Make sure you have everything setup (GPG installed!) for deploying to the Nexus OSS repository, see https://central.sonatype.org/pages/ossrh-guide.html guide
- [x] Add your credentials for server `sonatype-nexus-staging` in `~/.m2/settings.xml`
```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
   <!-- ... -->
   <servers>
    <server>
      <id>sonatype-nexus-staging</id>
      <username>mickael.istria</username>
      <password>securePassword</password> <!-- use `mvn --encrypt-password` to not store plain text -->
    </server>
    <!-- ... -->
   </servers>
</settings>
</source>
```

- [x] `git fetch eclipse tycho-N.M.x && git checkout FETCH_HEAD` to get the branch to be released
- [x] Update version to remove `-SNAPSHOT` with `mvn org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=<VERSION>`
- [x] Update versions in tycho-demo folder
- [x] `git add * && git commit` version change
- [x] Sync to release commit and deploy to nexus staging repository: `mvn clean deploy -Prelease -DforgeReleaseId=sonatype-nexus-staging -DforgeReleaseUrl=https://oss.sonatype.org/service/local/staging/deploy/maven2/ -DskipTests`
- In the meantime...
    - [x] `git tag tycho-<TYCHO_VERSION>`
    - [x] Find out who contributed to the release:
```
git log --pretty=format:%an tycho-<previousVersion>..tycho-<newVersion> | sort | uniq
git log --grep="Also-[bB]y:" tycho-<previousVersion>..tycho-<newVersion> | grep -i also-by | sed -e 's/.*Also-[bB]y:\s*\(.*\)/\1/' | sort | uniq
```

   - [x] Prepare (in a text editor) announcement, thanking the contributors:
```
Subject: Tycho <VERSION> is released

Tycho <VERSION> has been released and is available from Maven Central repository.

🆕 https://github.com/eclipse/tycho/blob/master/RELEASE_NOTES.md#xyz
🏷️ https://github.com/eclipse/tycho/tree/tycho-x.y.z
👔 https://projects.eclipse.org/projects/technology.tycho/releases/x.y.z
🙏 contributors who contributed patches for this release:
<contributors>
and thanks and to everyone who helped us with testing the staged version.

Regards,

```
- [x] On https://oss.sonatype.org/#stagingRepositories , Close the staging repository, get the staging repo URL from Nexus
- [x] Wait for artifacts to be available on Maven central.
- [x] `git push eclipse HEAD:tycho-N.M.x tycho-<TYCHO_VERSION>` (push commit to branch, and tag)
- Documentation
  - [x] Generate site docs using `mvn install site site:stage -DskipTests` and check the result from `target/staging` seems viable.
  - [x] Prepare documentation on the webite, using git repo https://git.eclipse.org/c/www.eclipse.org/tycho.git/ : copy the local site docs folders `target/staging/sitedocs` to the existing `sitedocs` folder and then submit as Gerrit review (don't merge yet)
- Announce the release
  - [x] Send prepared announce of the release to [GitHub discussions](https://github.com/eclipse/tycho/discussions) and tycho-dev@eclipse.org,
  - [ ] Optionally, announce on other medias (Twitter)
- [x] Create, push and merge patch changing the bootstrap Tycho version for Tycho build (eg https://git.eclipse.org/r/c/tycho/org.eclipse.tycho/+/174964 )

**Comment by laeubi** [comment]
@mickaelistria @akurtakov I also sceduled a relase review as the release page says:

> Reviews are required for all major and minor releases. 

should I add this step to the release process documentation?

**Comment by laeubi** [comment]
@akurtakov can you create an announcement?

Subject: Tycho 2.6.0 release

We plan to release Tycho 2.6.0 at end of month. For details of new features and bugfixes, see [release notes](https://github.com/eclipse/tycho/blob/tycho-2.6.x/RELEASE_NOTES.md).
Please help by testing the SNAPSHOTS build. To use it, change your tycho version to 2.6.0-SNAPSHOT and add the following snippet to your pom.

```
<pluginRepositories>
    <pluginRepository>
      <id>tycho-snapshots</id>
      <url>https://repo.eclipse.org/content/repositories/tycho-snapshots/</url>
    </pluginRepository>
</pluginRepositories>
```

We plan to promote this release at end of month unless major regressions are found that can't be fixed at least one week before the release date.

Regards,
Tycho team

**Comment by akurtakov** [comment]
Done

**Comment by laeubi** [comment]
Great, I have one bug https://github.com/eclipse/tycho/issues/496 that causes a regression https://github.com/eclipse/tycho/issues/493, I think we should include the bugfix instead of fixing https://github.com/eclipse/tycho/issues/493 as this would be a bigger change....

**Comment by cdietrich** [comment]
Xtext builds seem all fine.

**Comment by mickaelistria** [comment]
I don't think there is anything to do beyond waiting for review to complete. Did I miss something in particular?

**Comment by mickaelistria** [comment]
By the way, the release is not necessarily tied to the review now (many things changed recently in EDP). I thinkwethink can just move forward with the release and get review complete in parallel.

**Comment by laeubi** [comment]
> I don't think there is anything to do beyond waiting for review to complete. Did I miss something in particular?

Yes

> By the way, the release is not necessarily tied to the review now (many things changed recently in EDP)

Feel free to stage this as soon as it seems suitable then... :+1:

**Comment by mickaelistria** [comment]
I'd like to make you able to stage/promote release. Can you please perform the steps listed at https://central.sonatype.org/publish/publish-guide/#create-a-ticket-with-sonatype ?

**Comment by laeubi** [comment]
What specifically do you wan't me to do? The link seems to point to adding a new project, I assume tycho is already registered? I also have once deployed something to maven-central for another project so probably PGP key should be registered as well.

**Comment by mickaelistria** [comment]
OK, so if you think you have permission to stage to OSSRH already, please do it. Otherwise, we'll see the error code and ask for more permissions (I don't remember whether OSSRH permissions are per-project or not).

**Comment by mickaelistria** [comment]
@laeubi  Any progress here? Could you push to sonatype OSSRH staging?

**Comment by laeubi** [comment]
I get error:
> Authorization failed for https://oss.sonatype.org/service/local/staging/deploy/maven2/org/eclipse/tycho/tycho/2.6.0/tycho-2.6.0.pom 403 Forbidden

so it seems I'm not allowed for tycho.

**Comment by laeubi** [comment]
https://issues.sonatype.org/browse/OSSRH-77453

**Comment by laeubi** [comment]
Artifacts are now deployed to sonartype

**Comment by laeubi** [comment]
> git log --pretty=format:%an tycho-<previousVersion>..tycho-<newVersion> | sort | uniq

` git log --pretty=format:%an tycho-2.5.0..tycho-2.6.0 | sort | uniq` gives me an error commit or path does not exits...

**Comment by mickaelistria** [comment]
Does `tycho-2.6.0` exist on your end?

**Comment by laeubi** [comment]
But it seems tycho 2.5.0 tag is missing...

**Comment by laeubi** [comment]
strange https://github.com/eclipse/tycho/tags shows the tag by running git-tag locally does not show the tag...

**Comment by laeubi** [comment]
I have updated the release doc: https://github.com/eclipse/tycho/commit/ebd1cd9f45720d67a4bb4342326553fa0c94b167

**Comment by laeubi** [comment]
> Close the staging repository, get the staging repo URL from Nexus

Should I really *close* the repository? And what should one do with 'the staging repo URL'

**Comment by mickaelistria** [comment]
We recently agreed that the staging phase never identified any bug that couldn't be identified earlier on snapshots and decided to ignore the staging phase. So for release, we go directly from staging to release and can ignore the staging URL.

**Comment by laeubi** [comment]
> We recently agreed that the staging phase never identified any bug that couldn't be identified earlier on snapshots and decided to ignore the staging phase. So for release, we go directly from staging to release and can ignore the staging URL.

I adjusted the docs: https://github.com/eclipse/tycho/commit/87424502d3f797a1d426b3af7d33c628c5e6e26d

How long does it takes between closing and the artifacts appear on central?

**Comment by mickaelistria** [comment]
In my experience, between 5 and 10 minutes.

**Comment by laeubi** [comment]
It seems I can't access `ssh://<user_id>@git.eclipse.org:29418/www.eclipse.org/tycho.git` do I need special permissions?

**Comment by cdietrich** [comment]
dont you need to close AND release?

**Comment by laeubi** [comment]
> dont you need to close AND release?

No idea :-) Close was the only available action and the documentation indicates so...

**Comment by cdietrich** [comment]
in xtext we hit close. then refresh button. then release

**Comment by laeubi** [comment]
> in xtext we hit close. then refresh button. then release

After refresh it show `No staging repositories available`

**Comment by cdietrich** [comment]
https://central.sonatype.org/publish/release/ also says close and release

**Comment by cdietrich** [comment]
wonder if you really closed it
i can see this one
<img width="828" alt="Bildschirmfoto 2022-01-20 um 19 42 38" src="https://user-images.githubusercontent.com/238736/150401926-950a8f29-f4f4-43c9-a6e1-fb71f907ac47.png">

**Comment by cdietrich** [comment]
looks like the repo still did not appear in central. can you check once more if you list is really empty?

**Comment by laeubi** [comment]
I can now see the repo again, but it has failures, one seems to be related to

- https://github.com/eclipse/tycho/issues/546

and it seems I used the wrong pgp key (will check that)

![grafik](https://user-images.githubusercontent.com/1331477/150478379-ccc3ee53-0aa7-46c6-b245-d624ef3cf757.png)

**Comment by cdietrich** [comment]
there also seems to be a missing javadoc somewhere

**Comment by laeubi** [comment]
I have updated the docs regarding the checks and how to perform the release of the staging repository: https://github.com/eclipse/tycho/commit/5c83ecd968eae37aa328020d228c8f03b2a3168c

**Comment by laeubi** [comment]
Release is done for this now, I think we can omit advertising at tycho-dev@eclipse.org and for the twitter stuff I left this to someone else if desired (I dont use twitter at all ...).

**Comment by akurtakov** [comment]
Announcement on tycho-dev is required as this is the "official" channel for Eclipse Foundation projects.
