### ISSUE TITLE
No notification on failed build

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#50]
It seems that currently no notification mail is send if a PR build fails.

**Comment by mickaelistria** [comment]
It's more a GitHub limitation compared to Gerrit. I don't know whether GitHub can be configured to send notification for (automated) reviews without comment.

**Comment by laeubi** [comment]
@mickaelistria thats not the job of github but jenkins:

https://wiki.eclipse.org/Jenkins (search for 'send a mail on unsuccessful and fixed builds')

**Comment by Dufgui** [comment]
you can do it by just adding some line in https://github.com/eclipse/tycho/blob/master/Jenkinsfile :
```
post {  
         failure {  
             mail bcc: '', body: "<b>Example</b><br>Project: ${env.JOB_NAME} <br>Build Number: ${env.BUILD_NUMBER} <br> URL de build: ${env.BUILD_URL}", cc: '', charset: 'UTF-8', from: '', mimeType: 'text/html', replyTo: '', subject: "ERROR CI: Project name -> ${env.JOB_NAME}", to: "foo@foomail.com";  
         }    
     }  
```

You just must choose the mailing list (maybe commiter mayling list if there is one or tycho dev mailing list)

**Comment by laeubi** [comment]
@mickaelistria do you want to adjust he Jenkinsfile or should we close this as GH actions are enough to get attention?

**Comment by mickaelistria** [comment]
Given that GH actions often return incomplete results, it's still worth keeping this issue on.

**Comment by akurtakov** [comment]
We survived a year without these notifications so clearly no one sees it important.
