### ISSUE TITLE
Bug 571533 - tycho-compiler-plugin with useJDK=BREE and BREE==JavaSE-1.8 fails to find some EE packages

### ISSUE THREAD

**Issue by ind1go** [eclipse/tycho#51]
Was: https://bugs.eclipse.org/bugs/show_bug.cgi?id=571533

> Hi all!
> 
> I have a bundle that uses JAXB, i.e. the javax.xml.bind packages that came with Java up until their removal in Java 11.
> 
> The build itself runs Java 11 and Maven 3.6.3.
> 
> The tycho-compiler-plugin is configured to useJDK=BREE, and the plugin BREE is Java 8. I have toolchains set up for JDK 8 and JDK 11.
> 
> At Tycho 2.1.0, this build succeeds. However, upgrading to Tycho 2.2.0, the build now fails - error at the bottom. It looks like it may be attempting to find the class in JDK 11 instead of JDK 8.
> 
> There's a minimal reproduce of this bug at:
> 
> https://github.com/ind1go/tycho.bug.reproduce.1/tree/with-tycho-2.1.0 (the working case)
> vs
> https://github.com/ind1go/tycho.bug.reproduce.1/tree/with-tycho-2.2.0 (the failure case)
> 
> The only thing I've changed is the Tycho version (comparison at https://github.com/ind1go/tycho.bug.reproduce.1/compare/with-tycho-2.1.0...with-tycho-2.2.0).
> 
> Error:
> 
> [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.2.0:compile (default-compile) on project tycho.bug.reproduce.1: Compilation failure: Compilation failure: 
> [ERROR] .../tycho.bug.reproduce.1/src/main/java/dev/bencox/tychobugreproduce1/ClassUsingJAXB.java:[3] 
> [ERROR] 	import javax.xml.bind.JAXBException;
> [ERROR] 	       ^^^^^^^^^^^^^^
> [ERROR] The import javax.xml.bind cannot be resolved
> [ERROR] .../tycho.bug.reproduce.1/src/main/java/dev/bencox/tychobugreproduce1/ClassUsingJAXB.java:[9] 
> [ERROR] 	new JAXBException("Constructing this exception purely so there's a usage of javax.xml.bind in this class.");
> [ERROR] 	    ^^^^^^^^^^^^^
> [ERROR] JAXBException cannot be resolved to a type

Still the case trying with `2.4.0-SNAPSHOT` today.

**Comment by Dufgui** [comment]
I think i have the same problem. Here is a reproducer
https://github.com/Dufgui/tycho-demo/tree/toolchain/itp04-rcp

```
ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.3.0:compile (default-compile) on project example-bundle: Compilation failure: Compilation failure:
[ERROR] C:\Users\gdufour\git\github\eclipse\tycho-demo\itp04-rcp\example-bundle\src\example\bundle\Application.java:[21]
[ERROR]         import javax.xml.bind.annotation.XmlEnum;
[ERROR]                ^^^^^^^^^^^^^^
```

**Comment by laeubi** [comment]
@Dufgui can you create a PR that adds a new [integrationtest](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) for this case derived from the example?

**Comment by Dufgui** [comment]
I try but all my test are working on IT. i will check my product build if I miss some alignment because it seems working.

https://github.com/Dufgui/tycho/tree/571533_breeJava8

here is my branch
https://github.com/eclipse/tycho/pull/188

**Comment by Dufgui** [comment]
it's work on my mac, and the same repo last week on my windows fail. Maybe i miss the path on my windows laptop.
I will check next week (when i go back to work) to check.

**Comment by laeubi** [comment]
@akurtakov I debugged this a bit and get the feeling that this is probably caused due to removed JavaSE1.8 profile, what do you think would it harm to add this back (and simply not manage it any further) for 2.7.x ?

**Comment by akurtakov** [comment]
Where is the JavaSE-1.8 profile removed?

**Comment by laeubi** [comment]
> Where is the JavaSE-1.8 profile removed?

Good question, I though it was part of Tycho but seems be part of `org.eclipse.ogi` I just noticed its not in tcho-core so I assumed we have removed it.

Maybe I'm on the wrong track but if I have Jdk8 should it not resolve+compile without any additional adding for  `javax.` stuff? Sadly the only jdk8 test we have do not use such imports thats why this regression was not discovered..

**Comment by akurtakov** [comment]
I personally don't have time to spend on Java 8 issues, there is enough on my plate with Java 18 which is far more important IMHO.

**Comment by laeubi** [comment]
This issue is a regression of [Bug 561363](https://bugs.eclipse.org/bugs/show_bug.cgi?id=561363).
To restore old behavior one needs to set `<deriveReleaseCompilerArgumentFromTargetLevel>false<deriveReleaseCompilerArgumentFromTargetLevel>`.

**Comment by laeubi** [comment]
I summarized the important parts here: https://github.com/eclipse/tycho/wiki/Compiling-code-for-older-java-releases
