### ISSUE TITLE
Allow to supply debug options to tycho-surefire

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#52]
In complex setups its often necessary to make deeper investigations for class-loading problems.
Currently one can only enable the "showEclipseLog" what enables implicitly -debug but it would be better to have the opportunity to supply an option file.

**Comment by mickaelistria** [comment]
Please add a note to the N&N document. Either in the wiki, or you may want to start a RELEASE_NOTES.md or similar document directly in this repo.

**Comment by laeubi** [comment]
RELEASE_NOTES.md sounds good, do you have any particular format in mind?

**Comment by mickaelistria** [comment]
I usually use that format: https://github.com/eclipse/wildwebdeveloper/blob/master/RELEASE_NOTES.md
But I don't really mind if something else is preferred.
