### ISSUE TITLE
Drop official support for non modular vms

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#522]
We currently have one test that explicitly requires a Java-8 VM in toolchains.

As Java 8 is EOL for a long time and we are about to switch to Java 17 maybe at end of year I think we should drop official support for non modular VMs.

That would mean we

1. remove the test that currently requires Java 8
2. do no longer support bugs/regressions that target Java 8 unless a patch is provided that do not require us to maintain legacy code

**Comment by akurtakov** [comment]
I am all for that. Considering the fact Java 23 (Sep 2023) will be yet another LTS version supporting pre Java 11. We should go by LTS vesions thus support for pre Java 11 should be considered "selfsupport".

**Comment by akurtakov** [comment]
@laeubi Do you remember the exact test requiring Java 8 JVM ? I would like to get rid of it immediately.

**Comment by laeubi** [comment]
I think it is 

https://github.com/eclipse/tycho/blob/master/tycho-its/src/test/java/org/eclipse/tycho/test/compiler/JdtBreeJava8Test.java

we then should also remove toolchain here https://github.com/eclipse/tycho/blob/master/toolchains-gh.xml and java 8 setup here https://github.com/eclipse/tycho/blob/16cb813ac8f13eea42e7ceaa8d80a9fc6965e368/.github/workflows/maven.yml#L26 that will revel if there are more tests requiring java 8

**Comment by laeubi** [comment]
Do you like to add a note to the migration guide that we  do no longer test/maintain VMs < 9

**Comment by akurtakov** [comment]
Done via https://github.com/eclipse/tycho/commit/9ae3f04d1dd76c90244883da6e0585bb5294b8d3
