### ISSUE TITLE
Problem with dependency types and artifactory Maven plugin

### ISSUE THREAD

**Issue by henryju** [eclipse/tycho#539]
Hi,

After upgrading from Tycho 2.3.0 to 2.5.0, my build is failing. We are using the [Artifactory](https://www.jfrog.com/confluence/display/JFROG/Maven+Artifactory+Plugin) plugin to record build informations, and it is supposed to collect all project dependencies.
The collection of dependencies contains things like:
```
       {
          "type" : "jar",
          "sha1" : "a68981b2c9df9c5f90c1f5022a5e15a3d8d70368",
          "md5" : "4f6632b90135f92ad6c1b1e2c25615f8",
          "id" : "p2.eclipse-plugin:org.eclipse.jface:3.23.0.v20210723-1324",
          "scopes" : [ "system" ]
        }, {
          "type" : "lucene-backward-codecs-5.5.5.jar",
          "sha1" : "d1dee5c7676a313758adb30d7b0bd4c69a4cd214",
          "md5" : "c584dcfc21ff1506d61477d5c4fb8f06",
          "id" : "p2.eclipse-plugin:org.eclipse.m2e.maven.indexer:1.18.0.20210618-2246",
          "scopes" : [ "system" ]
        }
```
The `type` attribute of the second dependency looks wrong from a Maven point of view. Are you aware of this problem?

FYI the error on Artifactory side is:
> Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'dependency_type' at row 1

**Comment by mickaelistria** [comment]
I believe the issue is on artifactory side; the type here should be jar, and lucene-backward-codecs-5.5.5 should probably be a classifier (it's an inner jar). The artifactory plugin seems to fail at parsing the depedency string correctly and tries to feed its DB with wrong values.
Anyway, not an issue on Tycho side.

**Comment by henryju** [comment]
OK, so you confirm Tycho is putting arbitrary long values as dependency classifiers?

I found the [place](https://github.com/jfrog/build-info/blob/f6bd5d55a54caf7f824db5c217b8aeae4e3486da/build-info-extractor/src/main/java/org/jfrog/build/extractor/BuildInfoExtractorUtils.java#L271) where the artifactory plugin is building the `type` property, and indeed they are sometimes appending the `classifier`.

And for other people reference, I found this open issue on artifactory side:
https://www.jfrog.com/jira/browse/BI-477

Thanks

**Comment by mickaelistria** [comment]
> OK, so you confirm Tycho is putting arbitrary long values as dependency classifiers?

Yes, in case of nested jars.
