### ISSUE TITLE
Launcher name ignored for Mac app

### ISSUE THREAD

**Issue by vogella** [eclipse/tycho#541]
It is possible to add a launcher name in the product.

![image](https://user-images.githubusercontent.com/139910/150104331-4108dbc8-5de3-4e66-916b-a496bea7399a.png)

This is used under Linux / Windows to name the launcher.

![image](https://user-images.githubusercontent.com/139910/150104589-4e4336f2-f7fc-41f8-8728-0fb3d18d79e7.png)

Under Mac this currently does not work:

![image](https://user-images.githubusercontent.com/139910/150104502-a632e9d3-bb40-4170-b76d-ae5f7b299006.png)

To test clone https://github.com/vogellacompany/eclipse4book/ run build with mvn clean verify and check the result in git\eclipse4book\com.example.e4.product\target\products\com.example.e4.product\macosx\cocoa\x86_64>

**Comment by vogella** [comment]
Sorry for the noise, this can be configured

`<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-p2-director-plugin</artifactId>
				<version>${tycho.version}</version>
				<executions>
				  <execution>
					<id>materialize-products</id>
					<goals>
					  <goal>materialize-products</goal>
					</goals>
				  </execution>
				  <execution>
					<id>archive-products</id>
					<phase>verify</phase>
					<goals>
					  <goal>archive-products</goal>
					</goals>
				  </execution>
				</executions>
				<configuration>
				  <products>
					<product>
					  <id>WebFatClient</id>
					  <rootFolders>
						<macosx>WFC.app</macosx>
					  </rootFolders>
					</product>
				  </products>
				</configuration>
			  </plugin>`

**Comment by laeubi** [comment]
@vogella you might want to write a wiki and/or "show&tell discussion"-

**Comment by mickaelistria** [comment]
Note that a patch to use smarter default according to .product content would be welcome.
