### ISSUE TITLE
tycho-packaging-plugin warns about not being threadsafe

### ISSUE THREAD

**Issue by eNBeWe** [eclipse/tycho#543]
When building a small project with Tycho 2.5.0 in parallel execution mode, I get this warning

````
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following goals are not marked @threadSafe in [target] de.scheidtbachmann.eval.amqp.target:
[WARNING] org.eclipse.tycho:tycho-packaging-plugin:2.5.0:package-target-definition
[WARNING] *****************************************************************
````

It looks like tycho-packaging is marked threadsafe in general, but [PackageTargetDefinitionMojo.java](https://github.com/eclipse/tycho/blob/master/tycho-packaging-plugin/src/main/java/org/eclipse/tycho/packaging/PackageTargetDefinitionMojo.java) is not.

**Comment by laeubi** [comment]
Thanks for reporting this, a code review has not given any evidence that this is not safe to be called concurrently so I will simply add the missing flag. here.

**Comment by laeubi** [comment]
@eNBeWe Tycho 2.6.0 is out and it contains some improvements with parallel build (e.g. parallel compile is enabled again) so you probably want to try that out.
With the tycho build I can speedup the build from 3 minutes to about 20sec on a 16-core machine.
