### ISSUE TITLE
Javadoc error on deploy

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#546]
While deploying tycho to sonartype the following errors are printed to the log:

```
[ERROR] MavenReportException: Error while generating Javadoc: 
Exit code: 1 - error: module org.eclipse.osgi.compatibility.state reads package org.eclipse.core.runtime from both org.eclipse.equinox.common and org.eclipse.equinox.registry
error: module org.eclipse.tycho.embedder.shared reads package org.eclipse.core.runtime from both org.eclipse.equinox.common and org.eclipse.equinox.registry
error: module org.eclipse.equinox.common reads package org.eclipse.core.runtime from both org.eclipse.equinox.registry and org.eclipse.equinox.common
error: module org.eclipse.equinox.registry reads package org.eclipse.core.runtime from both org.eclipse.equinox.common and org.eclipse.equinox.registry
error: the unnamed module reads package org.eclipse.core.runtime from both org.eclipse.equinox.registry and org.eclipse.equinox.common

Command line was: /usr/lib/jvm/java-11-openjdk-amd64/bin/javadoc @options @packages
```

**Comment by mickaelistria** [comment]
what's the command that triggers that? I don't remember we usually publish Maven reports and Javadoc (only mojo doc).

**Comment by cdietrich** [comment]
can you check https://stackoverflow.com/questions/58836862/jdk-11-and-javadoc
it may be at least a workaround

**Comment by laeubi** [comment]
@mickaelistria do you remember if such workarounds where necessary for the 2.5.0 deploy? I think we are using Java 11 for a while so I'm a bit confused.

**Comment by cdietrich** [comment]
is the javadoc missing for all or a specific jar only?

**Comment by laeubi** [comment]
I have updated the instructions here now: https://github.com/eclipse/tycho/commit/000276c3aec019297a448e5a081d8286896b3ae8

**Comment by mickaelistria** [comment]
> do you remember if such workarounds where necessary for the 2.5.0 deploy?

Nope, however I never ever verified the log for Javadoc related messages, I just never cared enough, as long as the published content was correct.

**Comment by cdietrich** [comment]
hmm if there is no javadoc jar created, nexus will complain.
or does it complain about the contents of the jar?

**Comment by mickaelistria** [comment]
> hmm if there is no javadoc jar created, nexus will complain.

Apparently, it doesn't prevent from pushing to OSSRH and then Central, we don't have javadoc in Maven Central for Tycho in 2.5.0: https://repo.maven.apache.org/maven2/org/eclipse/tycho/tycho-maven-plugin/2.5.0/

**Comment by laeubi** [comment]
I'll close this as I adjusted the docs (no errors/warnings anymore) and javadoc seems optional.
