### ISSUE TITLE
Make tycho aviable as a core-extension

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#556]
Currently one has to enable Tycho in the following way:

```
<plugin>
  <groupId>org.eclipse.tycho</groupId>
  <artifactId>tycho-maven-plugin</artifactId>
  <version>${tycho.version}</version>
  <extensions>true</extensions>
</plugin>
```

additionally one can also enable tycho-pomless in `.mvn/extensions.xml`

```
<extension>
  <groupId>org.eclipse.tycho.extras</groupId>
  <artifactId>tycho-pomless</artifactId>
  <version>2.7.0-SNAPSHOT</version>
</extension>
```

With the new feature of mixed reactor builds, and in the light of #551 and #48 it seems more profitable to enable tycho as a core-extension with the following properties:

- it is enough to add in  `.mvn/extensions.xml` to use tycho packaging types and resoloution
```
<extension>
  <groupId>org.eclipse.tycho</groupId>
  <artifactId>tycho-build</artifactId>
  <version>2.7.0-SNAPSHOT</version>
</extension>
```
- tycho-pomless is implicitly included (it is already possible to mix pomless+pom defined projects).

There is currently just one restriction the core-extensions do not allow to provide the version as a system-property, we might want to enhance maven in a way that one can use it that way.

This will allow tycho to participate even more close with maven as before and ee might even make this the only option for 3.0.0 to use tycho as a core extension. Individual mojos for the build itself can still be configured through the pom.xml

**Comment by akurtakov** [comment]
My issue with extension usage is that I never found how to use SNAPSHOT if not previously available in local m2 repo. For that reason in Eclipse Platform we build using 2.7.0-SNAPSHOT but tycho-pomless is set to last release (2.6.0) as there is no way to add plugin repository for extension.

**Comment by mickaelistria** [comment]
Wouldn't it be possible and simpler to have pomless generating pom the other way round, ie adding the tycho extensions to generated pom files instead?

**Comment by laeubi** [comment]
> My issue with extension usage is that I never found how to use SNAPSHOT if not previously available in local m2 repo. For that reason in Eclipse Platform we build using 2.7.0-SNAPSHOT but tycho-pomless is set to last release (2.6.0) as there is no way to add plugin repository for extension.

For testing tycho-snapshots you need to specify this in `settings.xml` this is described here: https://github.com/eclipse/tycho/wiki#getting-tycho-snapshots

> Wouldn't it be possible and simpler to have pomless generating pom the other way round, ie adding the tycho extensions to generated pom files instead?

From my testing the core-extension simply need to have tycho-core as a dependency and it will be pulled in and found its extensions. There are just some issue because we are using some legacy stuff that seems not to be available at this point.

My idea is, that one could simply add the core extension and then start using (e.g. for one ui plugin) the tycho packaging types and for the rest e.g. regular maven packaging types. Actually it should also be possible to use the polyglot-extension to modify the pom.xml but that's a bit tricky as the general contract for ployglot is to not do anything if a pom.xml is there.

**Comment by akurtakov** [comment]
> > My issue with extension usage is that I never found how to use SNAPSHOT if not previously available in local m2 repo. For that reason in Eclipse Platform we build using 2.7.0-SNAPSHOT but tycho-pomless is set to last release (2.6.0) as there is no way to add plugin repository for extension.
> 
> For testing tycho-snapshots you need to specify this in `settings.xml` this is described here: https://github.com/eclipse/tycho/wiki#getting-tycho-snapshots

I know that but unfortunately that's not easy to do in a Jenkins build.

**Comment by laeubi** [comment]
> I know that but unfortunately that's not easy to do in a Jenkins build.

It depends... In my jenkins build I simply do `mvn --settings $WORKSPACE/maven-settings.xml` quite easy :-)
It might becomes more complicated with a manages settings. xml but maven should already support "global-settings" and "user-settings" beside that, it would be possible to just add the snippet there to make Snapshots available on a central place.

**Comment by mickaelistria** [comment]
Now I understand the proposal better and I think it's OK to have the capability to enable Tycho as a core extension; however I find it equally important that it remains also possible to not use it and instead in extension in pom.xml. As long as the later still works, it's probably good to also enable the former.

**Comment by laeubi** [comment]
Both ways should wore, while a core-extension might provide more rich features as we can better hook in. E.g. the "sessionStart" is only called for core-extensions but not for "regular" extensions.

**Comment by laeubi** [comment]
See 

- https://issues.apache.org/jira/browse/MNG-7395
- https://issues.apache.org/jira/browse/MNG-7396

**Comment by laeubi** [comment]
@akurtakov I have checked the platform build and it has the following in its Jenkins setup:
```
mountPath: "/home/jenkins/.m2/settings.xml"
      name: "m2-secret-dir"
      readOnly: true
      subPath: "settings.xml"
```
I think we should simply ask the Eclipse-Infra to add the eclipse-maven repository (with snapshots enabled) to the default maven config maybe in a profile that must be enabled eg with name `eclipse-central` especially if we want to go toward more "maven like". Another option would be to copy that settings.xml as part of a build to a writeable location, add the desired items and pass that settingsfile to the build.

**Comment by laeubi** [comment]
I'll close thsi for now as the code is there and we can imrpove with seperate tickets.
