### ISSUE TITLE
Pomless product build fails in package phase

### ISSUE THREAD

**Issue by vogella** [eclipse/tycho#567]
If I include the package goal in my Maven build, it fails for pomless products. Would be nice if pomless build would support this phase without the need of extra configuration. I think a "good"  default behavior would be to do anything but not to fail the build.

Example: 

Clone https://github.com/vogellacompany/eclipse4book
Run "mvn clean verify package"

Error: 

[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-repository-plugin:2.6.0:assemble-repository (default-assemble-repository) on project com.example.e4.product: Could not assemble p2 repository: Mirroring failed: No repository found at file:/C:/Users/vogella/git/eclipse4book/com.example.e4.product/target/. -> [Help 1]
[ERROR]

**Comment by laeubi** [comment]
The [verify phase includes the package phase](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html) so have you tried a simple `mvn clean verify`?

**Comment by vogella** [comment]
That works. Strange that the package goal fails.

**Comment by laeubi** [comment]
> That works. Strange that the package goal fails.

I think Tycho simply do not support executing the same life-cycle multiple times especially when you already have reached a "higher" phase.

**Comment by vogella** [comment]
Thanks for the help, lets close this bug in this case.
