### ISSUE TITLE
Use the correct scope when injecting dependencies into the maven model

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#581]
As reported in

- https://github.com/eclipse/tycho/pull/569

we currently set a system/dependent scope that could confuse maven tools. We should set an appropriate scope type depending on the compiles/test flags.

**Comment by mickaelistria** [comment]
As far as I know, usage of system scope is/was meant to allow passing/using a specific path as other scopes imply usage of artifacts in Maven repo. However, there are now numerous and more and more frequent cases where we have real Maven artifacts or Maven reactor project coordinates. For those, we could probably try to use a regular Maven scope without too much trouble; that would be a good 1st step.

**Comment by laeubi** [comment]
I have tested with a larger project and see:

- `<scope>provided</scope>` for reactor projects
- `<scope>system</scope>` for items from P2
- `<scope>compile</scope>` for items added as pom.dependencies I add manual to the pom.xml

**Comment by laeubi** [comment]
I played around with this and the problem is that maven obviously tries to resolve the artifacts if the are not system-scoped, so given we consume them from an Update site this results in

`Could not find artifact org.eclipse.osgi:org.eclipse.osgi:jar:3.17.0-SNAPSHOT `

the `-SNAPSHOT` is because of https://github.com/eclipse/tycho/issues/574 in the P2 metadata, anyways we actually don't want maven to fetch it from central if it is actually provided by the target platform.

I'll investigate if we can hook-up into maven somewhere here but maybe we have to fix the scope at the package-phase? That would allow a (maybe somewhat strange) output from dependency:list but a clean pom, even though there is no guarantee everything is deployed at any maven repository...

**Comment by laeubi** [comment]
I have created https://issues.apache.org/jira/browse/MNG-7400

**Comment by laeubi** [comment]
I think there is the problem that we never can never tell if the project was from a repository. So it is hard to decide what is the correct way to do here. I could think about that we add a property `maven.deployed` to the P2 metadata that is only set if it is a maven-target-location item or was consumed from the pom. Then we can also set this property if a release is performed and replace the SNAPSHOT with the build qualifier. That way we would know if the artifact is supposed to be available at any repository at all.

For all other items, we could store them as a p2 artifact and provide a maven-core extension that allows to resolve those against p2-layouted repositories. That way it would be possible to use these in plain maven and inside tycho ... any thoughts?

Otherwise I fear we create more frustration than helping people with `dependency descriptors` and `dependency:list` ...

**Comment by mickaelistria** [comment]
> I think there is the problem that we never can never tell if the project was from a repository.

I think it's possible to tell that. We may either just implement a "lookup" that will look into the various available sources to know where artifact comes from, or just store somewhere in the target platform description the source of where an artifact was resolved from, or maybe other strategies. IMO, the "source repo" is not the kind of info we should inject in metadata because it's not reliable: both Maven and p2 don't guarantee the source from an artifact.
