### ISSUE TITLE
Drop old updatesites

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#594]
Currently we test tycho with ancient update-sites e.g. TYCHO0209tychoRepositoryRoundtrip uses
http://download.eclipse.org/releases/galileo

I think we should for 3.0 throw away any legacy testing stuff and simply use the latest eclipse update URL in any tests. @mickaelistria @akurtakov what do you think?

**Comment by akurtakov** [comment]
All for that. There are many places with such hardcoded entries. Ideally, tests should rely on org.eclipse.tycho.test.util.ResourceUtil which has definitions for few. Unfortunately ECLIPSE_LATEST is one year old there. I'll try to bump this one now.

**Comment by akurtakov** [comment]
Ideally, usages of old repos should be gone and only LATEST should stay. We used to have a few more which were removed in the last few years but lately I can't find enough time for such improvements.
