### ISSUE TITLE
Tycho mirror task mirrors too much if id org.eclipse.platform.sdk is specified

### ISSUE THREAD

**Issue by vogella** [eclipse/tycho#61]
To build RCP appliations with use the org.eclipse.platform.sdk feature in our target platform. But if I try to mirror that with the tycho mirroring task, the whole update site is downloaded as if no restrictions are defined:

Example pom:

If I use only the currently commented org.eclipse.equinox.sdk.feature.group it works as expected. So I guess something is not right with the platform.sdk feature or the Tycho mirroring tasks. As the sdk feature work fine in the target platform and is used in the Eclipse SDK build I assume it is the Tycho mirroring task.

----
<?xml version="1.0" encoding="UTF-8"?>
<project
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
    xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <name>Mirror Update Site</name>

    <prerequisites>
        <maven>3.0</maven>
    </prerequisites>

    <groupId>com.vogella.p2.mirror</groupId>
    <artifactId>mirror</artifactId>
    <version>3.5.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <properties>
        <tycho.version>2.3.0</tycho.version>
        <tycho-extras.version>2.3.0</tycho-extras.version>
    </properties>

    <build>
    <plugins>
        <plugin>
            <groupId>org.eclipse.tycho.extras</groupId>
            <artifactId>tycho-p2-extras-plugin</artifactId>
            <version>${tycho.version}</version>
            <executions>
                <execution>
                    <phase>prepare-package</phase>
                    <goals>
                        <goal>mirror</goal>
                    </goals>
                </execution>
            </executions>

            <configuration>
                <source>
                    
                    <repository>
                        <url>http://download.eclipse.org/releases/latest/</url>
                        <layout>p2</layout>
                        
                    </repository>

                </source>

                
                

                
                

               	<ius>
                   
                    <iu>
                        <id>org.eclipse.platform.sdk</id>
                    </iu>
				</ius>

                

                <destination>${project.build.directory}/repository</destination>
                
                

                <followStrictOnly>false</followStrictOnly>
                
                <includeOptional>true</includeOptional>
                
                <includeNonGreedy>true</includeNonGreedy>

                

                <filter>
                    <osgi.os>linux</osgi.os>
                    <osgi.ws>gtk</osgi.ws>
                    <osgi.arch>x86_64</osgi.arch>
                </filter>

                
                

                <latestVersionOnly>false</latestVersionOnly>
                
                <mirrorMetadataOnly>false</mirrorMetadataOnly>

                

                <compress>true</compress>
                
                <append>true</append>

            </configuration>
        </plugin>
    </plugins>
</build>
</project>
----

**Comment by mickaelistria** [comment]
`org.eclipse.platform.sdk` is not a feature but a product definition. So that does bring a lot of extra deps which ultimately cost time in mirroring. I don't think Tycho has anything to be blamed for here.

**Comment by vogella** [comment]
Thanks Mickael. The Tycho tasks seems to ignore the product meta-data completely as it mirrors all features, for example xtext and buildship even thought they are not part of the product definition. This is different to the target resolution of the target editor.

But using the org.eclipse.e4.rcp.feature.group is a valid approach instead of using the product so this bug report can be closed.

Thanks again.
