### ISSUE TITLE
Classpath computation must take fragments into account

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#626]
Fragments contribute to the classpath of bundles. Currently Tycho do not take this into consideration when computing the classpath/computing requirements.

`org.eclipse.jgit` has a fragment `com.jcraft.jsch` and when using classes from there it works inside PDE but Tycho build fails with

> [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.7.0-SNAPSHOT:compile (default-compile) on project compiler.fragments: Compilation failure: Compilation failure: 
> [ERROR] The import org.eclipse.jgit.transport.JschConfigSessionFactory cannot be resolved
> [ERROR] The import org.eclipse.jgit.transport.OpenSshConfig cannot be resolved

**Comment by mickaelistria** [comment]
Fragments need to be explicitly added to the target-platform for this plugin; otherwise there is concretely no reason that they'd be included by default.

**Comment by laeubi** [comment]
> Fragments need to be explicitly added to the target-platform for this plugin; otherwise there is concretely no reason that they'd be included by default.

That's a limitation of current tycho that soon should vanish ;-)  adding configuration for each bundle is not desired and even not possible with pomless builds.

**Comment by mickaelistria** [comment]
I don't think it's desired to automatically add extra random artifacts to TP by default. It basically breaks the idea that the dependencies must be properly defined.
Is the fragment or its packages here listed as a requirement (even optional)? If it's optional, are optionalDependencies configured to be included by default (in target-platform-configuration/dependency-resolution)? If this flag cannot help here, it then should be another flag to request inclusion of fragments by default.
The dependency between bundle and fragments is the other way round: fragments know their host, host must work without knowing their fragments.

**Comment by laeubi** [comment]
> It basically breaks the idea that the dependencies must be properly defined.

You can't declare a dependency to a fragment, that is how OSGi works. The Fragment defines the dependecy to its host and is attached without the consumer could decide this.

> Is the fragment or its packages here listed as a requirement (even optional)?

You can't list fragments as requirements, the fragment extends a package exported by the host (what is valid in OSGi)

> The dependency between bundle and fragments is the other way round: fragments know their host, host must work without knowing their fragments.

The host works without the fragment but the *compiler* can't compile the code if A uses a class from C (in a package exported by B), depends on B and C is a fragment of B.

This might sound a bit strange but is valid OSGi and as mentioned works in PDE out-of-the box.

PDE use `Eclipse-ExtensibleAPI: true` to determine if it should attach fragments, we can also use that but it must noted that this is pure Eclipse-PDE extension and has no meaning on runtime (and I haven't checked if its in the p2 meta-data).

**Comment by mickaelistria** [comment]
> The host works without the fragment

It wouldn't work when trying to load the classes and if C is not there, would it?
Couldn't the host list an Import-Package?

**Comment by laeubi** [comment]
> > The host works without the fragment
> 
> It wouldn't work when trying to load the classes and if C is not there, would it?

Yes, but that might or might not be a problem e.g. a fragment could add optional content, a bundle might look-up classes by name and simply do some kind of default action when not found and so on...

> Couldn't the host list an Import-Package?

As mentioned here the packe *is* imported (org.eclipse.jgit.transport) but the host and the fragment both contains the package, thus there can't be anything *additionally* imported.

**Comment by mickaelistria** [comment]
I don't get it. org.eclipse.jgit.transport is a split package?

**Comment by laeubi** [comment]
> I don't get it. org.eclipse.jgit.transport is a split package?

No a split-package is one exported from more than one *bundle* (thus split between two providers). Here the fragment *attaches* additional classes in an existing package exported by the host (thus everything comes from one provider = the host).

A fragment simply got *merged* with its host as if both where packed in the *same* bundle.

**Comment by mickaelistria** [comment]
I think I know understand it. What an ugly pattern to use... I'm just afraid that if we want to have this working by default, then we get more fragments added to depedency resolution by default while they're not desired in most cases. But if you can find a solution that's preventing from this risk, then it's all good to include it.

**Comment by laeubi** [comment]
Actually these fragments should only be on the compile class-path. That makes it a bit tricky but that way they won't drain into other parts of tycho (e.g. included in an update-site).

**Comment by opcoach** [comment]
I found another use case today with a multiple plaform build (linux, macOS, windows), with a code containing a FontData instance. 

- On macOS, FontData is defined in the macosX fragment and contains a public String name and has a getName returning name
- On windows, FontData has only a getName method computing the name.

In my code, there is a line with an access to fd.name.  

**Eclipse 2022-03, jdk17 behaviour :** 
On macOS, in Eclipse, it compiles correctly. It takes the right class from the fragment. 
On Windows, in Eclipse, there is an error message... this is correct as the windows fragment provides only the getName method. 

**Tycho behavior** 
If we build with tycho using the 3 different environments the compilation is ok !  And there is no error for the windows generation. It seems that another FontData class definition has been used for the compilation... (may be the macOS one)...

**Comment by laeubi** [comment]
@opcoach this depends on the order of fragment attachments an as it is only compiled once for all three platforms Tycho currently can't detect the issue.

**Comment by poul-m** [comment]
Hi.
**host.bundle** 
export my.pack

**fragment.bundle** 
--lib
  --my.jar
    --my.pack
      --MyClass.class
export my.pack, 
my.jar included in classpath

**user.bundle**
depends host.bundle
new MyClass();

It works inside PDE but Tycho build fails for classes from jars inside fragments (my.pack.MyClass)
