### ISSUE TITLE
Tycho project hangs when importing it into eclipse

### ISSUE THREAD

**Issue by parttimenerd** [eclipse/tycho#631]
I tried to import the tycho maven projects into my eclipse (2021-12) on JDK 17, but the importing gets into an endless loop.

**Comment by mickaelistria** [comment]
It's not a Tycho project, but an Eclipse (m2e) one. Let's close it here.

**Comment by parttimenerd** [comment]
Thanks, I did not this

**Comment by laeubi** [comment]
This is most probably https://github.com/eclipse-m2e/m2e-core/issues/123

**Comment by parttimenerd** [comment]
Oh, ok. Maybe the wrong place to ask: But is there another way to get Tycho working in eclipse (I looked at the installer version but this does not conform to the installer of the latest eclipse version)?

**Comment by laeubi** [comment]
You should download eclipse for RCP/rap, then import everything but not the itests!

Then it works (for me) to cancel all builds, locate the tycho-core project do Maven>Update project then Maven>Update All projects

I always compile the stuff then on the commandline `mvn clean install -T1C -DskipTests` and run builds to debug with `mvnDebug ...` using a remote debugging session.

**Comment by parttimenerd** [comment]
What are the `itests`?

**Comment by laeubi** [comment]
https://github.com/eclipse/tycho/tree/master/tycho-its also some projects have nested integration-test-projects so just make sure you always only import the "root" project.

**Comment by parttimenerd** [comment]
You mean that I should only import the root maven project (from the `TYCHO_FOLDER/pom.xml`)? Not importing `tycho-its`does not help.
