### ISSUE TITLE
Tycho 2.7.0 Release

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#648]
# Releasing Tycho

This describes the steps to perform a release of Tycho:

- [x] Make sure all fixed issues and merged PRs have the correct milestone for this release, to finding PRs without milestone you can use the following filter `is:pr is:merged no:milestone` issues without milestone can be found with `is:issue no:milestone is:closed`
- [x] Prepare the [release notes](https://github.com/eclipse/tycho/blob/master/RELEASE_NOTES.md) which should provide a quick overview of new features and bug fixes
- [x] Create branch `tycho-N.M.x` (e.g. `tycho-2.4.x`) for upcoming release and push it to remote; this branch should remain frozen until the release, only major fixes for regressions could be merged in before release. Work can still happen regularly on the `master` branch.
- [x] Create release record on https://projects.eclipse.org/projects/technology.tycho projects.eclipse.org, link the N&N to https://github.com/eclipse/tycho/blob/[branch-name]/RELEASE_NOTES.md release notes]
- [x] Update the Jenkinsfile on the `tycho-N.M.x` and adjust the `stage('Deploy Snapshot')` to reference the new branch in the when conditional.
- [x] Update versions on `master `to future release with `mvn org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=<NEXT_VERSION>-SNAPSHOT` and push to remote
- [x] Announce the intent to release and request feedback about snapshots on the [GitHub discussions](https://github.com/eclipse/tycho/discussions):
```
Subject: Tycho <VERSION> release

We plan to release Tycho <VERSION> next week. For details of new features and bugfixes, see [release notes](https://github.com/eclipse/tycho/blob/tycho-x.y.z/RELEASE_NOTES.md).
Please help by testing the SNAPSHOTS build. To use it, change your tycho version to <VERSION>-SNAPSHOT and add the following snippet to your pom.


<pluginRepositories>
    <pluginRepository>
      <id>tycho-snapshots</id>
      <url>https://repo.eclipse.org/content/repositories/tycho-snapshots/</url>
    </pluginRepository>
</pluginRepositories>

We plan to promote this release in one week unless major regressions are found.

Regards,
Tycho team
```

... Wait until review date (usually a week later)...

- [x] make sure all tags are fetched with `git fetch -t`
- [x] Make sure you have everything setup (GPG installed!) for deploying to the Nexus OSS repository, see https://central.sonatype.org/pages/ossrh-guide.html guide
- [x] Add your credentials for server `sonatype-nexus-staging` in `~/.m2/settings.xml`
```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
   <!-- ... -->
   <servers>
    <server>
      <id>sonatype-nexus-staging</id>
      <username>mickael.istria</username>
      <password>securePassword</password> <!-- use `mvn --encrypt-password` to not store plain text -->
    </server>
    <!-- ... -->
   </servers>
</settings>
</source>
```

- [x] `git fetch eclipse tycho-N.M.x && git checkout FETCH_HEAD` to get the branch to be released
- [x] Update version to remove `-SNAPSHOT` with `mvn org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=<VERSION>`
- [x] Update versions in tycho-demo folder
- [x] `git add * && git commit` version change
- [x] Deploy to nexus staging repository (check that the correct pgp key is used and published to the key-servers eg. https://keys.openpgp.org/): 
```
mvn clean deploy -Prelease -DskipTests -Dsource=8 -DjdetectJavaApiLink=false \
     -DforgeReleaseId=sonatype-nexus-staging \
     -DforgeReleaseUrl=https://oss.sonatype.org/service/local/staging/deploy/maven2/ \
     -Dgpg.keyname=<your e-mail of pgpg key>
```
- In the meantime...
    - [x] `git tag tycho-<TYCHO_VERSION>`
    - [x] Find out who contributed to the release:
```
git log --pretty=format:%an tycho-<previousVersion>..tycho-<newVersion> | sort | uniq
git log --grep="Also-[bB]y:" tycho-<previousVersion>..tycho-<newVersion> | grep -i also-by | sed -e 's/.*Also-[bB]y:\s*\(.*\)/\1/' | sort | uniq
```

   - [ ] Prepare (in a text editor) announcement, thanking the contributors:
```
Subject: Tycho <VERSION> is released

Tycho <VERSION> has been released and is available from Maven Central repository.

🆕 https://github.com/eclipse/tycho/blob/master/RELEASE_NOTES.md#xyz
🏷️ https://github.com/eclipse/tycho/tree/tycho-x.y.z
👔 https://projects.eclipse.org/projects/technology.tycho/releases/x.y.z
🙏 contributors who contributed patches for this release:
<contributors>
and thanks and to everyone who helped us with testing the staged version.

Regards,

```
- [x] close the staging repository on https://oss.sonatype.org/#stagingRepositories 
- [x] Wait until all checks are done (this takes some time, see Activity tab). If all checks have passed, release the repository.
- [ ] Wait for artifacts to be available on Maven central.
- [x] push tag `git push origin tycho-<TYCHO_VERSION>`
- Documentation
  - [x] Generate site docs using `mvn install site site:stage -DskipTests` and check the result from `target/staging` seems viable.
  - [x] Prepare documentation on the webite, using git repo https://git.eclipse.org/c/www.eclipse.org/tycho.git/ : copy the local site docs folders `target/staging/sitedocs` to the existing `sitedocs` folder and then submit as Gerrit review (don't merge yet)
- Announce the release
  - [x] Send prepared announce of the release to [GitHub discussions](https://github.com/eclipse/tycho/discussions) and tycho-dev@eclipse.org,
  - [ ] Optionally, announce on other medias (Twitter)
- [ ] Create, push and merge patch changing the bootstrap Tycho version for Tycho build (eg https://git.eclipse.org/r/c/tycho/org.eclipse.tycho/+/174964 )

**Comment by laeubi** [comment]
@mickaelistria @akurtakov Eclipse complains here https://projects.eclipse.org/projects/technology.tycho/releases/2.7.0 that one week is a too short period for planing a release.

**Comment by laeubi** [comment]
- [ ] @akurtakov The license check still complains https://github.com/eclipse/tycho/actions/runs/1836228431 can we still do a release?

**Comment by laeubi** [comment]
@akurtakov can you create the release announcement?

**Comment by akurtakov** [comment]
It's better to give Monday for licensecheck just to be on the safe side. Let's create the announcement on Tuesday to give some time for infra to be fixed.

**Comment by laeubi** [comment]
> It's better to give Monday for licensecheck just to be on the safe side. Let's create the announcement on Tuesday to give some time for infra to be fixed.

I think we can still announce the intend so people can start testing?

**Comment by akurtakov** [comment]
Yes, licensecheck was fine last night when I last looked at it. What should I announce as target date?

**Comment by laeubi** [comment]
See https://github.com/eclipse/tycho/issues/648#issuecomment-1037915163 I'm not sure if one week is enough (from EF rules) but we can also just say Monday next week...?

**Comment by akurtakov** [comment]
https://github.com/eclipse/tycho/discussions/497 I decided to not go with exact date.

**Comment by mickaelistria** [comment]
@laeubi you can ignore the 1-week notice. the EDP has changed over that last months so a release review isn't required anymore.

**Comment by mbooth101** [comment]
I submitted this PR https://github.com/eclipse/tycho/pull/654 against master, is there a chance to get it into 2.7.0? Should I push a separate PR against the 2.7.0 branch?

**Comment by laeubi** [comment]
If everything is fine I could cherry pick this to the 2.7. as well.

**Comment by mickaelistria** [comment]
@laeubi OK, please do so.

**Comment by laeubi** [comment]
As PGP is one of the key-points in the 2.7.0 release I'd like to integrate #660 and then we probably could release on Monday?

**Comment by mickaelistria** [comment]
@laeubi OK, so please merge #660 ASAP so we can see Platform builds using the patch and give the opportunity to spot major breakages and to verify it fixes the initial issue with Platform Test p2 repo.

**Comment by laeubi** [comment]
@mickaelistria I'm done but Eclipse CI Infra is stuck again, this is really annoying an greatly slows down development. As Red Hat is a strategic member of eclipse would it be possible to check if it is possible to give some more more priority on having a reliable CI build?

**Comment by laeubi** [comment]
I got the build running by killing all other jobs now : https://ci.eclipse.org/tycho/job/tycho-github/job/tycho-2.7.x/

Overview still do not display the status of build-nodes....

**Comment by laeubi** [comment]
All builds are stuck again... that really slows down devlopment / releasing...

**Comment by laeubi** [comment]
List of Tycho 2.6.0 contributors:
```
Alexander Kurtakov
Arthur Brugière
Christian Dietrich
Christoph Läubrich
Fred G
Hannes Wellmann
Jakub Stroleny
Joe Shannon
Lorenzo Bettini
Marc Miltenberger
Marco Lehmann-Mörz
Mat Booth
Michael Keppler
Mickael Istria
Sebastian Ratz
Vaclav Hala
```

**Comment by laeubi** [comment]
> Wait for artifacts to be available on Maven central.

I have closed the staging repo and deployed it but it does not yet appears on central how long does it usually takes? Minutes? Hours?

**Comment by mickaelistria** [comment]
> I can see it here: https://repo1.maven.org/maven2/org/eclipse/tycho/tycho-core/2.7.0/ is that enough or do we require it to be visible in the maven search?

It's enough.
I don't know how frequently is Maven search refreshed, but as soon as it's in the Maven Central repo, it can be generally adopted and we can consider it as released.
