### ISSUE TITLE
Build with a nested target platform fails to "bootstrap"

### ISSUE THREAD

**Issue by habbit-baggins** [eclipse/tycho#665]
Trying to build the [nested target platform example project](https://github.com/eclipse/tycho/tree/master/tycho-its/projects/target.references) **in a "pristine" environment** fails with an exception when trying to validate the classpath of the `test.bundle` project.

    [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.7.0-SNAPSHOT:validate-classpath (default-validate-classpath) on project test.bundle: Execution default-validate-classpath of goal org.eclipse.tycho:tycho-compiler-plugin:2.7.0-SNAPSHOT:validate-classpath failed: bundleLocation not found: null -> [Help 1]

If the project has ever been built _without_ the nested target platforms (e.g. by using `base.target` as the actual TP in the project), then the problem does not appear, even when using the nested TP.

## Environment
I was originally testing this in the context of the 2.7 release (#651) but the same problem happens also in master and in the current release 2.6.0 (although earlier in the build).

## Steps to reproduce
1. Have the Tycho repo downloaded e.g. at path $X
2. Launch the build in a pristine environment, in my case in a new container with a "clean" Maven 3.8 on JDK11:
    ```bash
    $ podman run --rm -it -v "$X/tycho-its/projects/target.references:/mnt" maven:3.8-jdk-11 mvn -f /mnt clean verify
    ```

The build fails with the mentioned exception, while it should succeed instead.

**Comment by habbit-baggins** [comment]
I have attached a full log of the build (note that it is quite long because Maven was also downloading Tycho): [out.log](https://github.com/eclipse/tycho/files/8102141/out.log).

The issue is relevant because a "pristine" Maven environment is not that uncommon in CI environments, so this problem could cause builds to succeed in the developer's machine and then fail on CI.

**Comment by laeubi** [comment]
I'm not sure, do you mean it fails with an empty maven local repository and succeeds on second build?

**Comment by laeubi** [comment]
@habbit-baggins I could reproduce this with an empty mvn local repository now. The problem is that we don't add the artifact repository of the referenced target to the overall target content, I'm currently preparing a fix.

**Comment by laeubi** [comment]
Cherry picked to 2.7.0 as well.

**Comment by habbit-baggins** [comment]
I confirm that it works in a pristine Maven environment both in Linux and in Windows, thanks a lot!

**Comment by laeubi** [comment]
Thanks for verification. If you like this feature the consider say [thank you](https://github.com/sponsors/laeubi?frequency=one-time) or even [sponsor further development ](https://github.com/sponsors/laeubi?frequency=recurring) of tycho.
