### ISSUE TITLE
Improve mirror handling of tycho

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#677]
Currently I have cleared my m2 repository and that leads to a lot of download. Sadly there is one mirror currently not responsive and even though it has timed out for some artifacts already it is still queried.

We should maintain a list of "bad mirrors" and don't ask them again in the same build...

**Comment by mickaelistria** [comment]
Maben mirrors or p2 mirrors? If the later then change would probably better fit in p2's ...RepositoryManager.

**Comment by laeubi** [comment]
P2 mirrors ....

**Comment by laeubi** [comment]
> If the later then change would probably better fit in p2's ...RepositoryManager.

In fact the handling seems to be in MirrorRequest of P2 and as we already have P2MirrorDisablingArtifactRepositoryManager I though it might not be desirable to change P2 itself... as far as I know @merks also has implemented optimization outside of P2 so I until now though it might be a better choice to do this in tycho.

But of course one could also think about some kind of downloadmanager that even ask multiple mirrors for big files to get a faster loading...

**Comment by merks** [comment]
It would probably be good if I could find the time to move the "better mirror selector" logic back into p2.  If I did that, would Tycho just reuse it?

**Comment by laeubi** [comment]
I hope so :+1: at least currently I just can see that it simply iterates all mirrors regardless of their quality and that's a bit bad. Maybe one could even make a pluggable "MirrorStrategy" so it is possible to choose another one just in case but I think there is not much need to adjust here if it works fine OutOfTheBox....

**Comment by merks** [comment]
Could I suggest that you open an enhancement request in p2 so that this issue is tracked and there is a clear reason why improvements would be useful, i.e., would be reused by Tycho.

**Comment by laeubi** [comment]
Here we go: https://bugs.eclipse.org/bugs/show_bug.cgi?id=578887 I must confess that I'm not very familiar *how* P2 actually handles this, it seems to be a combination of `MirrorSelector` and `MirrorRequest` so the report is rather vague...

**Comment by laeubi** [comment]
We have a soloution ow for tycho and an enhancement request for P2 so I thinkt his could be closed.
