### ISSUE TITLE
Move tycho-source-feature-plugin its to tycho-its

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#681]
tycho-source-feature-plugin uses groovy and the maven-invoker-plugin to execute integration test. This is a bit alien on how we do integration testing with tycho and should be migrated to better integrate with the current layout.

This also leads to the situation that currently those tests are not executed as part of the "integrationtest check" of GH actions.

**Comment by akurtakov** [comment]
I'm all for unifying codewise. But having tests whereh they belong is very beneficial during development as one can run only the tests/it tests for the given module. 
GH actions should be changed to run all IT tests like it's done on Jenkins instead.

**Comment by akurtakov** [comment]
Thinking more about it tycho-source-feature-plugin should be removed in 2.0 so maybe putting the tests in tycho-source-plugin or maybe they are there already?

**Comment by laeubi** [comment]
I can run the test without any problem separately e.g.

`mvn clean verify -Pits -Dtest=org.eclipse.tycho.test.sourceBundle.TychoSourcePluginTest`

but I always never run them in the individual plugins, beside that they are a pita to debug and having groovy scripts do not help much if we do not use groovy at other places. This has bugged me several times in the past.

**Comment by laeubi** [comment]
> Thinking more about it tycho-source-feature-plugin should be removed in 2.0 so maybe putting the tests in tycho-source-plugin or maybe they are there already?

That's another reason to move them. Actually these integration tests are hard to run separately and one has to build tycho before anyways.
