### ISSUE TITLE
Tycho-Sitedocs seems to block the build

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#688]
I recently often see the following scenario:

- The master build has run and triggered a new site-doc build with `wait=true`
- The [sitedoc build ](https://ci.eclipse.org/tycho/job/tycho-sitedocs/) waits "forever" for a new build executor
- Everything else is stuck

I have now[ changed the Jenkinsfile to not wait ](https://github.com/eclipse/tycho/commit/4be044b5017d96b4e5bbc0e2430de8a69173024c)for the sitedoc build maybe this helps already, but wondering if we not simply could integrate the [sitedocs](https://ci.eclipse.org/tycho/job/tycho-sitedocs/) in the regular jenkins buildfile instead of trigger a new job?

@mickaelistria or @akurtakov can you take a look at this?

**Comment by akurtakov** [comment]
Integrating sounds good to me. IIRC this is remnant from the past as this used to be separate job from before I joined the project.

**Comment by laeubi** [comment]
Will a `mvn -V clean install site site:stage` be enough to add to the jenkinsfile?
The build also seems to archive `target/staging/**` but are anyone really looking at this artifact?

**Comment by akurtakov** [comment]
Having it as separate stage would be nice as it be a bit more clear that it's site generation and not compile/test failure. Last I looked at these artifacts was probably 2 years ago when some maven-site-plugin update broke generation so probably not that important.
