### ISSUE TITLE
Builds are triggered twice if waiting for the nex build executor

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#689]
Currently each change at master triggers a new build of all PR. If there are not enough executors, and one pushes another commit to the master, a new job is started, waiting for a new executor and so on, this can easily stack up.

Maybe we could simply disable concurrent builds like described here: https://stackoverflow.com/a/41516843/9503281

@mickaelistria and @akurtakov what do you think?

**Comment by akurtakov** [comment]
with gerrit jenkins plugin there was option to build only latest version and cancel/discard previous ones if new one is pushed. Isn't smth like that available for github?

**Comment by laeubi** [comment]
Depending on Jenkins version, disablecuncurrent builds could abort previous runs:

https://issues.jenkins.io/browse/JENKINS-43353

`options { disableConcurrentBuilds abortPrevious: true } `

**Comment by akurtakov** [comment]
That sounds really promising and worth trying.
