### ISSUE TITLE
Failed to resolve dependencies with Tycho 2.7.0 for custom repositories

### ISSUE THREAD

**Issue by vogella** [eclipse/tycho#697]
With Tycho 2.7.0 we see errors for resolving artifacts from internal Nexus servers.

[ERROR] Failed to execute goal on project a: Could not resolve dependencies for project a: Could not find artifact b:4.20.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

It should go to the configured URL.
```
<repositories>
			<repository>
				<id>nexus</id>
				<url>https://nexus.client.de/repository/secure-public</url>
			</repository>
		</repositories>
```
@HannesWell IIRC you implemented this. Does it still work for you with Tycho 2.7.0?

**Comment by laeubi** [comment]
I think you should provide a bit more context here:

- Is this a snippet from a target, a pom or a settings.xml?
- are there any additional errors/warning in the log
- ...

**Comment by vogella** [comment]
> Is this a snippet from a target, a pom or a settings.xml?

Target. 
> are there any additional errors/warning in the log

No.

We reverted this build to Tycho 2.6.0 and had to delete the content of .mvn/repository after going back to 2.6.0. 
Unfortunately I'm not aware of other open Nexus server which I could use to build a standalone example which does not require internal network access. Is there any?

**Comment by vogella** [comment]
~/git/tycho/tycho-its/projects/target.mavenMulti seems to contains a IT test but does currently not work as it pointsto               <tycho-version>2.5.0-SNAPSHOT</tycho-version>

But if I change it to 2.7.0 it still works, looks to me that is downloads part from Maven central and parts from the other repo. 

````
[WARNING] No explicit target runtime environment configuration. Build is platform dependent.
[DEBUG] [main] Computing preliminary target platform for MavenProject: org.eclipse.tycho.itests:test.bundle:0.0.1-SNAPSHOT @ C:\Users\vogella\git\tycho\tycho-its\projects\target.mavenRepos\test.bundle\pom.xml
[DEBUG] Using execution environment 'JavaSE-17' configured in Currently running profile, newer than configured profile (JavaSE-11) from [Bundle-RequiredExecutionEnvironment (unique entry)]
[DEBUG] Currently running JRE matches source level for JavaSE-17; current JRE system packages are used.
[DEBUG] Adding target definition file "file:/C:/Users/vogella/git/tycho/tycho-its/projects/target.mavenRepos/test.bundle/../test.target"
[INFO] Resolving target definition file:/C:/Users/vogella/git/tycho/tycho-its/projects/target.mavenRepos/test.bundle/../test.target for environments=[win32/win32/x86_64], include source mode=honor, execution environment=StandardEEResolutionHints [executionEnvironment=OSGi profile 'JavaSE-17' { source level: 17, target level: 17}], remote p2 repository options=org.eclipse.tycho.p2.remote.RemoteAgent@66d2885c...
[INFO] Resolving MavenDependencyRoots = [GroupId = edu.ucar, ArtifactId = cdm, Version = 5.0.0, ArtifactType = jar, IncludeDependencyScope = ], IncludeDependencyScope = [compile], MissingManifestStrategy = GENERATE, IncludeSource = true...
[DEBUG] Resolve edu.ucar:cdm:jar:5.0.0...
[DEBUG] Resolving artifact edu.ucar:cdm:jar:5.0.0 from [central (https://repo.maven.apache.org/maven2, default, releases), unidata-all (https://artifacts.unidata.ucar.edu/repository/unidata-all/, default, releases+snapshots)]
[DEBUG] Using transporter WagonTransporter with priority -1.0 for https://repo.maven.apache.org/maven2
[DEBUG] Using connector BasicRepositoryConnector with priority 0.0 for https://repo.maven.apache.org/maven2
Downloading from central: https://repo.maven.apache.org/maven2/edu/ucar/cdm/5.0.0/cdm-5.0.0.jar
[DEBUG] Writing tracking file C:\Users\vogella\.m2\repository\edu\ucar\cdm\5.0.0\cdm-5.0.0.jar.lastUpdated
[DEBUG] Using transporter WagonTransporter with priority -1.0 for https://artifacts.unidata.ucar.edu/repository/unidata-all/
[DEBUG] Using connector BasicRepositoryConnector with priority 0.0 for https://artifacts.unidata.ucar.edu/repository/unidata-all/
Downloading from unidata-all: https://artifacts.unidata.ucar.edu/repository/unidata-all/edu/ucar/cdm/5.0.0/cdm-5.0.0.jar
````

Do we also have an example in which the lib is not available on Maven central?


Another question, what is the policy of the tycho version for the IT projects? Update on demand to the latest Tycho version?

**Comment by laeubi** [comment]
> but does currently not work as it pointsto 2.5.0-SNAPSHOT

You can run any IT with any version of tycho specifying `-Dtycho-version=<...>`

> looks to me that is downloads part from Maven central and parts from the other repo.

That's how it is supposed to work

> Do we also have an example in which the lib is not available on Maven central?

'Downloading from unidata-all' in your output indicates that it is not available from central.

> Another question, what is the policy of the tycho version for the IT projects? Update on demand to the latest Tycho version?

I generally update them whenever I touch the test to use a new feature. They get always injected the version of the current build if run inside the CI with a system option (see above.)

**Comment by laeubi** [comment]
@vogella any updates here?

**Comment by vogella** [comment]
Sorry, cannot replicate anymore, as I do not have access anymore to an inhouse Maven repo. Closing

**Comment by pzi-dsa** [comment]
I'd like to reopen this issue, as I've recently run into the same problem in our product, after testing out the 2.7.1 snapshot (after migrating from 2.6.0).

```
[ERROR] Failed to execute goal on project example: Could not resolve dependencies for project example.group:example:eclipse-plugin:2.1.1-SNAPSHOT: lib.group:lib.artifact:jar:7.40.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```

The plugin is contributed via the target platform definition and download at the beginning of the reactor build:

```
[INFO] Resolving MavenDependencyRoots = [GroupId = lib.group, ArtifactId = lib.artifact, Version = 7.40.0, ArtifactType = jar, IncludeDependencyScope = ], IncludeDependencyScope = [compile], MissingManifestStrategy = GENERATE, IncludeSource = true...
Downloading from central: https://repo.maven.apache.org/maven2/lib/group/lib.artifact/7.40.0/artifact-7.40.0.jar
Downloading from nexus-3pps: https://<internal nexus>/lib/group/lib.artifact/7.40.0/artifact-7.40.0.jar
Downloaded from nexus-3pps: https://<internal nexus>/lib/group/lib.artifact/7.40.0/artifact-7.40.0.jar (631 kB at 1.2 MB/s)
Downloading from central: https://repo.maven.apache.org/maven2/lib/group/lib.artifact/7.40.0/artifact-7.40.0-sources.jar
```

When building the plugin, it then tries to fetch the pom from Maven Central only:

```
Downloading from central: https://repo.maven.apache.org/maven2/lib/group/lib.artifact/7.40.0/artifact-7.40.0.pom
[WARNING] The POM for lib.group:lib.artifact:jar:7.40.0 is missing, no dependency information available
```

Weirdly enough, the issue only appeared after building a release version of the dependent plugin (i.e.  building the project with version 7.40.0-SNAPSHOT works).

Building the dependency locally (via mvn install) also causes the project to work with both 7.40.0 and 7.40.0-SNAPSHOT.

I'll have a look today whether I can come up with a working example that doesn't rely on our internal repository.

**Comment by laeubi** [comment]
The current workaround is to add the repositories mentioned in the target also to the pom of the maven build. I think we need to rethink and possibly fix this in 3.0.0 with #585 for 2.7.x I don't see an easy solution for this.

**Comment by laeubi** [comment]
@vogella @pzi-dsa this should soon apear in the snapshot so please verify if it solves the issue now.

**Comment by pzi-dsa** [comment]
I ran our build with the latest snapshot and the problem doesn't show up anymore.
Thank you for looking into this!
