### ISSUE TITLE
Change of coordinates for p2 artifacts cause issues downstream (eg in dash license tool)

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/tycho#700]
Moving from 2.6 to 2.7 cause that the output of `mvn dependency:list` slightly differs.
In 2.6 `p2.eclipse-plugin:org.w3c.dom.smil:jar:1.0.1.v200903091627:system:/home/mistria/.m2/repository/p2/osgi/bundle/org.w3c.dom.smil/1.0.1.v200903091627/org.w3c.dom.smil-1.0.1.v200903091627.jar`
In 2.7 `p2.eclipse.plugin:org.w3c.dom.smil:eclipse-plugin:1.0.1.v200903091627:system:/home/mistria/.m2/repository/p2/osgi/bundle/org.w3c.dom.smil/1.0.1.v200903091627/org.w3c.dom.smil-1.0.1.v200903091627.jar`
A dash got replaced with a dot.
Some tools downstream (eg dash-license tool) are relying on such names or strings and are now broken with newer Tycho.

**Comment by laeubi** [comment]
BTW as you see from the system path, it actually should even be `p2.bundle:org.w3c.dom.smil`so this might change in the future as well to align with maven repository layout.

If `dash-license tool` really likes to ignore(?) these items it should check for

- artifact type is any of the tycho packaging types
- group id starts with "p2."
- scope is system

to be compatible for 2.7.0, for 3.0.0 it might even be possible to actually resolve those (see #590).

**Comment by laeubi** [comment]
Beside that, I can only encourage everyone bind tightly to tycho internals to participate in testing 
 [tycho snapshot](https://github.com/eclipse/tycho/wiki#getting-tycho-snapshots) builds at least when we announce releases.

**Comment by laeubi** [comment]
These internals are nothing one really should depend on as tycho itself does not depends on this.
The only thing one might consider "public exposed" is the prefix `p2.` that is defined here:
https://github.com/eclipse/tycho/blob/2b9bc212bf7dd43ca558b0f343d15f216d9b82d3/tycho-bundles/org.eclipse.tycho.embedder.shared/src/main/java/org/eclipse/tycho/TychoConstants.java#L16
but any suffix is subject to change.
