### ISSUE TITLE
Create a p2-mavenplugin

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#711]
Currently we use P2 embedded inside OSGi, but the tycho-build extension already have made some efforts to use P2 standalone in a maven context.

We should further follow this path to make P2 more accessible to tycho, probably even maven some of the mojos that do not really interact with tycho so the plugin could be used independent from tycho, e.g. for the [dash-licenses](https://github.com/eclipse/dash-licenses) (@waynebeaton ) tool.

Because of that, I'd like to propose the name "p2-maven-plugin" as we already have "tycho-maven-plugin" the scope of this should be:

1. resolve solutions for a given set of IUs
2. read/write/update repositories
3. provide tasks similar to the "ant-based-tasks" (e.g. mirror application and alike)

In the end this will save us a lot of headaches and probably we could finally even drop the embedded OSGi runtime. A side effect (but not a goal) might be that we can drop the ant-tasks completely from platform decreasing the maintenance effort there so p2 can focus on its core functionality.

**Comment by mickaelistria** [comment]
Do you have a concrete use story in mind that could benefit from this?
I think the main point is to allow p2 to work without OSGi, so it's mostly development in p2, isn't it?

**Comment by laeubi** [comment]
e.g. https://github.com/eclipse/tycho/issues/590 would benefit from it as well. the p2 repository layout is not really "tycho" but would make is possible to use p2-update sites in a regular maven build as well. So that is my first "milestone" here.
Even more I'd like to have target platform resolution happen in the maven reactor instead of the OSGi runtime so we do not pas back-and-forth so much stuff and it could be performed as part of the tycho-build extension.

**Comment by mickaelistria** [comment]
> would make is possible to use p2-update sites in a regular maven build as well. 

OK. that's an interesting story, however I don't think a dedicated mojo is necessary right now to achieve that. But it's all up to you ;)

**Comment by laeubi** [comment]
We have the p2-plugin and use t already on some places so I think this could be closed, further work can use more dedicated tickets.
