### ISSUE TITLE
JUnit Classpath container does not seem to work

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/tycho#716]
Hi

In version [](https://github.com/eclipse/tycho/blob/master/RELEASE_NOTES.md#support-resolving-of-junit-classpath-container)2.4.0
[Support resolving of JUnit Classpath Container](https://bugs.eclipse.org/bugs/show_bug.cgi?id=572602) we have this new support. There's also an example here https://github.com/eclipse/tycho/tree/master/tycho-its/projects/compiler.junitcontainer/junit4-in-bundle but can it be it works only for `eclipse-plugin` packaging type? At least in my case it does not work for `eclipse-test-plugin`: with Tycho 2.7.0 I have compilation errors of the shape

```
Error:  Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.7.0:compile (default-compile) on project edelta.lib.tests: Compilation failure: Compilation failure: 
Error:  /home/runner/work/edelta/edelta/edelta.parent/edelta.lib.tests/src/edelta/lib/learning/tests/EdeltaModelMigratorTest.java:[43] 
Error:  	import org.junit.Before;
Error:  	       ^^^^^^^^^^^^^^^^
Error:  Access restriction: The type 'Before' is not API (restriction on classpath entry '/home/runner/.m2/repository/p2/osgi/bundle/org.junit/4.13.2.v20211018-1956/org.junit-4.13.2.v20211018-1956.jar')
```

**Comment by laeubi** [comment]
At least it is only supported for `eclipse-plugin` packaging but *might* work for other packaging types but I won't test/support this use-case.

**Comment by LorenzoBettini** [comment]
> Is there any specific reason you want to use` eclipse-test-plugin` packaging (beside: we always did it that way)?

besides we always did it that way, no ;)

jokes apart: are you deprecating `eclipse-test-plugin`?

in any case, maybe it might be useful to stress in the release notes that it is meant only for `eclipse-plugin`?

**Comment by laeubi** [comment]
> jokes apart: are you deprecating `eclipse-test-plugin`?

For me personally `eclipse-test-plugin` is of no use anymore and I wont invest any further work in supporting it but I know there are other people really keen of keeping it, but probably for tycho 4.0 who knows :-)

> in any case, maybe it might be useful to stress in the release notes that it is meant only for `eclipse-plugin`?

Sure, improvements in the documentation are always welcome! The JUnit container just becomes important with the support for plain tests in `eclipse-plugin` so it makes sense to mention this in the documentation as well.

If you like you can of course also contribute a wiki-page describing the new way of tests as it seems your already experimenting with that so having a user-socumentation would greatly be appreciated!

**Comment by mickaelistria** [comment]
> jokes apart: are you deprecating eclipse-test-plugin?

No, eclipse-test-pluing are to remain, and for a long time.
They're actually very helpful in cases one wants to run tests on other environments (Platform and other RCPs I'm aware of do that often: install/build a test against a different TP to run it against distinct environment/RCP). I personally am convinced that the Eclipse approach of test bundles/fragments, although it has flaws, is fundamentally more correct that the Maven approach as it "treats tests as a 1st-class citizen", which is often a cause or symptom (?) of more sustainable project development.
eclipse-test-plugin allows to better embrace this workflow than the Maven way with tests just being sidekicks artifacts.

But the new "test source" workflows have their merits.

The issue at the moment is that both can hardly be mixed together in the same bundle/module.

**Comment by laeubi** [comment]
@mickaelistria you can do the same with the `eclipse-plugin`packaging its just a matter of not including any code in that project itself. Anyways I have no real plans to deprecate nor advocate against that packaging-type :-)

**Comment by laeubi** [comment]
@LorenzoBettini do you think here is anything to be done?

**Comment by LorenzoBettini** [comment]
@laeubi I proposed a change to the RELEASE notes, as discussed here.

**Comment by laeubi** [comment]
Thanks for the PR, I have merged this now.
