### ISSUE TITLE
Performance regression in 2.7.0 / 3.0.0 (maybe caused by #626?)

### ISSUE THREAD

**Issue by sratz** [eclipse/tycho#719]
I've noticed that in 2.7.0 the dependency and classpath resolution phases are slower than in 2.6.0.

For a non-parallelized build this adds about 7-10 minutes to our build time (727 artifacts):
2.6.0: ~ 25 minutes
2.7.0: ~ 35 minutes

I am currently trying to get some more concrete numbers with hot caches and populated ~/.m2/repository.

First bisecting show that this could be caused by #626.

**Comment by sratz** [comment]
So I did some testing using 2.7.0 vs. 2.7.0 + reverted 774e135844b20b46ef71b6de4463126aa0f6da9b from #626:
Same machine, first a build using `mvn clean verify` to warm up, then a 2nd run using
`mvn clean verify -o` to force offline mode and work on caches only:

Here are the numbers from the 2nd runs:
```
                              2.7.0       2.7.1-SNAPSHOT (2.7.0 + reverted 774e135844b20b46ef71b6de4463126aa0f6da9b)
dependency resolution phase   00:08:17    00:03:33
build phase (clean verify)    00:19:25    00:18:58
--
total                         00:27:42    00:22:31
```

**Comment by laeubi** [comment]
Can you set a breakpoints to see how many units are queried? I think we might use some caching because most of the units should be the same for all projects.

**Comment by laeubi** [comment]
@sratz can you check if that reduces the execution times in your case?

https://github.com/eclipse/tycho/pull/721

Beside that, you should really try to enable parallel execution, as we have enabled parallel compile again in Tycho 2.7 this should reduce the build times significantly if building a lot of modules.

**Comment by sratz** [comment]
Already better with #721, but it still bottlenecks in the loop over addMatchingFragments().

I've added another improvement on top of your change in #724.

With that, he performance is almost on par again with 2.6.0.
