### ISSUE TITLE
JGit packaging build fails with Tycho 2.7.0

### ISSUE THREAD

**Issue by msohn** [eclipse/tycho#723]
I tried updating the jgit packaging build to Tycho 2.7.0 [1] and this failed with the following error [2] 

`org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:target-platform-configuration:2.7.0:target-platform (default-target-platform) on project org.eclipse.jgit.repository: Execution default-target-platform of goal org.eclipse.tycho:target-platform-configuration:2.7.0:target-platform failed: Not an artifact file: null`

The same build succeeds using Tycho 2.5.0 and 2.6.0.
Any idea what might be wrong?
Build instructions for jgit are documented here [3].
Maven debug log is in [mvn.log]

[1] https://git.eclipse.org/r/c/jgit/jgit/+/191530
[2] https://ci.eclipse.org/jgit/job/stable/job/jgit.gerrit-pipeline.java11/1051/console
[3] https://wiki.eclipse.org/EGit/Contributor_Guide#Maven_Buil
[mvn.log](https://github.com/eclipse/tycho/files/8196858/mvn.log)

**Comment by laeubi** [comment]
@msohn thanks for the report I'll try to take a look at this.

**Comment by Bananeweizen** [comment]
egit/jgit still use the old-school attach-artifact mechanism to dynamically add a target file to the build. I suspect that something around resolving that variable has been broken in 2.7. However, attach-artifact is not necessary anymore. The target of a Tycho build can be specified directly as a file (without referring to a maven artifact) since some versions. My IDE is still trying to get up to date for egit sources, but I might be able to submit a PR later.

**Comment by msohn** [comment]
I moved this change to master and rebased it onto Michael's change
https://git.eclipse.org/r/c/jgit/jgit/+/191544
directly referring to the target platform file, though this is still failing with the error

`[ERROR] Failed to execute goal org.eclipse.tycho:target-platform-configuration:2.7.0:target-platform (default-target-platform) on project org.eclipse.jgit.repository: Execution default-target-platform of goal org.eclipse.tycho:target-platform-configuration:2.7.0:target-platform failed: Not an artifact file: null`

**Comment by msohn** [comment]
I merged Michael's patches using modern style of using target platforms

Looking forward to your fix.

**Comment by laeubi** [comment]
Can you try out the current [tycho snapshot](https://github.com/eclipse/tycho/wiki#getting-tycho-snapshots) build if it fixes your issue?

**Comment by msohn** [comment]
I can confirm that the jgit build succeeds with the current tycho 3.0.0-SNAPSHOT

**Comment by mickaelistria** [comment]
Doing a release is a major disturbance and slows down a lot of other development. The other question would be: can you deal with 3.0.0-SNAPSHOT until it's released as 3.0.0 ?

**Comment by laeubi** [comment]
@msohn in generall it really helps if projects using tycho help with testing of upcoming versions, so If you can either always use the snapshot or at least have a weekly build that uses a snapshot that would be great to discover such issues before the release.

**Comment by laeubi** [comment]
@msohn I wonder if you probably use `<exclusion>` in your build somewhere? As i think that it might be that if a transitive dependency is excluded we end up with this `null` problem ...

**Comment by msohn** [comment]
yes we do in this module: https://git.eclipse.org/r/plugins/gitiles/jgit/jgit/+/refs/heads/master/org.eclipse.jgit.junit.ssh/pom.xml#54
