### ISSUE TITLE
Project compiler settings cannot be overridden when running Maven

### ISSUE THREAD

**Issue by sithmein** [eclipse/tycho#74]
It is not possible to override the Eclipse project compiler settings on the command line using `<compilerArgs>` in the _tycho-compiler-plugin_ configuration. According to the Eclipse batch compiler documentation this is  possible, e.g. by passing

```
<configuration>
  <arg>-err:-nullAnnot</arg>
</configuration>
```

However, the complete command line generated by Tycho looks as follows:

> [DEBUG] JDT compiler args: [-err:-nullAnnot, -warn:-nullAnnot, -properties,  /.../.settings/org.eclipse.jdt.core.prefs, -s, ...] 

The manually provided compiler arguments are always put at the front of the argument list. However, according to the batch compiler documentation the *last* argument determines the effective settings which would be the project configuration. This means it's impossible to override it on the command line.

**Comment by mickaelistria** [comment]
Thanks!
