### ISSUE TITLE
Implement a caching P2 transport

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#797]
Currently certain access to files (mostly p2.index) are not cached making tycho quite slow. Another issue are non-existing index files if p2 tries to query to find out where the meta-data resides.

**Comment by laeubi** [comment]
It seems this has increased the buildtime of the unit test a lot, I'll take a look if this is just because of now we have cold-caches or if there are other issues, probably we need to disable the transport by default (currently enabled) until it is clear what causing this, lets wait for the next build ...

**Comment by laeubi** [comment]
Build times are back to normal

**Comment by laeubi** [comment]
@jcompagner do you like to try it out? https://github.com/eclipse/tycho/blob/master/RELEASE_NOTES.md#improved-p2-transport-for-more-efficiently-http-cache-handling-and-improved-offline-mode

If you set `-Dtycho.p2.transport.min-cache-minutes=40320` Tycho should only contact update-site servers once a month, so if your targets are really static this should improve build times and save you from server outages.

**Comment by jcompagner** [comment]
i will have a look (but busy in the comming 2 weeks with our own release, then i am back on master where this kind of stuff is in)
i guess i need then the nighly build right (to get 3.0)
what if i don't set that -Dtycho.p2.transport.min-cache-minutes=40320 ? what is the default value?

**Comment by laeubi** [comment]
default is one hour.
