### ISSUE TITLE
Support resolving of non-project IUs in P2Resolver

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#82]
Currently the P2Resolver API do read the root units from the project, in some circumstances it is desirable to perform a resolution of units based on a different set.

Use-case is for example I have a mojo and like to fetch a unit from a target-platform including its dependencies.

Currently one can archive this indirectly by creating a dummy project, and use the deprecated P2Resolver.collectProjectDependencies method.

**Comment by mickaelistria** [comment]
Unless this Mojo is part of Tycho itself, I don't think Tycho should include logic it doesn't use itself. Tycho has never had as goals to be a provider of APIs (that would basically prevent any further refactoring from happening without extra care, and would then result in a reduced ability to deliver new features quickly), and I think we should avoid getting into that business.
If you think this needs to be discussed, please bring this to the mailing-list.

**Comment by laeubi** [comment]
This will be required to support "additional.bundles" in AbstractTestMojo

**Comment by laeubi** [comment]
#33 and  #77 / #63 might be related.
