### ISSUE TITLE
tycho-source-plugin:feature-source is not a drop-in for tycho-source-feature-plugin:source-feature

### ISSUE THREAD

**Issue by sewe** [eclipse/tycho#85]
This issue has originally been reported on the [`tycho-user` mailing list](https://www.eclipse.org/lists/tycho-user/msg09055.html).

Replacing `tycho-source-feature-plugin:source-feature` with `tycho-source-plugin:feature-source` (versions 2.1.0, 2.2.0 and 2.3.0) fails the build during dependency resolution, although this should be a drop-in replacement [according to the release notes](https://wiki.eclipse.org/Tycho/Release_Notes/2.2#Tycho_Source_Feature_Generation_moved_from_tycho_extras_to_tycho_core):

```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: update-site raw:0.0.1.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):0.0.1-SNAPSHOT
[ERROR]   Missing requirement: org.example.feature.source.feature.group 0.0.1.202104201129 requires 'org.eclipse.equinox.p2.iu; org.example.feature.feature.group [0.0.1.202104201129,0.0.1.202104201129]' but it could not be found
[ERROR]   Cannot satisfy dependency: update-site raw:0.0.1.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):0.0.1-SNAPSHOT depends on: org.eclipse.equinox.p2.iu; org.example.feature.source.feature.group 0.0.0
```

Will create a reproducer project and report back here.

**Comment by sewe** [comment]
> Will create a reproducer project and report back here.

Created https://github.com/sewe/tycho-issue-85-reproducer.

To reproduce:

```bash
export TYCHO_VERSION=2.3.0 # Also happens with 2.1.0, 2.2.0
git clone https://github.com/sewe/tycho-issue-85-reproducer.git
cd tycho-issue-85-reproducer
mvn clean verify -DtychoVersion=$TYCHO_VERSION # Fails with tycho-source-plugin:feature-source
git checkout HEAD^
mvn clean verify -DtychoVersion=$TYCHO_VERSION # Succeeds with tycho-source-feature-plugin:source-feature
```

Hope this helps.

**Comment by laeubi** [comment]
@sewe it seems currently tycho requires that the execution id is named 'feature-source'

```
<executions>
	<execution>
		<id>feature-source</id>
		<goals>
			<goal>feature-source</goal>
		</goals>
	</execution>
</executions>
```

I will check if this could be relaxed...

**Comment by sewe** [comment]
Good catch. Not in a million years I would have thought this to be the cause.

> I will check if this could be relaxed...

Well, it was possible before (my execution ID was always `attach-source`), so hopefully that will be possible again. :crossed_fingers:

**Comment by laeubi** [comment]
> Well, it was possible before (my execution ID was always `attach-source`), so hopefully that will be possible again. crossed_fingers

Finally this was fixed by @HannesWell and should show up shortly in the snapshots ([when this job is done](https://ci.eclipse.org/tycho/job/tycho-github/job/tycho-2.7.x/32/)), I also cherry picked this for 2.7.2 so please help testing the release: https://github.com/eclipse/tycho/discussions/903

**Comment by fredg02** [comment]
> Good catch. Not in a million years I would have thought this to be the cause.

Thanks to @sewe for reporting the same problem that I had, to @laeubi for pointing to the workaround/solution and to @HannesWell for the fix.

I'm glad this did not turn into a https://xkcd.com/979/ situation. :)
