### ISSUE TITLE
SLF4J issue with Tycho 2.7.1

### ISSUE THREAD

**Issue by dhendriks** [eclipse/tycho#874]
We at Eclipse ESCET [just upgraded](https://gitlab.eclipse.org/eclipse/escet/escet/-/issues/343) to Tycho 2.7.1, and found the following regression in our output:

```diff
 [timestamp] [INFO] Scanning for projects...
 [timestamp] [INFO] Resolving target definition file:/home/jenkins/agent/workspace/buildXXX/releng/org.eclipse.escet.releng.target/org.eclipse.escet.releng.target.target for environments=[linux/gtk/x86_64, win32/win32/x86_64, macosx/cocoa/x86_64], include source mode=honor, execution environment=org.eclipse.tycho.p2.target.ee.CustomEEResolutionHints@1c506e6, remote p2 repository options=org.eclipse.tycho.p2.remote.RemoteAgent@addressXXX...
+[timestamp] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
+[timestamp] SLF4J: Defaulting to no-operation (NOP) logger implementation
+[timestamp] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
 [timestamp] [INFO] Resolving dependencies of MavenProject: org.eclipse.escet:org.eclipse.escet.chi.codegen:0.6.0-SNAPSHOT @ /home/jenkins/agent/workspace/buildXXX/chi/org.eclipse.escet.chi.codegen/.polyglot.META-INF
```

I can't find any real negative impact of this, besides the 3 `SLF4J` lines. However, it doesn't look nice, and makes me wonder what code is trying to use SLF4J here, and what potential logging output could now be missed?

**Comment by laeubi** [comment]
I can't see this with an arbitrary build, could you provide an example project that shows the issue?

**Comment by Phillipus** [comment]
I see the same thing with our RCP build when I use Tycho 2.7.1:

https://github.com/archimatetool/archi/blob/master/pom.xml
https://github.com/archimatetool/archi/blob/master/com.archimatetool.editor.product/pom.xml

**Comment by laeubi** [comment]
Please try out the current [tycho snapshot](https://github.com/eclipse/tycho/wiki#getting-tycho-snapshots) build if that fixes your issue if not provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue.

**Comment by Phillipus** [comment]
Hi Christoph, the log message does not show when using `3.0.0-SNAPSHOT`. Thanks.

**Comment by laeubi** [comment]
Thanks for verification, if anyone wants this for 2.7.2 we would need a PR.

**Comment by lppedd** [comment]
Is this issue still valid for 2.7.4 @Phillipus?

**Comment by Phillipus** [comment]
> Is this issue still valid for 2.7.4

Yes, it is. But I don't believe it was intended to be changed in 2.7.x as per the comment above.

**Comment by laeubi** [comment]
If anyone wants this for 2.7.5 we would need a PR against the 2.7.x branch.

**Comment by lppedd** [comment]
Btw, are we really sure this has to be done on the Tycho side?
SLF4J documentation states:

> If you are responsible for packaging an application and do not care about logging, then placing slf4j-nop.jar on the class path of your application will get rid of this warning message. Note that embedded components such as libraries or frameworks should not declare a dependency on any SLF4J providers but only depend on slf4j-api. When a library declares a compile-time dependency on a SLF4J provider, it imposes that provider on the end-user, thus negating SLF4J's purpose.
