### ISSUE TITLE
Running tests with Tycho 3.0.0 gives java.lang.NoClassDefFoundError in org.eclipse.tycho.surefire.osgibooter

### ISSUE THREAD

**Issue by ktatavarthi** [eclipse/tycho#878]
As reported in https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/7#issuecomment-1094916243 the jdt.ui LeakTestSuite tests fail with the below error

```
java.lang.NoClassDefFoundError: Lorg/apache/maven/surefire/spi/MasterProcessChannelProcessorFactory;
	at org.eclipse.jdt.ui.tests.leaks.JavaLeakTest.testTextEditorCloseOneOfTwo(JavaLeakTest.java:99)
Caused by: java.lang.ClassNotFoundException: org.apache.maven.surefire.spi.MasterProcessChannelProcessorFactory cannot be found by org.eclipse.tycho.surefire.osgibooter_3.0.0.202204100956
	at org.eclipse.jdt.ui.tests.leaks.JavaLeakTest.testTextEditorCloseOneOfTwo(JavaLeakTest.java:99)
```

Running with previous version 2.7.0 , no error is reported and tests pass.

**Comment by joeshannon** [comment]
Tycho recently updated Surefire to 3.0.0-M6 (from 2.22.2). It looks like `MasterProcessChannelProcessorFactory` is in the `surefire-extensions-spi` module which was new for 3.0.0-M5. It probably needs to be added to Tycho's surefire booter.

**Comment by laeubi** [comment]
Can you provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue? We have over 250 tests but it seems this particular case is not covered currently.

**Comment by mickaelistria** [comment]
I'll try to look at it since it's a regression frm surefire upgrade

**Comment by mickaelistria** [comment]
This should now be fixed. Please try newer Tycho snapshots.
