### ISSUE TITLE
Compiler doesn't copy resource files when build.properties defines nested jars

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse/tycho#90]
When we tried building platform with tycho 2.4.0 we are getting the comparator errors indicating those files are not getting packaged. Log is attached [buildtimeComparatorUnanticipated.log.txt](https://github.com/eclipse/tycho/files/6355746/buildtimeComparatorUnanticipated.log.txt)

I have modified [platform aggregator job](https://ci.eclipse.org/platform/job/eclipse-aggregator-master/) to use tycho 2.4.0-SNAPSHOT. This can be used for testing. 

Please look out for similar errors as given below in the console log. These warnings should not appear. 
[INFO] --- tycho-p2-plugin:2.4.0-SNAPSHOT:p2-metadata-default (default-p2-metadata-default) @ org.eclipse.ant.core ---
[WARNING] MavenProject: org.eclipse.ant:org.eclipse.ant.core:3.6.0-SNAPSHOT @ /home/jenkins/agent/workspace/eclipse-aggregator-master/eclipse.platform/ant/org.eclipse.ant.core/pom.xml: baseline and build artifacts have same version but different contents
   no-classifier: different
      org/eclipse/ant/internal/core/InternalCoreAntMessages.properties: present in baseline only

[INFO] MavenProject: org.eclipse.ant:org.eclipse.ant.core:3.6.0-SNAPSHOT @ /home/jenkins/agent/workspace/eclipse-aggregator-master/eclipse.platform/ant/org.eclipse.ant.core/pom.xml
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

**Comment by mickaelistria** [comment]
This regression happens for files that have nested jars in their build.properties. I managed to write a test that reproduces it with 2.4.0-SNAPSHOT, but not with 2.3.0 (as expected); I'm going to merge it because this is a blocker issue, so it's fine to get all builds failing until it's resolved.
I'll then investigate to find out which commit does cause this issue.

**Comment by sravanlakkimsetti** [comment]
> This regression happens for files that have nested jars in their build.properties. I managed to write a test that reproduces it with 2.4.0-SNAPSHOT, but not with 2.3.0 (as expected); I'm going to merge it because this is a blocker issue, so it's fine to get all builds failing until it's resolved.
> I'll then investigate to find out which commit does cause this issue.

Please let me know when a new snapshot has been published. I would like to try again.

**Comment by mickaelistria** [comment]
This regression seems to come from 92d274ba64a61b3e7da5bad370837213f96c2895 (`git checkout 92d274ba64a61b3e7da5bad370837213f96c2895 && git cherry-pick 76da2a4f2b7770496cbb23d50eeb0b739c4152a7 && mvn clean install -pl tycho-compiler-plugin/` reproduces the test failure).
@laeubi can you please have a look at that? I suspect it's just a minor code issue (like `copyResources()` not invoked in some cases)

**Comment by laeubi** [comment]
I'll take a look.

**Comment by mickaelistria** [comment]
Build that includes fix in ongoing at https://ci.eclipse.org/tycho/job/tycho-github/job/master/23/ , please try again Tycho 2.4.0-SNAPSHOT upon completion to get the fix (depending on CI performance, this can be between 1 and 6 hours apparently...)

**Comment by sravanlakkimsetti** [comment]
Though the build failed for doc update I am able trigger a new build with latest snapshot. I can confirm the problem is resolved
