### ISSUE TITLE
Use better defaults for archive-products products

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#913]
I almost always configure the `archive-products` in the following way
```
 <execution>
	<id>archive-products</id>
	<goals>
		<goal>archive-products</goal>
	</goals>
	<phase>install</phase>
	<configuration>
		<formats>
			<linux>tar.gz</linux>
			<macosx>tar.gz</macosx>
		</formats>
	</configuration>
</execution>
```

This is for two reasons:

1. Actually `tar.gz` is more common for *nix based systems
2. Zip do not preserves the execution flags reliable

I think we should change this defaults for 3.x to require less configuration for the common case

**Comment by laeubi** [comment]
What are the defaults currently? I can't remember configuring anything special here and get good defaults from the product file (e.g. no root folder at all?)

**Comment by HannesWell** [comment]
Just checked that and the default is indeed no-root folder. IIRC the Eclipse zip/tar.gz-files also come with a `eclipse` root folder.
The the default `archiveFileName` seems to be the product's `uid`.

Maybe it's a matter of personal/company-preferences. At least we always use that for our products and maybe other's would like that too. Having a root folder can be helpfull in case one blindly extracts a zip/tar.gz. And if one specifies a launcher-name I would see that as part of the branding and want to use that name for the zip as well.

But it's just a suggestion and maybe others have a different opinion. :)

**Comment by laeubi** [comment]
I think this is a bit individual and I don't think we gain much as there are too many naming schemes, but having a zip that can't be executed right now seems strange as the execute flag is lost and I almost always seeing `tar.gz` being used for *nix systems and `zip` for windows.

**Comment by HannesWell** [comment]
> I think this is a bit individual and I don't think we gain much as there are too many naming schemes, but having a zip that can't be executed right now seems strange as the execute flag is lost and I almost always seeing `tar.gz` being used for *nix systems and `zip` for windows.

Acknowledge.
For projects that build multiple products it would be useful to be able to use 'pattern' for those variables so that it can be specified in the root pom and applied for each individual product.
I think this could be achieved if the `product-id` and the `product-launcher-name` (if specified) were injected as Maven-properties when a product-project is build. One could then simply specify something like the following at root level.

```
<plugin>
	<groupId>org.eclipse.tycho</groupId>
	<artifactId>tycho-p2-director-plugin</artifactId>
	<configuration>
		<products>
			<product>
				<id>${tycho.product.uid}</id>
				<archiveFileName>${tycho.product.launcher.name}-${unqualifiedVersion}.${buildQualifier}</archiveFileName>
				<rootFolder>${tycho.product.launcher.name}</rootFolder>
			</product>
		</products>
	</configuration>
</plugin>
```

**Comment by guw** [comment]
@HannesWell Should `${tycho.product.launcher.name}` be mapping to the `<launcher name="foo">` attribute value within the `.product` file? I tried it and it looks like it's mapping to the product uid.
