### ISSUE TITLE
Tycho 3.0: tycho-packaging-plugin:3.0.0-SNAPSHOT:validate-version failed: Project org.eclipse.emf:org.eclipse.emf.mwe.activities:eclipse-plugin:1.7.0-SNAPSHOT does not have an expanded version

### ISSUE THREAD

**Issue by cdietrich** [eclipse/tycho#937]
23:45:23  [INFO] [jenkins-event-spy] Generated /home/jenkins/agent/workspace/mwe2_cd_tycho30@tmp/withMaven50cd7ad3/maven-spy-20220505-034429-1668131431923031255609.log
23:45:23  [ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:3.0.0-SNAPSHOT:validate-version (default-validate-version) on project org.eclipse.emf.mwe.activities: Execution default-validate-version of goal org.eclipse.tycho:tycho-packaging-plugin:3.0.0-SNAPSHOT:validate-version failed: Project org.eclipse.emf:org.eclipse.emf.mwe.activities:eclipse-plugin:1.7.0-SNAPSHOT does not have an expanded version -> [Help 1]

https://ci.eclipse.org/mwe/job/mwe2/job/cd_tycho30/83/console

what does tycho want to tell here

thought 
https://github.com/eclipse/tycho/commit/b9c5d7304593a05795787a9f072300324bb6c066
was an opt in feature

**Comment by cdietrich** [comment]
yesterday it still was working 
https://ci.eclipse.org/mwe/job/mwe2/job/cd_tycho30/82/consoleFull

**Comment by laeubi** [comment]
Best is to run with -X and post the stacktrace then we might see better where it error out. The version check was slightly adjusted.

**Comment by cdietrich** [comment]
https://ci.eclipse.org/mwe/job/mwe2/job/cd_tycho30/84/console

**Comment by cdietrich** [comment]
we have this in pom
```
<tycho-qualifier>yyyyMMdd-HHmm</tycho-qualifier>
....
				<plugin>
					<groupId>org.eclipse.tycho</groupId>
					<artifactId>tycho-packaging-plugin</artifactId>
					<version>${tycho-version}</version>
					<configuration>
						<format>${tycho-qualifier}</format>
						<strictVersions>true</strictVersions>
					</configuration>
				</plugin>
```

**Comment by laeubi** [comment]
Do you think you can provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue? It seems this case is then not currently covered as all test passed.

**Comment by cdietrich** [comment]
maybe next week

**Comment by cdietrich** [comment]
(my first try to create a it for it of course(tm) does not lead to a failing test)
is there a easy way to run the test locally iteratively?

**Comment by laeubi** [comment]
For maven it is important that the test ends with "Test" to be automatically discovered, if you want to run it standalone you can cd into the tycho-its folder and calls `mvn clean verify -Pits -Dtest=full.class.name`
