### ISSUE TITLE
Signature issues with Tycho 2.4.0

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/tycho#94]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=573159 .

**Comment by mickaelistria** [comment]
@laeubi This is a consequence of https://github.com/eclipse/tycho/commit/d9a58240820776f11feb0a8dbaabfaaa00a4619d . This seems to highlight that the approach of tests in module but without having this module signed is not really usable together with signed bundles. Again, it seems to me that generating a test fragment, that would be signed, would work better.
The bundle in question is oddly configured though. i'll try to fix the bundle first.

**Comment by laeubi** [comment]
So the new feature executes now tests that previously where ignored? I don't see how test fragment could hlep here as they do not apply here anyways.

**Comment by mickaelistria** [comment]
> So the new feature executes now tests that previously where ignored?

Yes, because the module was an `eclipse-plugin` and had the `test` attribute set in .classpath. But I think this is worth fixing this module first and I submitted https://git.eclipse.org/r/c/equinox/rt.equinox.p2/+/179816

> I don't see how test fragment could hlep here as they do not apply here anyways.

It wouldn't help to fix this particular issue; it's just a reminder that tests that are not part of the same classloader as main artifact can fail in different ways because of classloading or class access restrictions; and that is something that works just fine with test-fragments. It's just IMO 1 more reason to have the story of the "tests in bundles" support to generate an explicit test fragment as it allows more reliable class access.

**Comment by laeubi** [comment]
The it should either be a test-plugin or distinguish between Uinit and integration test with a proper filter. The "test-fragment" discussion really does not relate here and won't have changed anything.
Beside that I still don't see any benefit in supporting this, the whole classloader/acessrestriction thing simply has no meaning when defining a test class and only complicates the whole thing with no gain. In fact it even does not make sense for plain unit-test as there is no "OSGI-Runtime".

**Comment by laeubi** [comment]
As the referenced bug is closed I think we can close this too, please reopen if you see any issue.
