### ISSUE TITLE
Rename org.eclipse.tycho.plugins.p2.director.DirectorMojo

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#949]
It has a TODO 

https://github.com/eclipse/tycho/blob/8dda882a3d77ecba8601f9bba5d9a2ecbc4f6695/tycho-p2/tycho-p2-director-plugin/src/main/java/org/eclipse/tycho/plugins/p2/director/DirectorMojo.java#L39-L41

Should we rename it with Tycho 3.x?

**Comment by mickaelistria** [comment]
Why not?

**Comment by laeubi** [comment]
The original issue is rather old and I can't see why there was a demand to rename it:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=348586

so I don't know if it is the rename that bring something (make it more clear?) or we just should remove the todo...
