### ISSUE TITLE
Tcho 2.7.3 org.eclipse.tycho:tycho-compiler-plugin:2.7.3:validate-classpath failed: bundleLocation not found: null

### ISSUE THREAD

**Issue by cdietrich** [eclipse/tycho#954]
after updating from 2.7.2 to 2.7.3 i am getting 

```
10:34:57  [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.7.3:validate-classpath (default-validate-classpath) on project org.eclipse.xtend.ide: Execution default-validate-classpath of goal org.eclipse.tycho:tycho-compiler-plugin:2.7.3:validate-classpath failed: bundleLocation not found: null -> [Help 1]
10:34:57  [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.7.3:validate-classpath (default-validate-classpath) on project org.eclipse.xtend.m2e: Execution default-validate-classpath of goal org.eclipse.tycho:tycho-compiler-plugin:2.7.3:validate-classpath failed: bundleLocation not found: null -> [Help 1]
10:34:57  [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.7.3:validate-classpath (default-validate-classpath) on project org.eclipse.xtend.standalone: Execution default-validate-classpath of goal org.eclipse.tycho:tycho-compiler-plugin:2.7.3:validate-classpath failed: bundleLocation not found: null -> [Help 1]
```
with no further message. what does tycho want to tell me

https://ci.eclipse.org/xtext/job/xtext-xtend/job/cd_tycho273/2/console

**Comment by cdietrich** [comment]
is it possible that if download fails this is no longer properly logged?

**Comment by laeubi** [comment]
> looks like the upstream build finished and overwrote the repo in parallel

Sharing the m2e repository with concurrent builds is not supported neither by standard maven nor tycho at the moment, you should either make sure not two builds access the same repo at the same time or better have dedicated repository per build and maybe use artifact promotion instead.

**Comment by laeubi** [comment]
You could try to use `mvn -U` to force tycho checking if remotes changed, I has only seen this error when there are corrupted files in the (maven) repo.

**Comment by cdietrich** [comment]
jenkins always starts fresh. and the build already runs with `--update-snapshots`
restarting the build solved, but i wonder why it does not tell the artifact which is bad.

**Comment by laeubi** [comment]
> but i wonder why it does not tell the artifact which is bad.

Might be an area where improvements are necessary, I think this error is something one would not expect to see so it might be that the error message is poor. If you like you can open a PR to improve the message, maybe a `-X` would already reveal more info here.
