### ISSUE TITLE
Generated OSGi bundles symbolic names seem official by default

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/tycho#956]
Using TM4E, which use Tycho 3.0.0, using Maven dependencies in a .target with "generate" for `missingManifest`, the generated bundle seems to have a relatively official name. As a result, we have a `org.jcodings` in the repo while it's actually 1 build of jcodings from TM4E. As discussed initially, such case can be confusing for upstream and downstream community. I would expect that such a wrapped bundle would be named `org.eclipse.tm4e.org.jcodings` or `wrapped.org.jcodings` by default.

**Comment by laeubi** [comment]
> I would expect that such a wrapped bundle would be named `org.eclipse.tm4e.org.jcodings`

This is only if you consume them from the pom.

>  `wrapped.org.jcodings` by default.

This is the default if the jar is not already a bundle but projects can choose to configure this differently as they like.

**Comment by mickaelistria** [comment]
OK, my bad. Good everything is working as expected then; too bad I didn't realize the (not so good) header customization in TM4E's target earlier.

**Comment by laeubi** [comment]
The best would be to ask the `jcodings` to add OSGi headers in the first place, you can even give them the BND instructions used in the target as a blueprint for a start in publishing OSGI headers with bnd-maven plugin.

As soon as there are official headers then any instructions are ignored anyways :-)
