### ISSUE TITLE
Tycho Packaging plugin is packaging .gitignore

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse/tycho#966]
We are seeing the following log in platform build https://download.eclipse.org/eclipse/downloads/drops4/I20220518-1100/buildlogs/comparatorlogs/buildtimeComparatorUnanticipated.log.txt

In my opinion .gitignore should not get packaged in to plugin jar. Something went wrong here

Notifications:
@akurtakov @laeubi

**Comment by akurtakov** [comment]
This is caused by https://github.com/eclipse/tycho/commit/34f66701823c26f7dd9eb3694c7c7ee62f3c8ead , more specifically https://github.com/codehaus-plexus/plexus-utils/pull/174 . I'll have a fix shortly.

**Comment by sravanlakkimsetti** [comment]
Still there is a problem
Comparator differences from current build
	/home/jenkins/agent/workspace/I-build-4.24/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/siteDir/eclipse/downloads/drops4/I20220520-0600
compared to reference repo at 
	https://download.eclipse.org/eclipse/updates/4.24-I-builds

1.  eclipse.jdt.ui/org.eclipse.jdt.ui.tests
   no-classifier: different
      org/eclipse/jdt/ui/tests/chkpii/.gitignore: not present in baseline
   classifier-sources: not present in baseline
    The main artifact has been replaced with the baseline version.
    The following attached artifacts are not present in the baseline and have been removed: [sources]

**Comment by sravanlakkimsetti** [comment]
Still an issue 
```
Comparator differences from current build
	/home/jenkins/agent/workspace/I-build-4.24/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/siteDir/eclipse/downloads/drops4/I20220523-0320
compared to reference repo at 
	https://download.eclipse.org/eclipse/updates/4.24-I-builds

1.  eclipse.platform.ui/tests/org.eclipse.ui.tests
   no-classifier: different
      .gitignore: present in baseline only
   classifier-sources: not present in baseline
    The main artifact has been replaced with the baseline version.
    The following attached artifacts are not present in the baseline and have been removed: [sources]
```

**Comment by mickaelistria** [comment]
> .gitignore: present in baseline only

Bundle needs to be touched and get a new qualifier for newer build (without .gitignore) to be produced and published

**Comment by akurtakov** [comment]
Right, commit https://github.com/eclipse-platform/eclipse.platform.ui/commit/d5b54bcef5c3cc34751b23f08fd73155c383042f caused the .gitignore to be added and not shown as comparator error. I'll touch the bundle.
