### ISSUE TITLE
Materializing a Linux RCP Application using zip loses executable attribute

### ISSUE THREAD

**Issue by andrew-tram** [eclipse/tycho#974]
When trying to materialize a Linux RCP application as a `zip` instead of a `tar.gz`, the executable attribute gets lost.

```
<configuration>
	<formats>
		<linux>zip</linux>
	</formats>
</configuration>
```

A temporary work around would be to use `<artifactId>maven-antrun-plugin</artifactId>` and programmatically `chmod +x` executables. But I believe it's a bug with Tycho as the attributes remain intact when using tar.gz instead.

**Comment by laeubi** [comment]
This is a limitation of the zip format, and thus `tar.gz` is recommended here.
