### ISSUE TITLE
Remove the org.osgi.framework.bootdelegation from profiles

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#975]
I noticed we define some `org.osgi.framework.bootdelegation` like this in profiles:

```
org.osgi.framework.bootdelegation = \
 javax.*,\
 org.ietf.jgss,\
 org.omg.*,\
 org.w3c.*,\
 org.xml.*,\
 sun.*,\
 com.sun.*
```

we should try to remove them from the profiles as with modular vms all packages should be imported instead of boot delegated.

**Comment by akurtakov** [comment]
I see this one after I commented on the patch. Do you have some links on the topic to educate myself?

**Comment by laeubi** [comment]
I think https://wiki.eclipse.org/Equinox_Boot_Delegation might be a starting point.

**Comment by akurtakov** [comment]
Thanks, I'm aware of that I was more looking about changes for/with modular VMs.

**Comment by laeubi** [comment]
> Thanks, I'm aware of that I was more looking about changes for/with modular VMs.

There is no real "change" especially as profiles are Equinox specific. But Equinox offers the `osgi.compatibility.bootdelegation` what is default to true for eclipse and thus PDE do not "complain" if you do not import the packages in the manifest listed here.
That might be the reason why they are listed here. But given we use a modular vm, these packages are no longer provided by the vm so it is kind of useless anyways, so my idea was to remove those.

**Comment by akurtakov** [comment]
OK. let's do that then.

**Comment by laeubi** [comment]
Yep, I think we should give it a try :-)

**Comment by laeubi** [comment]
Done with https://github.com/eclipse/tycho/pull/976
