### ISSUE TITLE
Exception parsing OSGi MANIFEST: Unknown OSGi execution environment: 'JavaSE-1.5'

### ISSUE THREAD

**Issue by sewe** [eclipse/tycho#98]
It get this exception (using both Tycho 2.0.0 and the latest 2.4.0-SNAPSHOT from `master`) when building against https://subclipse.github.io/updates/subclipse/4.3.x/:

```
[ERROR] Internal error: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST /home/sewe/.m2/repository/p2/osgi/bundle/org.tmatesoft.sqljet/1.1.13.r1341/org.tmatesoft.sqljet-1.1.13.r1341.jar!/META-INF/MANIFEST.MF: Unknown OSGi execution environment: 'JavaSE-1.5' -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST /home/sewe/.m2/repository/p2/osgi/bundle/org.tmatesoft.sqljet/1.1.13.r1341/org.tmatesoft.sqljet-1.1.13.r1341.jar!/META-INF/MANIFEST.MF: Unknown OSGi execution environment: 'JavaSE-1.5'
```

The relevant header fields from the manifest in question look like this:

```
Bundle-RequiredExecutionEnvironment: JavaSE-1.5
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.5))"
```

**Comment by sewe** [comment]
While the Eclipse PDE manifest editor inserts `J2SE-1.5` rather than `JavaSE-1.5`, at least [in an example](https://osgi.github.io/osgi/core/framework.module.html#framework.module.bree) the OSGi Core spec lists both spellings for Java 1.4: `J2SE-1.4` and `JavaSE-1.4`:

```
org.osgi.framework.executionenvironment = 
     JavaSE-1.5, J2SE-1.4, JavaSE-1.4, JavaSE-1.3, OSGi/Minimum-1.1
```

I couldn't find a complete list of valid execution-environment names yet, however.

**Comment by mickaelistria** [comment]
There is https://docs.osgi.org/reference/eenames.html which seems up-to-date (at least knows about JavaSE-17) and specifies it's J2SE-1.5.

**Comment by sewe** [comment]
> There is https://docs.osgi.org/reference/eenames.html which seems up-to-date (at least knows about JavaSE-17) and specifies it's J2SE-1.5.

True, but https://docs.osgi.org/reference/eenames.html#osgiee-capability also lists the **capability** as being `JavaSE` **for all  version numbers**:

> Java (2) SE. Prior to Java SE 9 the version numbers to be used  are 1.5, 1.6, etc. Starting with Java SE 9, the version numbers to be  used are 9, 10, etc.

So the rules for `Bundle-RequiredExecutionEnvironment` seem to be different; the capability apparently was always called `JavaSE`, whereas the BREE shorthand changed over time.

Unfortunately, the bundle I have is inconsistent:

```
Bundle-RequiredExecutionEnvironment: JavaSE-1.5
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.5))"
```

The `Require-Capability` seems to be correct, but the `Bundle-RequiredExecutionEnvironment` isn’t. Now, the [OSGi spec](https://osgi.github.io/osgi/core/framework.module.html#framework.module.bree) says tgat "[b]undles should not mix these headers but use either an osgi.ee requirement or this header. If both are used, both constraints must be met to resolve."

So maybe Tycho is behaving correctly and can resolve the `Require-Capability` but not the broken `Bundle-RequiredExecutionEnvironment`. Will do some local tests and report back on it.

**Comment by sewe** [comment]
> So maybe Tycho is behaving correctly and can resolve the Require-Capability but not the broken Bundle-RequiredExecutionEnvironment. Will do some local tests and report back on it.

I manually patched my `org.tmatesoft.sqljet-1.1.13.r1341.jar`'s manifest:

```
Bundle-RequiredExecutionEnvironment: J2SE-1.5
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.5))"
```

This works. I think we can close this bug and I will report the issue upstream.
