### ISSUE TITLE
Wrong compiler target level used if using older BREE that's not available in toolchains

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/tycho#998]
This seems to be a major regression from recent https://github.com/eclipse/tycho/commit/7d59f3320cf3096956442d5d7ad4e054f07ac0b6 ; and luckily it is visible at the moment with an error in some cases while it is very likely to be silently failing in many other cases.
If trying to build a bundle with an older BREE that the one currently used to run Tycho and that target version is not in toolchains, then the compiler takes the current Java version as target for compiled code. For example, if I try to build with Java 17 a bundle that is using BREE=JavaSE-11 and don't have Java 11 in toolchain, then the compiler builds with source/target/release=Java 17, so the output is wrong and no major error is shown. Luckily, at the moment, the issue I faced was another case: I'm running with Java 18 a bundle that target JavaSE-17 in BREE, and I got an error that current ECJ doesn't support `-target 18`.

**Comment by mickaelistria** [comment]
I'm reverting https://github.com/eclipse/tycho/commit/7d59f3320cf3096956442d5d7ad4e054f07ac0b6 before it critically impacts Platform or other projects that would suddenly produce invalid bundles

**Comment by mickaelistria** [comment]
I'm really astonished that there is no test case that covers that story; it is critical that we implement one before re-working on the topic of profiles/EEs.

**Comment by laeubi** [comment]
> I'm reverting [7d59f33](https://github.com/eclipse/tycho/commit/7d59f3320cf3096956442d5d7ad4e054f07ac0b6) before it critically impacts Platform or other projects that would suddenly produce invalid bundles

Platform has almost all java versions in the tool-chains so its quite unlikely that there are any issues.

> I'm really astonished that there is no test case that covers that story

So if there is no test case this was a hidden feature :-) I'll try to enhance the testcase to reveal this issue, it just would have been easier without reverting this change so I will include it in reverting the revert so hopefully we can merge a fixed version soon including the test-case as current Tycho lacks the possibility to test this:

1. We only support a fixed set of BREEs (11, 17, 18)
2. if not using any of the fixed one Tycho fails
3. all our setups currently include 11+17 in the tool-chains (and 18 is not supported)

**Comment by mickaelistria** [comment]
> So if there is no test case this was a hidden feature :-)

Yes, but a feature that is widely used!

> I'll try to enhance the testcase to reveal this issue,

Thanks. Do you think it would be possible to get a test case working against the current code that we could include in a preliminary commit? I can try to write one if you cannot do it right now.

>  it just would have been easier without reverting this change

Yes, but the risk of having false-positive output in downstream project was too big to take the risk. This problem would have become a problem factory and over the night, we'd had broken 5-6 other projects.

**Comment by laeubi** [comment]
I have created a build here that only enhances the test-case: https://github.com/laeubi/tycho/commit/51ede810278c1e61bcd3b215df38abad627070e5 and fails if you apply my patch.

With current code-base, as described above it is hard to accomplish, because Tycho simply do not support this, e.g. whatever JVM you use it always uses the settings from the hard-coded profiles, so the previous test already covered the case but only for hard-coded defaults. I changed that test to use the build java version and thus this check was lost, but https://github.com/laeubi/tycho/commit/51ede810278c1e61bcd3b215df38abad627070e5 recovers that.

**Comment by laeubi** [comment]
This should be fixed now as well or do you see any issues with that fixed version? The problem was that before it used the foll profile not just the packages. So you could try out my branch and of course we can add more test afterwards, but the described issue should be fixed.

**Comment by mickaelistria** [comment]
> This should be fixed now as well or do you see any issues with that fixed version? 

I'll give it a try right now.

**Comment by mickaelistria** [comment]
I tried the PR #1002 and it seems file. Should I also try your branch or is the PR good enough?
